### ISSUE TITLE
Do there any blockers to bump new release?

### ISSUE THREAD

**Issue by idegtiarov** [jazzband/django-oauth-toolkit#1000]
We are looking forward to using `django-auth-toolkit` with Django 3.2 

Required PR is already merged into master branch #968.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by idegtiarov** [comment]
@Andrew-Chen-Wang @alexmclarty any thoughts related to my question?

**Comment by auvipy** [comment]
@n2ygk hi O:)

**Comment by Andrew-Chen-Wang** [comment]
I don't have release permission @idegtiarov

**Comment by alexmclarty** [comment]
I don’t have permission either @idegtiarov

**Comment by idegtiarov** [comment]
@Andrew-Chen-Wang  @alexmclarty  thanks for the reply!!!

@auvipy thanks for pointing to the right person, if I understand correctly your message ))))

@n2ygk I looking forward to hearing a word from you.

**Comment by daadu** [comment]
any ETA?

**Comment by idegtiarov** [comment]
Hey, @n2ygk any news so far?

**Comment by rejuls** [comment]
Hey, possible to do this release soon? We're in the process of updating our codebase to Django 3.2 and desperately need support for this package

**Comment by Andrew-Chen-Wang** [comment]
@jezdez can you perform the release?

**Comment by dannosaur** [comment]
I too could do with a release containing the unreleased changes. Specifically I need the resolution to #712 to exist. Any news when we might see a published release?

**Comment by jezdez** [comment]
@auvipy Please prepare a release branch (with changelog update etc) and assign the review of that PR to the project leads @n2ygk and @MattBlack85. Security-critical projects like this one need some extra care before doing the releases.

**Comment by idegtiarov** [comment]
Hey, @auvipy any updates on the new release branch? Winter is coming! ))))

**Comment by auvipy** [comment]
> Hey, @auvipy any updates on the new release branch? Winter is coming! ))))

dont worry, im from tropical region! joke apart very likely this week end

**Comment by idegtiarov** [comment]
@auvipy  Please say that week at which ends we can celebrate the new bumped release is close! ))) 

Could you share any recent news, ETA, something?

Thank you in advance.

**Comment by wolendranh** [comment]
HI @auvipy @idegtiarov ! 

Any updates on new release? It seems like 3 month passed since this issue was started...

**Comment by auvipy** [comment]
FWIW, I am not the project lead & I am busy with the projects I have leading likeish role. I was in vacation as well, so now clearing  the backlogs of the projects I lead & have some commercial involvement. TIA for understanding.

**Comment by natabene** [comment]
@auvipy Thank you so much for an update, I appreciate!

**Comment by idegtiarov** [comment]
@auvipy Thank you for your work on that project and help with the current issue specifically. I know we are pushing on you very much and we are impatient. If you know a way I can help you with the issue, please do not hesitate to write to me.

Thank you again!

**Comment by n2ygk** [comment]
Hey! I saw a [request](https://github.com/jazzband/django-oauth-toolkit/issues/1000#issuecomment-948504056) from @jezdez back in October to package up a release PR and assign to me and @MattBlack85 for review. I'm still waiting. If @auvipy can't do it, I'm sure someone else can.

**Comment by Andrew-Chen-Wang** [comment]
@n2ygk created a PR #1038 for CHANGELOG entry. Also hoping to merge PR #1039 before release. Cheers, and thanks for the response 👍
