### ISSUE TITLE
How to use jwt tokens in django-oauth-toolkit without adding to the database?

### ISSUE THREAD

**Issue by Suldenkov** [jazzband/django-oauth-toolkit#1027]
I have been working on separating the authorization server and the resource server using django-oauth-toolkit. Also I wrote my jwt token generator:

```
from rest_framework_simplejwt.tokens import RefreshToken

def my_acces_token_generator (request, refresh_token = False):
    refresh = RefreshToken.for_user (request.user)
    return str (refresh.access_token)

def my_refresh_token_generator (request, refresh_token = False):
    refresh = RefreshToken.for_user (request.user)
    return str (refresh)
```
And now I noticed that my jwt tokens are added to the database created by django-oauth-toolkit, but the essence of jwt is not to store them in the database. Tell me how to do it all rummaged through I can not find anything.

![Снимок](https://user-images.githubusercontent.com/45039914/141380761-01edc794-ffb2-4e4d-8694-f6d04dac08e0.PNG)

**Comment by n2ygk** [comment]
As currently implemented, it is not possible to do this. Feel free to submit a PR if you are able to figure out how to do it.
