### ISSUE TITLE
Logic for interraction thought oauth

### ISSUE THREAD

**Issue by jmlefevre-inartco** [jazzband/django-oauth-toolkit#1028]
Hi,
I would like to implement an auth server with these conditions:
- There are people into group A that can log into a website thought an interface. For example, a group of student.
- There are people into group B that can log into the same website as A thought a interface but have access to different features.
- When a people from group B want to interact with group A, group B must send a request to  someone in group A. When this person in group A answer positively to the request from group B, the people from group B (only the request sender) can access data from group A and the people from group A can interact with some of the feature of the person from group B. 
- Whenever he wants, the one from group A can revoke the access to his data that was accessible from the one from group B. The feature own by the one from group B that were available to the one of group A  is no more available. 

As an example, there is a group of students and a group of teacher.  When a teacher, called Mark contact Jim who is a student,  Jim accept the contact. Then Jim can access document, lesson, video ... of Mark. Also Mark can access to Jim notebook, agenda ... 
When Jim decides to break to stop, then Mark can't access Jim notebook, agenda and Jim can't access anymore to Mark's lesson, video, document. 

How would you do that ? Using different realms and approbation between realms ? Create many applications ? Using scope ? 
What would be the best practice ? Could someone share some example ? a good tutorial ? an rfc link ? 

Thanks in advance !

**Comment by n2ygk** [comment]
Hmm, pretty complicated questions. Here's a training example that uses OIDC claims, etc that might be helpful: https://columbia-it-django-jsonapi-training.readthedocs.io/en/latest/
