### ISSUE TITLE
Is silent renew supported?

### ISSUE THREAD

**Issue by dopry** [jazzband/django-oauth-toolkit#1040]
Silent Renew has become more common than refresh tokens for SPAs as far as I can tell. Does Django OAuthToolkit support silent renew?

**Comment by n2ygk** [comment]
Do you mean using Implicit flow? The forthcoming [OAuth 2.1](https://oauth.net/2.1/) specification drops Implicit in lieu of using Authorization Code flow with PKCE in SPAs for security reasons. With Authorization Code flow you can use Refresh tokens.

**Comment by dopry** [comment]
No. I mean silent renewal. Where a refresh token is not provided but a hidden iframe is opened to the idp to fetch a new access token if a session is still active. https://auth0.com/docs/authenticate/login/configure-silent-authentication

**Comment by n2ygk** [comment]
@dopry Have you tried using it? It's in the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html) which is listed as supported by upstream [oauthlib](https://oauthlib.readthedocs.io/en/latest/feature_matrix.html)

**Comment by dopry** [comment]
It does seem to. so all is good.
