### ISSUE TITLE
RTFD builds failing since Django 4.0 release

### ISSUE THREAD

**Issue by n2ygk** [jazzband/django-oauth-toolkit#1047]
**Describe the bug**

readthedocs.io builds have been failing since 10 December 2021.

**To Reproduce**

Take a look at https://readthedocs.org/projects/django-oauth-toolkit/builds/15504196/

**Expected behavior**

Builds should succeed

**Version**

1.5.0, 1.6.0

- [x] I have tested with the latest published release and it's still a problem.
- [x] I have tested with the master branch and it's still a problem.

**Additional context**

~The likely cause is the 7 December 2021 [release of Django 4.0](https://pypi.org/project/Django/4.0/#history)~

**Comment by n2ygk** [comment]
Or this change:
```diff
(dot-venv) django-oauth-toolkit$ git diff 1.5.0  .github/workflows/test.yml 
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index 7d257b4..08d2ddc 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,7 +9,7 @@ jobs:
       fail-fast: false
       max-parallel: 5
       matrix:
-        python-version: ['3.6', '3.7', '3.8', '3.9']
+        python-version: ['3.7', '3.8', '3.9', '3.10']
 
     steps:
     - uses: actions/checkout@v2
@@ -37,7 +37,7 @@ jobs:
     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
-        python -m pip install --upgrade tox tox-gh-actions
+        python -m pip install --upgrade tox tox-gh-actions django
 
     - name: Tox tests
       run: |
```

```
commit 345122881424897a2907312db52fafad9bbaa5f1
Author: Peter Carnesciali <pcarn9@gmail.com>
Date:   Fri Dec 10 10:05:37 2021 -0600

    Removes default_app_config for Django Deprecation Warning (#1035)
    
    * Removes default_app_config for Django Deprecation Warning
    
    * Update AUTHORS
    
    * Update __init__.py
    
    * import django
    
    * Install django so tox tests work
    
    * Pin mistune to fix docs

```

not sure how/why the tox tests didn't work before this change...

**Comment by pcarn** [comment]
That commit is showing in reverse, it was adding django to `__init__`, to check the version.

https://github.com/jazzband/django-oauth-toolkit/commit/345122881424897a2907312db52fafad9bbaa5f1

**Comment by pcarn** [comment]
I don't have access to those builds, but installing django as part of the build setup should fix it.

**Comment by n2ygk** [comment]
> That commit is showing in reverse, it was adding django to `__init__`, to check the version.
> 
> [3451228](https://github.com/jazzband/django-oauth-toolkit/commit/345122881424897a2907312db52fafad9bbaa5f1)

D'oh!

**Comment by n2ygk** [comment]
> I don't have access to those builds, but installing django as part of the build setup should fix it.

Still trying to understand what changed since it was building fine up until 10 December.

**Comment by pcarn** [comment]
What changed is the `import django` line I added to `__init__.py`, the doc build is now failing because django can't be imported.

Django is in docs/requirements.txt though, so I thought that should work. Perhaps the init is happening before it's being installed or something.

**Comment by n2ygk** [comment]
@pcarn Since merging #1048 the docs [build](https://readthedocs.org/projects/django-oauth-toolkit/builds/15584826/) is now reporting a new missing package:

```
ModuleNotFoundError: No module named 'setuptools._distutils'
```

**Comment by pcarn** [comment]
Where is the config for this command in that docs build? 
```
/home/docs/checkouts/readthedocs.org/user_builds/django-oauth-toolkit/envs/latest/bin/python -m pip install --upgrade --no-cache-dir -I mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<2.2
```

Adding django to that might solve it.

**Comment by n2ygk** [comment]
I've got to take a deeper look, I'm bugging you since the first time the builds started failing was with your commit so something changed at that point. And the error change to setuptool missing once you moved the django dependency in the tox.ini.

I checked the rtfd config and it didn't have docs/requirements.txt, which is weird since how was it working before?

**Comment by pcarn** [comment]
I think it worked before because django wasn't a direct dependency for it, and I'm guessing setuptools is downstream from that.

I don't have access to the config for the docs build, so I can only guess on what needs to change there.
