### ISSUE TITLE
How to Run a Single test.

### ISSUE THREAD

**Issue by wagnerdelima** [jazzband/django-oauth-toolkit#1059]
How to Run a Single test.

I opened this Draft Pr here: https://github.com/jazzband/django-oauth-toolkit/pull/1058
 I would like to tacke the broken tests, however, I don't know how to run tests on its own without running everything via  tox. 

Can anyone help?

**Comment by n2ygk** [comment]
@wagnerdelima like this with tox:
```
django-oauth-toolkit$ tox -e py39-dj32 tests/test_application_views.py 
```

or install the requirements in a venv and run pytest manually which is a bit of a pain. Something like this:

```
django-oauth-toolkit$ python -m venv ../dot-venv
django-oauth-toolkit$ source ../dot-venv/bin/activate
(dot-venv) django-oauth-toolkit$ pip install 'django<3.3' djangorestframework 'oauthlib>=3.0' jwcrypto pytest pytest-cov pytest-django pytest-xdist pytest-mock
(dot-venv) django-oauth-toolkit$ pip install -e .
(dot-venv) django-oauth-toolkit$ DJANGO_SETTINGS_MODULE=tests.settings pytest tests/test_authorization_code.py 
```

**Comment by wagnerdelima** [comment]
O thank you @n2ygk.
