### ISSUE TITLE
Backwards-incompatible API change in OAuth2Validator in 1.6.0

### ISSUE THREAD

**Issue by Natureshadow** [jazzband/django-oauth-toolkit#1066]
**Describe the bug**

PR #967 changed the API for `OAuth2Validator.get_additional_claims` in a backwards-incompatible way (and the project major version has not been bumped, which would have been required by semantic versioning).

Specifically, the `request` argument was removed, which we relied upon downstream. It seems that the functionality has remained (in a slightly more complex way), but such breakage is not expected between minor versions.

I propose to revert the change in 1.6.1, and make a new release 2.0.0 introducing the breaking change.

**Expected behavior**

We expect the (documented) API not to break backwords-incompatibly in minor versions.

**Version**
1.6.0

**Comment by Natureshadow** [comment]
Then again, reverting the change in a 1.6.1 release would be a breaking change compared to 1.6.0. So the situation cannot be fixed, unless a 1.6.1 release re-introduces the old API, but keeps the new API as well.

**Comment by n2ygk** [comment]
Oh, that's not good. 

I'd say we should put fixing this on the queue for 1.7.0 but then you'd say it's a major change and it should be 2.0. We've tried to adopt semver -- the project previously had not used it -- and it seems we missed this as being a breaking fix.

Need to research what happened here and come up with a plan. Meanwhile go ahead and temporarily pin <1.6.0.

**Comment by n2ygk** [comment]
I think we need to revert this PR and issue 1.6.2. That will require some git branch games as we've already merged a bunch of new 1.7.0 changes.
