### ISSUE TITLE
Can I restrict an endpoint to and application

### ISSUE THREAD

**Issue by rick2ricks** [jazzband/django-oauth-toolkit#1079]
Hi, I would like to create and endpoint exclusively for another server to use, without any user involved, but I am having some difficulty to do it.

Can this be done with restricting access to applications? and how?

Thanks.

**Comment by n2ygk** [comment]
I believe what you are referring to is client_credentials flow.
You restrict access to the "application" by not sharing the client_secret with anyone but the authorized server. It's like doing HTTP Basic Auth between two backend servers but uses OAuth2 which has some advantages.

**Comment by rick2ricks** [comment]
Actually I meant the verification of which application is accessing the endpoint, users should authenticate using other applications but not be allowed to access this specific endpoint.

**Comment by n2ygk** [comment]
If I understand what you are saying, it's authorization that you are looking to do vs. authentication. We are being a bit loose with the terminology here which is I think part of the problem with my understanding your question.

Maybe use [RFC 6749 these role names](https://datatracker.ietf.org/doc/html/rfc6749#section-1.1) to explain the problem.

```
OAuth defines four roles:

   resource owner
      An entity capable of granting access to a protected resource.
      When the resource owner is a person, it is referred to as an
      end-user.

   resource server
      The server hosting the protected resources, capable of accepting
      and responding to protected resource requests using access tokens.

   client
      An application making protected resource requests on behalf of the
      resource owner and with its authorization.  The term "client" does
      not imply any particular implementation characteristics (e.g.,
      whether the application executes on a server, a desktop, or other
      devices).

   authorization server
      The server issuing access tokens to the client after successfully
      authenticating the resource owner and obtaining authorization.
```
So I think by endpoint you mean resource server. By user do you mean resource owner? By application do you mean client?

In OAuth 2 parlance, the client (application) is a 3rd party that the resource owner (end user) grants specific scopes of authorization to. The client then presents those user-authorized scopes to the resource server (backend endpoint) via the Access Token which makes the authorization decision of whether the client is allowed to do what's being requested (e.g. GET/POST/etc.).
So you can check in the resource server to see if certain scopes have been granted -- or, using OIDC, check for certain claims.

If you are using Django REST Framework these are implemented with permissions: https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/permissions.html

**Comment by rick2ricks** [comment]
Sure, I am sorry, this topic really requires the terminology. You are right, I used the term application to refer client because it is the term used by oauth-toolkit when you register a client, and by endpoint I mean one resource in the resource server.

Basically what I am going to do is to schedule an aws lambda function to call this endpoint in my resource server periodically to execute some tasks, but  I don't want to authorize it to access any other resource neither other users to access this endpoint.

So, what I want to know is how to authorize only this first party client to access this resource and restrict it from other resources. ( verify which client it is, without any user authenticating ) 

ps: Probably I am just trying to use client in the wrong way, and my lambda should also be an user instead of beeing only the client.

**Comment by n2ygk** [comment]
Ok so you are talking about using Client Credentials flow since there's no human.

In other OAuth2 AS implementations I am familiar with (we use PingFederate), one can restrict scopes only to be request by specific clients and then the resource server can check to see if that scope was granted. I don't believe this feature exists in DOT.

However, you can have your resource server check the client_id which is provided as part of the token introspection response: Only the client that knows that client_id's secret would be able to have that client_id.

Does that make sense?

**Comment by rick2ricks** [comment]
Hi, thank you.

Yes totally makes sense, I thought about restricting scopes but as I couldn't find it on documentation, I imagined it wasn't supposed to do that.

As my use case does not deserve that much effort, I will go for a simpler approach, just verifying some secret on this specific resource.

Thank you for the help and clarification.
