### ISSUE TITLE
Default value for CLEAR_EXPIRED_TOKENS_BATCH_INTERVAL

### ISSUE THREAD

**Issue by n2ygk** [jazzband/django-oauth-toolkit#1087]
@merito Sorry this is after the fact but wouldn't a default value of 0 be best, especially since the sleep is always executed even if the batch is tiny.
https://github.com/merito/django-oauth-toolkit/blob/725c3c9d8927379c9808abd1badb4fcd9ff1cbaa/oauth2_provider/models.py#L636

_Originally posted by @n2ygk in https://github.com/jazzband/django-oauth-toolkit/pull/969#discussion_r782459085_

**Comment by n2ygk** [comment]
I was enhancing and running the `clear_expired` tests and notice that the test was taking .4 sec longer than it should have;-)

**Comment by folt** [comment]
Can you describe what problem you are trying to solve with this PR?

**Comment by n2ygk** [comment]
@folt to further clarify, here's the code snippet:
https://github.com/jazzband/django-oauth-toolkit/blob/ac201526843ff63ad3861bb37e4099521cff091a/oauth2_provider/models.py#L630-L637
