### ISSUE TITLE
Protecting application registration view?

### ISSUE THREAD

**Issue by bombnp** [jazzband/django-oauth-toolkit#1094]
Hi, is it possible to protect the views in `/applications/*` for only users in a specific Django group? I want to create an api that only allows creating oauth2 applications to some selected group of people.

Thanks!

**Comment by n2ygk** [comment]
This sounds a lot like #1079

**Comment by bombnp** [comment]
I managed to solve this by manually adding the paths in DOT's urls.py file (specifically, `base_urlpatterns` and `management_urlpatterns`), instead of include()-ing the entire module. I used [django-decorator-include](https://pypi.org/project/django-decorator-include/) to protect `management_urlpatterns` with my own auth decorator logic, while include()-ing `base_urlpatterns` normally.
