### ISSUE TITLE
OpenID Connect

### ISSUE THREAD

**Issue by lsmag** [jazzband/django-oauth-toolkit#110]
Hello,

I was waiting for the approval of the OpenID Connect [spec](http://openid.net/connect/), and now it's approved, I wonder if you would like a pull request with that feature (the "OpenID connector" part on your roadmap refers to that, right?)

I'm already learning the [Core spec](http://openid.net/specs/openid-connect-core-1_0.html) to figure out how it can be implemented. It seems like a thin layer on top of OAuth2, for example the authentication part is done by a request to `/o/authorize` with "openid" as one of the scopes, and the token exchange now returns one more parameter, the ID Token.

There's two more (optional) specs, but my intent is implement the core on top of django-oauth-toolkit, since it seems enough to be an OpenID provider. I'm already reading django-oauth-toolkit's source code, but any tips are welcome.

So, what do you think?

**Comment by clintonb** [comment]
@lsmag What is the status of the OIDC integration?

**Comment by juanifioren** [comment]
@clintonb I follow both oauthlib and this project about their OIDC implementations but they seem to be stuck. Also was trying to implement it by my self but I ended up with a mess in oauthlib.

So I started from the ground up building a provider on top of Django. Check it out if u are interested:

https://github.com/juanifioren/django-openid-provider

I recently test it with the OpenID Connect Drupal Module (with a fresh drupal installation) and the user logged in perfectly (also the account was created in drupal).

Theres a lot of things to improve and to add.

Greetings.

**Comment by clintonb** [comment]
Thanks @juanifiorien. We also built our own (https://github.com/edx/edx-oauth2-provider) atop django-oauth2-provider. That project, however, seems to have stalled. I was hoping to transition to toolkit and take advantage of other features (e.g. client registration views) instead of starting from scratch.

**Comment by clintonb** [comment]
@juanifioren ^

**Comment by juanifioren** [comment]
I'll check it out, thanks @clintonb

**Comment by clintonb** [comment]
Has anyone made any progress on adding OIDC support to this project?

**Comment by markslwong** [comment]
This feature would certainly help me :+1: I would volunteer to help, but when it comes to framework code... I'm not sure you want a primarily C# and C++ developer making pull requests.

**Comment by ntcong** [comment]
There's some process lately in order to support openid connect in oauthlib: https://github.com/idan/oauthlib/pull/416

**Comment by joelstevenson** [comment]
Hello DOT-ers, FWIW I [have a fork of DOT](https://github.com/joelstevenson/django-oauth-toolkit) that integrates at a basic level with the [oauthlib PR #416](https://github.com/idan/oauthlib/pull/416) @ntcong mentioned.  This is a minimal implementation I needed to get the basic Authorization Code flow completed.  I'd appreciate any feedback you all might have and any ideas for improvements or different approaches.

**Comment by ntcong** [comment]
@joelstevenson Now that oauthlib's openid connect implement was merged, I think it's a good time to make a PR request ?

**Comment by pichlou** [comment]
@juanifioren @clintonb wich one of the OIDC provider and the edX OAuth2 Provider is better for using in Django application on edx-platform?(please write reasons of your choice)

**Comment by clintonb** [comment]
@pichlou we are planning to abandon usage of OIDC. The limited library support, and lack of time/resources on our part to add support to DOT, makes it difficult to continue using OIDC. That being said, our two years of using it have taught us a lot. Particularly, OIDC at is core is just OAuth with a short-lived JWT access token. Given that we already plan to switch to JWT access tokens, we are already partially where we want to be.

I'm happy to share more in the edX architecture Slack channel.

**Comment by pichlou** [comment]
Thanks @clintonb !

**Comment by juanifioren** [comment]
@pichlou It depends on your needs. `django-oidc-provider` is an active project which provides a robust platform for SSO based on OIDC and OAuth2.

Cool features of DOP:

* Session management support.
* Manage your clients easily using django admin (choose id_token alg, bautomatic secret and id).
* PKCE support for mobile implementations (you can use [AppAuth-iOS](https://openid.github.io/AppAuth-iOS/) and [AppAuth-Android](https://openid.github.io/AppAuth-Android/)).
* You can create your custom scopes and claims.
* Add custom data inside ID Tokens to fit your needs.
* Refresh token flow support.
* A lot more things, just read our docs http://django-oidc-provider.readthedocs.io/

Any other question please contact me.
Regards!

**Comment by pichlou** [comment]
Many thanks @juanifioren !
I wish you luck ...

**Comment by wiliamsouza** [comment]
Maybe someone have interest on this PR https://github.com/idan/oauthlib/pull/484

**Comment by jleclanche** [comment]
@juanifioren How similar is django-oidc-provider to django-oauth-toolkit? Would it make sense to merge the two libs? (I'm up for helping in that regard, or at least making our APIs more consistent across one another)

**Comment by juanifioren** [comment]
@jleclanche libs have differents approaches. DOP is a django-app for easily implement OIDC in your project. DOT is for developers and you need to put some code to make it works. That's what I think.

**Comment by jleclanche** [comment]
The reason I was asking is because DOP has PKCE support, which DOT should really support as well. Hmm...

**Comment by wiliamsouza** [comment]
Work in progress https://github.com/evonove/django-oauth-toolkit/pull/545 would be great to have some inputs.

**Comment by n2ygk** [comment]
Target is to reintegrate reverted PR #859

**Comment by aleks-j** [comment]
Hey everyone, thanks for the wonderful work! @n2ygk Just wondering, are there any updates on that reintegration of OIDC? Cheers!
