### ISSUE TITLE
"error": "invalid_request",   "error_description": "Request is missing username parameter."

### ISSUE THREAD

**Issue by BevisAngello** [jazzband/django-oauth-toolkit#1110]
I'm using django-oauth-toolkit and I'm using  custom user model AUTH_USER_MODEL = 'core_user.User'  but whenever i try to register a user in my resource server to the authentication server  i get "error": "invalid_request",   "error_description": "Request is missing username parameter." yet I'm not using username in my custom user modal. What could I be doing wrong?

here is the register code

class RegistrationAdminViewSet(ModelViewSet, TokenView): 
    parser_classes = (MultiPartParser, FormParser )
    serializer_class = RegisterSuperAdminSerializer
    permission_classes = (AllowAny,)
    http_method_names = ['post']
    

    def create(self, request, *args, **kwargs):
        '''
        Registers user to the server. Input should be in the format:
        {"email": "email", "password": "1234abcd"}
        '''
        # Put the data from the request into the serializer
        serializer = RegisterSuperAdminSerializer(data=request.data)
        # Validate the data
        if serializer.is_valid():
            # If it is valid, save the data (creates a user).
            serializer.save()
            # Then we get a token for the created user.
            # This could be done differentley
            r = requests.post('http://127.0.0.1:8000/o/token/',
                          data={
                              'grant_type': 'password',
                           
                              'email': request.data['email'],
                              'password': request.data['password'],
                              'client_id': CLIENT_ID,
                              'client_secret': CLIENT_SECRET,
                          },
                          )
            return Response(r.json())
        return Response(serializer.errors)

**Comment by oryn2gs** [comment]
@BevisAngello I am getting the same error, when using the custom user.
` curl -X POST -d "grant_type=password&email=testusertwo@email.com&password=password" -u"hcIWWdYHp9CP1PPqLWcWExBv0XDdalfexcbu8ZPC:gF3xWtYhCRtu3jYCRc4RsdGvsDNESZAAE5pcSPuVqsnnmZyFuuojkBP4JjpYbAF1FyYX2jI6JkwY4sblV3e7lpbP28E12WB1ZZRJzmr9P0sgevg0gspimZFppiqGTvAY" http://localhost:8000/api/accounts/token/

{"error": "invalid_request", "error_description": "Request is missing username parameter."}%  
`

do you have any suggestion for me.
