### ISSUE TITLE
Release of version 2.0.0

### ISSUE THREAD

**Issue by fagnerzulin** [jazzband/django-oauth-toolkit#1138]
Hello everyone

I would like to know if there is any prediction for the 2.0.0 version to be released. Today it is unrealized in the doc, and has two vulnerability alerts for versions lower than it in the [safety](https://pyup.io/). Thank you!

**Comment by simara-svatopluk** [comment]
Hello,
I found related discussion https://github.com/pyupio/safety-db/issues/2353

In short.. the reason for alert is: https://github.com/pyupio/safety-db/blob/master/data/insecure.json#L1841

And reason for this reason is explained in the discussion above

**Comment by n2ygk** [comment]
https://github.com/pyupio/safety-db/issues/2353#issuecomment-1088608992

Thanks for the pointer. 

You can always use a git ref to the prerelease code now.
