### ISSUE TITLE
How to skip oauth2_views.AuthorizationView's LoginRequiredMixin

### ISSUE THREAD

**Issue by luohaoGit** [jazzband/django-oauth-toolkit#1140]
I want to use Authorization code grant type, but when I invoke /o/authorize/, it redirects to admin's login.
How can I skip admin login?

**Comment by andreasofthings** [comment]
Wouldn't that defeat the purpose of the endpoint? 
What would you be trying to achieve by doing so?
The redirect target should be configurable by `LOGIN_URL` in `settings.py`

**Comment by RockyMM** [comment]
Hi there. I am trying to set up a DRF-based app with DOT to integrate with an Alexa Skill. I've seen here in the repo that many had succeeded, but I cannot. The problem I'm facing is that our users are Django users, but they are **not** Django Admin users. 

The default form is the Django Admin login form. That form only allows Django admin users. 

Is there some documentation on how to provide a custom login form or any other workaround where we could allow non-admin users to be authenticated and authorized to /o/authorize/?
