### ISSUE TITLE
2.0.0: Client Secret Hasher Migration vs. Swapped Application Models

### ISSUE THREAD

**Issue by josephabrahams** [jazzband/django-oauth-toolkit#1146]
### Describe the bug

The forward migration introduced in #1093 to hash all previously saved client secrets runs on apps that use a custom application model and produces the following error:

```
AttributeError: Manager isn't available; 'oauth2_provider.Application' has been swapped for 'oauth.Application'
```

### To Reproduce

Define a custom application model in `settings.py`:

```
OAUTH2_PROVIDER_APPLICATION_MODEL = "oauth.Application"
```

Migrate the database:

```
$ python manage.py migrate
```

### Expected behavior

Migrations run when using a swappable application model without throwing an error.

### Version 2.0

- [x] I have tested with the latest published release and it's still a problem.
- [x] I have tested with the master branch and it's still a problem.

**Comment by josephabrahams** [comment]
Potential fix to only run the migration when not using a custom application model in https://github.com/josephabrahams/django-oauth-toolkit/commit/a123285bf1758d7f717a010549fca64052b5903c.

**Comment by n2ygk** [comment]
@josephabrahams Thanks for this report. Swappable models are the hardest part with this stuff!

Please submit your proposed fix as a PR where we can discuss. 

Thanks.
