### ISSUE TITLE
Getting started section is not up to date with 2.0 release

### ISSUE THREAD

**Issue by kiddick** [jazzband/django-oauth-toolkit#1153]
https://django-oauth-toolkit.readthedocs.io/en/latest/getting_started.html
This step 
`To start the Authorization code flow go to this [URL](http://127.0.0.1:8000/o/authorize/?response_type=code&client_id=vW1RcAl7Mb0d5gyHNQIAcH110lWoOW2BmWJIero8&redirect_uri=http://127.0.0.1:8000/noexist/callback) which is the same as shown below:` 
should be completed with form with permissions
<img width="776" alt="image" src="https://user-images.githubusercontent.com/9250239/167270785-6de654d1-400f-4ce4-97a4-63c752aab8a0.png">

although it is redirecting me with error in url `?error=invalid_request&error_description=Code+challenge+required.`
It is okay in 1.7 version

**Comment by n2ygk** [comment]
2.0 requires authorization_code with PKCE. I'm guessing the documentation needs to be update to show that. Please consider submitting a PR to fix the documentation.
