### ISSUE TITLE
"Client Credential grant" example (getting started) no longer works.

### ISSUE THREAD

**Issue by Beenhakker** [jazzband/django-oauth-toolkit#1155]
Might be related to https://github.com/jazzband/django-oauth-toolkit/issues/1153 (Getting started section is not up to date with 2.0 release - PCKE required)

The example (similar to the implementation we use) https://django-oauth-toolkit.readthedocs.io/en/latest/getting_started.html?highlight=CLIENT_CREDENTIALS#client-credential - worked fine for us before version <2.

After updating to version 2.0.0., this no longer works. I get the error "invalid_client". However, I did disable PKCE_REQUIRED:

`
OAUTH2_PROVIDER = {
    "SCOPES": {
        "read": "Read-only",
    },
    "ACCESS_TOKEN_EXPIRE_SECONDS": 180,
    "PKCE_REQUIRED": False,
}
`

Am I missing something? I did check the Changelog, but nothing else then PKCE_REQUIRED is mentioned.

**Comment by n2ygk** [comment]
client_secret captured before it was hashed?

**Comment by Beenhakker** [comment]
Ah, yes of course. We use a "fixed application", and no longer use the register views really.

I was unaware of the fact that this `client_secret` was encrypted from now on, and our tests broke.

It works by specifying a `client_secret` as argument to `ApplicationModel`, and store the plaintext version separately so we can reuse it later on.

Thanks.

**Comment by Beenhakker** [comment]
Hey, I did not know what parts it would affect. Excuse me for asking.

**Comment by Beenhakker** [comment]
Few things going on on my side. This application was just handed over to me last week, and I did not fully understand our implementation with the `django-oauth-toolkit`, so all in all it was very confusing.

Anyway, I underline this breaking change in the documentation, then it would be more obvious that something important has changed, since there was no difference between the 1.7.1. and the 2.0.0. documentation, which I thoroughly compared.

**Comment by n2ygk** [comment]
Fair point. We'll make sure the documentation adds information on major upgrades beyond what's in the changelog (which is technically part of the documentation;-)

**Comment by Beenhakker** [comment]
I was thinking more about the section I pointed to earlier: https://django-oauth-toolkit.readthedocs.io/en/latest/getting_started.html?highlight=CLIENT_CREDENTIALS#client-credential

Something in the line of "The `client_secrets` are stored encrypted."

**Comment by n2ygk** [comment]
Let's move this to #1157

A documentation PR would be wonderful.

**Comment by Beenhakker** [comment]
Sure.
