### ISSUE TITLE
while get access token from authorization_code then "error": "invalid_client"

### ISSUE THREAD

**Issue by jeelos33** [jazzband/django-oauth-toolkit#1161]
-------------my settings.py, applications in link:
https://drive.google.com/drive/folders/10mEKBcTRXj8CVE6Pp7p1qmosjm9L6iY7?usp=sharing
------------when i use curl:
curl -X POST -H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" "http://127.0.0.1:8000/o/token/" -d "client_id=${ID}" -d "client_secret=${SECRET}" -d "code=${CODE}" -d "redirect_uri=http://localhost:8000/home/" -d "grant_type=authorization_code"
-----------then error.(i exported CODE,SECRET,ID)

**Comment by n2ygk** [comment]
I suspect this is lack of PKCE. See documentation just updated by #1159 

Please confirm and close if so

**Comment by jeelos33** [comment]
I followed documentation then ..
![Screenshot from 2022-05-18 10-03-35](https://user-images.githubusercontent.com/104294750/168949006-e5d01da8-10a5-41ed-9fad-ce2b2fe1ce4b.png)

**Comment by jeelos33** [comment]
I got code but access token error
![Screenshot from 2022-05-18 10-27-40](https://user-images.githubusercontent.com/104294750/168951230-68b54350-cc82-40fb-b439-9453c7824943.png)

**Comment by bnsoni** [comment]
@jeelos33 Hi, i'm facing the same issue. Did you manage to resolve it?

**Comment by bnsoni** [comment]
@n2ygk Thank you so much for pointing that out! 
I didn't pay attention to the hashed secret, it's working now :)

**Comment by jeelos33** [comment]
I use the clear text client secret. if i use the client secret which is hashed then error "invalid_client"

**Comment by andres-root** [comment]
@n2ygk How do I get the clear text client secret?
