### ISSUE TITLE
can't make tutorial "getting started" , django-oauth-toolkit 	2.0.0

### ISSUE THREAD

**Issue by vebp** [jazzband/django-oauth-toolkit#1178]
hi good day

I can't make work the tutorial "getting started" from the docs
(sorry I know there are a couple of similars issues rised but still it seems there is some differences)

Django               	       4.0.5
django-oauth-toolkit 	2.0.0
OS					Ubuntu 20.04
python				3.8

I've been following the steps as appears in the docs but at the end the system delivers me the line

`{"error": "invalid_request", "error_description": "Code verifier required."}`

instead of the expected:

![view8](https://user-images.githubusercontent.com/47260282/174893012-71404377-e0fd-4faa-b29e-774fa3a73bb7.png)

These where my steps:

![view1](https://user-images.githubusercontent.com/47260282/174893036-5e726727-8c25-4d1d-bc28-a3b5ceee8738.png)
![view3](https://user-images.githubusercontent.com/47260282/174893053-df44527f-2741-4f53-9b15-26850186a0a6.png)
![view4](https://user-images.githubusercontent.com/47260282/174893091-b89aac4c-b376-47a6-8a3a-7700e9b010e4.png)

BTW, when you enters the url
[http://127.0.0.1:8000/o/applications/register/](http://127.0.0.1:8000/o/applications/register/)

the form has another field called "Algorithm" with 3 options:
- No OIDC support
- RSA with SHA-2 256
- HMAC with SHA-2 256

Which option should I choose at this step? The docs do not refers to it.
I tried with the first and the third but the steps didn't work with any of them. The second option gives me this strange error when I try to selected it.

![view2](https://user-images.githubusercontent.com/47260282/174893402-248b86ed-4cfb-4e42-96f3-fdf5f5db0a79.png)

Finally, and don't know if it was important, but when I tried to create the code_challenge, I had to change the line
`code_verifier = base64.urlsafe_b64encode(code_verifier)`
to
`code_verifier = base64.urlsafe_b64encode(code_verifier.encode('utf-8'))`
because I had an error that requests me to use a string.
Later the line
`code_challenge = hashlib.sha256(code_verifier.encode('utf-8')).digest()`
had to change to
`code_challenge = hashlib.sha256(code_verifier).digest()`

![view7](https://user-images.githubusercontent.com/47260282/174893637-15c3e7e5-326a-447d-b131-ff56de378c87.png)

What am I doing wrong?

(Thanks in advance)

**Comment by n2ygk** [comment]
@vebp Oh wow, I didn't even know (remember?) there was an http://127.0.0.1:8000/o/applications/register/ endpoint.  (I've never followed the tutorial apparently!) I always use the admin UI at http://127.0.0.1:8000/admin/oauth2_provider/application/add/. I'll have to look over the tutorial, but meanwhile, can you try using the admin endpoint? Also 2.1.0 was just published.

Also the Algorithm selection should be "No OIDC support".  See this screenshot:

![image](https://user-images.githubusercontent.com/4356471/175772293-78eb4173-a457-4f9b-a887-079aa976aa2b.png)

I can't comment on the code challenge other than to suggest you try using Postman first as in this screen shot, selecting "Authorization Code (With PKCE)":

<img width="593" alt="image" src="https://user-images.githubusercontent.com/4356471/175772478-022ff239-35ed-452a-ac26-2e270c9f948e.png">

Also, make sure your Application includes this redirect URI: `https://www.getpostman.com/oauth2/callback`

**Comment by vebp** [comment]
OK @n2ygk thanks a lot!, I'll try to do that. 
I've continued doing the tutorials and have a similar problem at Part 1 - Make a Provider in a Minute , in the following part "Tutorials". The truth is I imagine that most people is just interested in using  Django OAuth Toolkit integrated with Django-rest-framework (which is my case too) so maybe that’s why no one has noticed. Still, you may want to make the docs consistent.
I’ll let you know if a find a problem at django-rest-framework
Have a nice day and thanks again

**Comment by tartarini** [comment]
I've tested twice the getting started doc and end up with the same error
`{"error": "invalid_grant"}`

Setup:
Django==4.1
django-oauth-toolkit==2.1.0
Python 3.10.6

**Comment by g-normand** [comment]
@tartarini @n2ygk I'm having the same problem

I created an app via the admin interface
![Capture d’écran de 2022-11-23 17-13-57](https://user-images.githubusercontent.com/17318506/203655094-2f7ee039-265a-4f2a-a9de-886cf34b0838.png)

Then I went to the URL : 
http://127.0.0.1:8004/o/authorize/?response_type=code&code_challenge=RbkDsjQXkYq3gl-aMEy54xNEoTuxar-RC-KcMkBJ2Ek&code_challenge_method=S256&client_id=58GddGR3SkPligV2nzEdr9pNeBgx0o42X3Qe30Io&redirect_uri=http://127.0.0.1:8004/test/callback

![Capture d’écran de 2022-11-23 17-14-17](https://user-images.githubusercontent.com/17318506/203655101-2d4789a0-d363-4006-9150-7fedcd69b074.png)

It gave me the code IkSXDqCaUnJCkiGshCjCLJjR44sl9f
![Capture d’écran de 2022-11-23 17-14-21](https://user-images.githubusercontent.com/17318506/203655125-7d7c2d06-4070-4cc9-a79a-fd110f4a37bf.png)

I even changed the Grant:
![Capture d’écran de 2022-11-23 17-16-50](https://user-images.githubusercontent.com/17318506/203655229-b82118ca-8600-4005-b218-a2e01ed80437.png)

But still, it does not work : 

curl -X POST     "http://127.0.0.1:8004/o/token/"     -d "client_id=58GddGR3SkPligV2nzEdr9pNeBgx0o42X3Qe30Io"     -d "client_secret=Nbj1vy6l2zqvvSYOcPFQWFD5zsmbZmtJpU2zFYiiBsNfxKCPwVKoA35bLCGDTOoWOqAA1kucPFpQ3I7NEB8s6evSbIyZWhNepfPmY0nPCev2y9EOnhomFpKfHAjYTKpy"     -d "code=IkSXDqCaUnJCkiGshCjCLJjR44sl9f"     -d "code_verifier=RbkDsjQXkYq3gl-aMEy54xNEoTuxar-RC-KcMkBJ2Ek"     -d "redirect_uri=http://127.0.0.1:8004/test/callback"     -d "grant_type=authorization_code"

{"error": "invalid_grant"}

What can be wrong?! Thanks !
