### ISSUE TITLE
How does jazzband prevent malicious activities?

### ISSUE THREAD

**Issue by MT-Cash** [jazzband/django-oauth-toolkit#1179]
This is primarily a question about jazzband

I see that anybody can join. If I understand it right, there are no requirements and people immediately are granted the privileges to push to repositories (and to make releases on PyPI?).

How does jazzband prevent malicious activities?

How does jazzband prevent well-intentioned beginners from breaking things?

**Comment by n2ygk** [comment]
See https://jazzband.co/about/releases#security. Only project leads can push to PyPi. It's still possible for mistakes to cause issues and, as with all FOSS projects, we count on the community to help review the code and root out errors.
