### ISSUE TITLE
Why the request returns 'invalid_client'?

### ISSUE THREAD

**Issue by linneudm** [jazzband/django-oauth-toolkit#1193]
Hello everyone, everything good?

I'm trying to follow the tutorial for Django Rest Framework that is in the [documentation](https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html). I am not able to get a valid answer. I've seen some issues in the repo, some may even be the same case, but it's not clear to me where I'm going wrong.

Basically, I'm sending the request using curl with the following data:
`curl -X POST -d "grant_type=password&username=<admin>&password=<admin>" -u"<fEsQnQBsokTk5NB1xaZeLRaLgvbjZ3INGgFhgmFn>:<pbkdf2_sha256$320000$tYHgBpw9Sq6WZFV6u8ruDK$8Boq6kWNqGChvRbw33FbfduwnYz4vUhDcY8RzE1HuqE=>" http://localhost:8000/o/token/`

The Authorization grant type is: **Resource owner password-based**
The django-oauth-toolkit version is: 2.1.0

The response I get from the server is:
`{"error": "invalid_client"}`

Sorry if this seems repetitive. But it wasn't clear to me where I went wrong.

PS: The data presented here are not sensitive, as they are data to exemplify the error.

**Comment by JordiNeil** [comment]
It seems like you are using the client_secret stored after saving the application. Look it starts with `pbkdf...`, it means it's already hashed.
[This doc](https://django-oauth-toolkit.readthedocs.io/en/latest/changelog.html) says that you need to copy the `client_secret` before hitting save button in django admin. Because it's going to be hashed and stored. And you cannot unhash it, and if you use the hash, you're getting `invalid_client` error

**Comment by linneudm** [comment]
You're right, I was wrong to use the hashed string. This was a very grotesque mistake on my part. I hope this can help someone as foolish as me one day. Thanks for listening @JordiNeil !

**Comment by n2ygk** [comment]
Closing this.

**Comment by ArjunTudotechnologies** [comment]
Wow this saved us ...this should part of the documentation :)

**Comment by davideke1** [comment]
still having this issue can somone help out

**Comment by bhuiyanmobasshir94** [comment]
@JordiNeil you just saved my day man. It should be withing the documentation.

**Comment by n2ygk** [comment]
@bhuiyanmobasshir94 @ArjunTudotechnologies a [documentation improvement](https://django-oauth-toolkit.readthedocs.io/en/latest/contributing.html#documentation) PR would be greatly appreciated.
