### ISSUE TITLE
How to use with multi user accounts/organizations?

### ISSUE THREAD

**Issue by ritwickdsouza** [jazzband/django-oauth-toolkit#1198]
Our application has users that can have access to multiple organizations. Multiple users can also have access to an organization. (e.g. GitHub)

What would be the best way to use the library to only allow access to certain accounts/organizations that have been selected by the user on the authorize page?

Would love some feedback.

**Comment by dopry** [comment]
This is just an authentication module. Authorization (groups, etc) are a different concern. In general you could use scopes or some other mechanism. All this module well tell you is who is logged in, not what their permissions are. Sorry we can't help you here. Good Luck.
