### ISSUE TITLE
How to activate translations for oauth2 views

### ISSUE THREAD

**Issue by alemangui** [jazzband/django-oauth-toolkit#1206]
I am unable to display oauth pages in anything other than English.

I import the urls using
```python
path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
```

And I have specified the language and i18n settings in my project's `settings.py`:
```python
LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Europe/Paris"
USE_I18N = True
USE_L10N = True
USE_TZ = True
```

However, my `/o` pages are always in English.

The only i18n entry I found in the doc is about contributing translation files, but not on how to use them.

**Comment by JordiNeil** [comment]
Hi, you can follow [this tutorial](https://localizely.com/blog/django-i18n-tutorial/), you need to change `urls.py` (add your `oauth2_provider` urls to the `i18n_patterns`),  and `settings.py` (configure `MIDDLEWARE`, `LOCALE_PATHS`, and `LANGUAGES`) files
