### ISSUE TITLE
Need help! still invalid_client after unhashed secret

### ISSUE THREAD

**Issue by swpper** [jazzband/django-oauth-toolkit#1235]
Hello, I am new to Django and django-oauth-toolkit. I was learning with the [document](https://django-oauth-toolkit.readthedocs.io/en/latest/getting_started.html#client-credential), I saved the client secret before it was hashed. But still got `{"error": "invalid_client"}`. What was going wrong? 

The unhashed secret was saved and `PKCE_REQUIRED = False` already as said in [changelog](https://github.com/jazzband/django-oauth-toolkit/blob/master/CHANGELOG.md#220-2022-10-18)

Version:
```
Django               4.1.4
django-oauth-toolkit 2.2.0
oauthlib 3.2.2
```

request in postman:
```
curl --location --request POST 'http://127.0.0.1:8000/o/token/' \
--header 'Authentication: Basic UE80dDI0UlZFd2tFRlBYT2NCVnVHZ0luQ3pNMnppQ21VbnRIQm52ejpBZ2VnR3FXd3prbEdZZTlqeU9ySEFJdXVJeUtzaE1CNmRYb1FkMnQwVTJlcHREblhsWVRrcGdxZTY1OUNCVHFDT0JtZlJyNk1wMExGSFduVWdaYk9oUWNFQWllRnZoNFZybWJNRzk5NXlneFdPVTg3clZOQUJhSWJKbW1BRzUwTg==' \
--header 'Cache-Control: no-cache' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials'
```
response in postman:
- body: `{"error": "invalid_client"}`
- [headers png](https://github.com/swpper/learn-django-oauth-toolkit/blob/main/postman%20response%20headers.png?raw=true)

All code is [here](https://github.com/swpper/learn-django-oauth-toolkit).

**Comment by swpper** [comment]
I turned back to `django-oauth-toolkit==1.7` and it`s ok.

**Comment by n2ygk** [comment]
If your client_secret starts with `pbkdf2_sha256$` that is the hashed version. You need the unhashed version which is only available prior to saving the credential. 

When creating the application you are presented with the system-generated client_secret:

![Screen Shot 2022-12-29 at 8 31 56 AM](https://user-images.githubusercontent.com/4356471/209961350-77fbb02a-d30e-4285-8091-f2bfa59cb410.png)

After `Save`, the client_secret is replaced with the hashed version:

![Screen Shot 2022-12-29 at 8 32 10 AM](https://user-images.githubusercontent.com/4356471/209961380-bcb56fee-a3fd-4e1d-b7b7-cd596c3e4743.png)


This is a new feature documented in the [CHANGELOG](https://github.com/jazzband/django-oauth-toolkit/blob/master/CHANGELOG.md#warning) and made more clear in the admin UI at http://127.0.0.1:8000/admin/oauth2_provider/application/add/ and is yet another place in the documentation and code where we missed documenting this new feature. Sorry!

**Comment by swpper** [comment]
您好，邮件我已收到，我会尽快查收，谢谢!

**Comment by n2ygk** [comment]
However I see that you state that the unhashed secret was saved, so I'm at a loss if that was not the error.

**Comment by n2ygk** [comment]
Please provide the client_id and unhashed secret since when I try to base64 decode `UE80dDI0UlZFd2tFRlBYT2NCVnVHZ0luQ3pNMnppQ21VbnRIQm52ejpBZ2VnR3FXd3prbEdZZTlqeU9ySEFJdXVJeUtzaE1CNmRYb1FkMnQwVTJlcHREblhsWVRrcGdxZTY1OUNCVHFDT0JtZlJyNk1wMExGSFduVWdaYk9oUWNFQWllRnZoNFZybWJNRzk5NXlneFdPVTg3clZOQUJhSWJKbW1BRzUwTg==` I don't see a client_id:client_secret

**Comment by swpper** [comment]
@n2ygk Thanks for your response. The client id, client secret and credential are:
```python
client_id = "PO4t24RVEwkEFPXOcBVuGgInCzM2ziCmUntHBnvz"
client_secret = "AgegGqWwzklGYe9jyOrHAIuuIyKshMB6dXoQd2t0U2eptDnXlYTkpgqe659CBTqCOBmfRr6Mp0LFHWnUgZbOhQcEAieFvh4VrmbMG995ygxWOU87rVNABaIbJmmAG50N"
credential = "UE80dDI0UlZFd2tFRlBYT2NCVnVHZ0luQ3pNMnppQ21VbnRIQm52ejpBZ2VnR3FXd3prbEdZZTlqeU9ySEFJdXVJeUtzaE1CNmRYb1FkMnQwVTJlcHREblhsWVRrcGdxZTY1OUNCVHFDT0JtZlJyNk1wMExGSFduVWdaYk9oUWNFQWllRnZoNFZybWJNRzk5NXlneFdPVTg3clZOQUJhSWJKbW1BRzUwTg=="
```
The credential is generated as said in doc:
```python
def get_credential(client_id, secret):
    credential = "{0}:{1}".format(client_id, secret)
    credential = base64.b64encode(credential.encode("utf-8"))
    return credential.decode('utf-8')
```
The credential is tested in [this file](https://github.com/swpper/learn-django-oauth-toolkit/blob/main/test_token.py)

**Comment by n2ygk** [comment]
Oh! I should have looked more closely at your `settings.py`. PKCE_REQUIRED is a key in the OAUTH2_PROVIDER [settings](https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html):
```
OAUTH2_PROVIDER = {
    'PKCE_REQUIRED': False,
}
```
You have it as a top-level setting:
`PKCE_REQUIRED  = False`

**Comment by swpper** [comment]
Hello, I have received your message in my email and will response quickly, thank you.

**Comment by swpper** [comment]
@n2ygk Wow, it is. This problem troubled me several days and you break it. Thank you very much. ^_^
