### ISSUE TITLE
Duplicate key error: source_refresh_token_id, id_token_id

### ISSUE THREAD

**Issue by sig003** [jazzband/django-oauth-toolkit#1237]
Hello. I have an error. Maybe django-oauth-toolkit's error.   

1. Create a token.   
2. And a re-create a token.    
3. But second token occur a duplicate key error.    

```
pymongo.errors.BulkWriteError: batch op errors occurred, full error: {'writeErrors': [{'index': 0, 'code': 11000, 'keyPattern': {'source_refresh_token_id': 1}, 'keyValue': {'source_refresh_token_id': None}, 'errmsg': 'E11000 duplicate key error collection: test.oauth2_provider_accesstoken index: source_refresh_token_id dup key: { source_refresh_token_id: null }', 'op': {'id': 29, 'user_id': ObjectId('63aa59667ef2477a5517c897'), 'source_refresh_token_id': None, 'token': 'GD8Uq4vupSPV2t0BbZ5D0joTbQrIhH', 'id_token_id': None, 'application_id': 1, 'expires': datetime.datetime(2022, 12, 27, 12, 52, 50, 819549), 'scope': 'read write groups', 'created': datetime.datetime(2022, 12, 27, 2, 52, 50, 820066), 'updated': datetime.datetime(2022, 12, 27, 2, 52, 50, 820081), '_id': ObjectId('63aa5e027ef2477a5517c8ac')}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}
```

Error field is a oauth2_provider_accesstoken.source_refresh_token_id.    

First token: source_refresh_token_id = null 
Second token: source_refresh_token_id = null   
But oauth2_provider_accesstoken has a unique index. It name is a source_refresh_token_id.   
Therefore, a key error occurs when generating the second token.    
And same problem have a oauth2_provider_accesstoken.id_token_id index / oauth2_provider_refreshtoken.access_token_id_1 index.

The solution is to delete the unique index. But I want to avoid deleting.

Is this a bug? Or my mistake? 
And What is a purpose id_token_id field?

Please, help me.

**Comment by JordiNeil** [comment]
Can you please provide more details on how you're creating the tokens? It should create a new token with a new id due to it's a `BigAutoField`

**Comment by sig003** [comment]
> Can you please provide more details on how you're creating the tokens? It should create a new token with a new id due to it's a `BigAutoField`

@JordiNeil 

[oauth2_provider_accesstoken]
- source_refresh_token_id = unique index

When you create a token, the field does not contain a value.
So it becomes a null value.
However, since it is set as a unique index, it goes into null again when generating the next token and causes a duplicate index error.
Failed to generate second token.
Unique index must be uninstalled to resolve the problem.
