### ISSUE TITLE
ROTATE_REFRESH_TOKEN Known Bug

### ISSUE THREAD

**Issue by hamza-sabri** [jazzband/django-oauth-toolkit#1240]
I am working with Django Oauth2 on a freelancing project and used the `username` and `password` to handle authenticate users.

However, when I tried to refresh the access token I noticed that the `refresh_token` itself was revoked, and I found on the documentation that we can use `ROTATE_REFRESH_TOKEN` to disable this behavior.

But, the docs are talking about a known bug that I do not fully understand, why would setting this setting to `False` because the tokens are to be revoked, I debugged the code locally and didn't see anything that would cause this.

I suspect that the docs could be old, and a bit outdated in that regard, but not sure.

<img width="988" alt="image" src="https://user-images.githubusercontent.com/47059736/210347817-bf4c74ed-84b4-4b9b-b7f7-34cb5548174e.png">

Can someone please explain it to me, and if it is safe to use when going into production or not?

**Comment by JordiNeil** [comment]
Hi, I just tested that case and is also working fine for me, if I define `ROTATE_REFRESH_TOKEN` to `False` inside the `OAUTH2_PROVIDER` setting. And the refresh token functionality is reusing the same refresh token, and it works for multiple refreshes. 

Then I would also guess that the documentation is outdated. 
That change was added in [this PR](https://github.com/jazzband/django-oauth-toolkit/pull/749) and exactly [this commit](https://github.com/jazzband/django-oauth-toolkit/pull/749/commits/1de90b1da58369557da5db0f86151f1d97920589). 
The description indicates [this issue](https://github.com/jazzband/django-oauth-toolkit/issues/732) but for me it doesn't seems to be related
