### ISSUE TITLE
Using JWT for access and refresh tokens

### ISSUE THREAD

**Issue by mainakchhari** [jazzband/django-oauth-toolkit#1254]
Many of the standard implementations of OIDC specs use JWT as standard for access and refresh tokens. They also have the benefit of not relying on token persistence (in database) for the token introspection process.
Is there a plan for this feature in any future milestone?

**Comment by mikraus94** [comment]
Any updates?

**Comment by trisduong** [comment]
Any updates?

**Comment by dopry** [comment]
DOT can provide JWTs. You need to enable OIDC, I recommend Authorization Flow + PKCE. The ID token will be  a JWT.  see: https://django-oauth-toolkit.readthedocs.io/en/1.5.0/oidc.html

**Comment by dopry** [comment]
If there is a specific portion of the OAuth or OIDC spec you are referring to, please link it and I check on the state of conformance.

**Comment by kv-42** [comment]
@dopry I think @mainakchhari reffers to OAuth2 Access tokens and Refresh Tokens specifically to be JWT, not the ID token: https://oauth.net/2/jwt-access-tokens/

**Comment by dopry** [comment]
[RFC 9068](https://datatracker.ietf.org/doc/rfc9068/) is a proposed standard. It is isn't final. As far as I know there are no final OAuth 2.0 specs outside of the OIDC umbrella. I wouldn't expect it to be implemented in OAuthLib until the standard is final. IT isn't in the list of [OAuthLib OAuth 2.0 Features and Platforms](https://oauthlib.readthedocs.io/en/latest/feature_matrix.html#oauth-2-0). 

the relevant final OIDC spec which add JWT to the OAuth specification are

see: 
* https://openid.net/specs/openid-connect-core-1_0.html#IDToken
* https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html

**Comment by dopry** [comment]
All that said you can use https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html#access-token-generator per https://oauthlib.readthedocs.io/en/latest/oauth2/tokens/bearer.html to make these tokens JWTs rather than opaque tokens.
