### ISSUE TITLE
What is the point of scopes?

### ISSUE THREAD

**Issue by SinaZK** [jazzband/django-oauth-toolkit#1262]
We can set the scopes in the Django settings. When granting access to each client, all the scopes where given to the client via token. If each client have access to all scopes or none, what is the point of having scopes? I want to have multiple clients, each with different scopes, so i need to set the scopes in the Application model. How can i achieve that?

**Comment by Polaris-d** [comment]
Scopes is the classification and grading of data belonging to the user, and the developer allows the user to decide whether to share it with others. So what data permissions are granted to the client (third party) is determined by the user, and you should remove the data that the user is not allowed to share from scopes.

**Comment by dopry** [comment]
@SinaZK please read https://oauth.net/2/scope/
