### ISSUE TITLE
Using permissions.AllowAny

### ISSUE THREAD

**Issue by Chappie74** [jazzband/django-oauth-toolkit#1265]
For views that are decorated with 
```python
@permission_classes([permissions.AllowAny])
```
if the `Authorization` header is present, with an invalid token it returns 401. It works if no Authorization header is present (expected).

is this the intended behavior?
From my understanding of how things should work, for views that are `AllowAny` the request should still go through, whether or not the authorization is present, or even if its an invalid authorization. I could be wrong, just seeking some advice.

**Comment by ogreyard** [comment]
I'd say it's perfectly correct to neglect an OK 200 response in case of an invalid (try of) authentication, regardless of the resource being protected or not. For me it makes sense as django should be performing authentication first in case it's requested, only afterwards answer the request for the resource.
