### ISSUE TITLE
How to prevent user to request and grant introspection scope?

### ISSUE THREAD

**Issue by zhuang42** [jazzband/django-oauth-toolkit#1297]
As my understanding scopes are optionally passed to authorize endpoint, how to prevent an user granting some specificity scopes and the access token. It seems there is no out of box solution from DOT?

**Comment by Chappie74** [comment]
For that you're going to have to create a custom view that does the token creation and prevent the user from using the `/token` endpoint that comes with this package. From your view you then make an internal request to the token view with the scope you would like.

Here is an example of how I did it. 

![image](https://github.com/jazzband/django-oauth-toolkit/assets/21108487/7a5020ed-fc36-4057-8146-cf5a06baf57d)

**Comment by zhuang42** [comment]
Thank you @Chappie74, it's a good idea. I am thinking to extend the application model and set a list of scopes, which the user can only grant these scopes defined by applications
