### ISSUE TITLE
Error ImportError: No module named signals

### ISSUE THREAD

**Issue by gabrielasan20117** [jazzband/django-oauth-toolkit#1303]
Hello. I haver error with this, i not allow import the library. 
I use this versions:

- oauthlib==2.1.0
- django-oauth-toolkit==1.0.0
- django-cors-middleware==1.3.1

```
from oauth2_provider.signals import app_authorized
ImportError: No module named signals
```

**Comment by n2ygk** [comment]
Release 1.0.0 is very out of date and likely references stuff that no longer exists. The [current release](https://pypi.org/project/django-oauth-toolkit/) is 2.3.0
