### ISSUE TITLE
post_logout_redirect_uris introduces breaking change

### ISSUE THREAD

**Issue by magicbrothers** [jazzband/django-oauth-toolkit#1309]
In [this commit](https://github.com/jazzband/django-oauth-toolkit/commit/11294ab5678691fb6bc21ecf917dca3099311a9e#diff-1ebdc91fdacce3c6c243c059421477ecd84b80bbc0381a1d21b424a66135241fR109) the non-nullable field `post_logout_redirect_uris` is introduced without a default value.
This is a breaking change.

There are two options to fix this problem:
1. Make the field nullable (`null=True`)
2. Set a default value (e.g. `default=""`)

- [x] I have tested with the latest published release and it's still a problem.
- [x] I have tested with the master branch and it's still a problem.

**Comment by n2ygk** [comment]
@Qup42 @dopry please take a look at this and submit a PR to make the field nullable with a default.
