### ISSUE TITLE
Outdated RFC link in README.rst and elsewhere

### ISSUE THREAD

**Issue by jennifer-richards** [jazzband/django-oauth-toolkit#1313]
**Describe the bug**
The `README.rst` and other files contain an outdated link to RFC 6749.

**To Reproduce**
Visit the github page and note that the URL for the statement about being rfc-compliant leads to a URL at `tools.ietf.org`, a now deprecated domain. Search the source code and find other mentions of `tools.ietf.org`.

**Expected behavior**
The link should point to the current location of the resource, https://www.rfc-editor.org/info/rfc6749 (for the info page with various formats and metadata about the RFC) or https://www.rfc-editor.org/rfc/rfc6749.html (for a direct link to the HTML version).

**Version**
current main branch

- [x] I have tested with the latest published release and it's still a problem.
- [x] I have tested with the master branch and it's still a problem.

**Additional context**
The `tools.ietf.org` site has been retired / deprecated and, while it redirects to a working location, should no longer be used.

**Comment by n2ygk** [comment]
A PR to fix this would be appreciated!
