### ISSUE TITLE
Unable to parse query string

### ISSUE THREAD

**Issue by codewriter3000** [jazzband/django-oauth-toolkit#1326]
**Describe the bug**

When I try to authorize, I get an error that says "Error; invalid request, unable to parse query string"
**To Reproduce**

1. Register an application as such:
![image](https://github.com/jazzband/django-oauth-toolkit/assets/58712923/c5be8afa-4350-470d-b09f-b86e429739f6)
2. Create a code_challenge as such:
```py
import random
import string
import base64
import hashlib

code_verifier = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(random.randint(43, 128)))
code_verifier = base64.urlsafe_b64encode(code_verifier.encode('utf-8'))

code_challenge = hashlib.sha256(code_verifier).digest()
code_challenge = base64.urlsafe_b64encode(code_challenge).decode('utf-8').replace('=', '')

print(fr'code verifier: {code_verifier}')
print(fr'code challenger: {code_challenge}')
```
3. Go to: http://127.0.0.1:8000/o/authorize/?response_type-code&code_challenge=YO1xUfYUKR6PCM5m3r-IjQWJKbhQ8YgMls8gigtnVxc&code_challenge_method=5256&client_id=2edYoWkN7DBj6uREFbvjnbJLrN3Hzr64G7dxH0wL&redirect_uri=http://127.0.0.1:8000/noexist/callback and set the proper parameters.
**Expected behavior**

I'm expecting to not see an error.
**Version**

2.3.0

- [X] I have tested with the latest published release and it's still a problem.
- [ ] I have tested with the master branch and it's still a problem.

**Additional context**

**Comment by dopry** [comment]
It looks like `response_type-code` should be `response_type=code`, please re-open if that doesn't resolve your isssue.

**Comment by codewriter3000** [comment]
The error is now `Mismatching redirect URI`
