### ISSUE TITLE
Refresh ID token alognside with Access Token

### ISSUE THREAD

**Issue by kv-42** [jazzband/django-oauth-toolkit#1339]
How to refresh the ID token having OAuth2 Refresh Token and avoid repeating Auth flow again? AFAIK current behaviour is to refresh OAuth2 Access Token only

**Comment by dopry** [comment]
You call the token endpoint using the refresh token in the Authorization header. 

see: https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_01.html#refresh-the-token
