### ISSUE TITLE
What is the release cadence?

### ISSUE THREAD

**Issue by LiamClarkeNZ** [jazzband/django-oauth-toolkit#1391]
Kia ora, there's some changes around JWT that are merged to main but not yet released that I'm interested in, but have no milestone attached it. I'm wondering how often this project releases, and if you know when the next one might be?

I'm happy to help out if there's any additional contributions needed to consider a new release (enlightened self-interest :D) 

Cheers!

**Comment by renarsvilnis** [comment]
➕ We depend now on a significant cache improvement regarding the fix on #1273 that has been merged in over a year ago

**Comment by n2ygk** [comment]
The release cadence is not great. More volunteers needed!
