### ISSUE TITLE
{ "error": "invalid_grant",     "error_description": "Invalid credentials given." }

### ISSUE THREAD

**Issue by Birddle** [jazzband/django-oauth-toolkit#1393]
I following this:https://github.com/jazzband/django-oauth-toolkit/blob/master/docs/getting_started.rst
I have a very confusing problem.
I am able to log in through a `python manage.py createsuper` created superuser, but not through a user created from the dashboard, even though the superuser option is checked. and i will got
```
Bad Request: /o/token/
[31/Jan/2024 03:33:31] "POST /o/token/ HTTP/1.1" 400 77
```
Am I overlooking something?
<img width="1455" alt="image" src="https://github.com/jazzband/django-oauth-toolkit/assets/86408260/74e98c98-35ba-4df1-8b00-c1950ee17ed0">
<img width="909" alt="image" src="https://github.com/jazzband/django-oauth-toolkit/assets/86408260/590aa8cd-b07d-409a-848e-6b47e480f276">
<img width="1132" alt="image" src="https://github.com/jazzband/django-oauth-toolkit/assets/86408260/045cb8cf-cf51-4374-88b0-8f0a3080eb3b">

<img width="894" alt="image" src="https://github.com/jazzband/django-oauth-toolkit/assets/86408260/7daf7587-923e-47b3-97f6-d96fda9f389f">

**Comment by ianmubangizi** [comment]
@Birddle is the Model username field the email?

The default validator uses the Model field username if am correct as seen here.
```python
class OAuth2Validator(RequestValidator):
    ...
    def validate_user(self, username, password, client, request, *args, **kwargs):
        """
        Check username and password correspond to a valid and active User
        """
        # Passing the optional HttpRequest adds compatibility for backends
        # which depend on its presence. Create one with attributes likely
        # to be used.
        http_request = HttpRequest()
        http_request.path = request.uri
        http_request.method = request.http_method
        getattr(http_request, request.http_method).update(dict(request.decoded_body))
        http_request.META = request.headers
        u = authenticate(http_request, username=username, password=password)
        if u is not None and u.is_active:
            request.user = u
            return True
        return False
```
