### ISSUE TITLE
Suitability for LTI 1.3

### ISSUE THREAD

**Issue by danielmcquillen** [jazzband/django-oauth-toolkit#1417]
Hi django-oauth-toolkit community.

I want to implement a very simple [LTI v1.3 ](https://www.imsglobal.org/spec/lti/v1p3) platform within an existing Django app, to support launching external tools like JupyterHub notebooks. (This article has a nice illustration of the LTI1.3 OIDC flow...https://medium.com/voxy-engineering/introduction-to-lti-1-3-270f17505d75)

A bit of a stretch for me as I grok the basic OIDC-based workflow, but get a bit lost when I go down a layer. So to avoid spending too much time in the wrong place, wondering if anyone can comment on whether django-oauth-toolkit is an appropriate library to build such a thing on? There are a bunch of LTI v1.3 **tool** libraries out there, but nothing really focused on the **platform**.

Apologies if this note should appear in a forum somewhere external...if so please advice and I'll close this issue.

**Comment by n2ygk** [comment]
Good to see that LTI as of v1.3 is (finally) moving away from OAuth 1.0 to OAuth 2.0. These are [very different protocols](https://www.oauth.com/oauth2-servers/differences-between-oauth-1-2/).

DOT is definitely a good library for OAuth 2.0 and OIDC. See https://django-oauth-toolkit.readthedocs.io/en/latest/oidc.html
