### ISSUE TITLE
add docs: how to customize oauth2 validator

### ISSUE THREAD

**Issue by synasius** [jazzband/django-oauth-toolkit#232]

**Comment by pythonwood** [comment]
how to customize oauth2 validator? 
that is important.

**Comment by mmohajer9** [comment]
> how to customize oauth2 validator?
> that is important.

you can do this by over riding OAUTH2_VALIDATOR_CLASS method called validate_user
see my code to understand
i implemented a simple authentication without giving username and password and just by sending sms


`from oauth2_provider.oauth2_validators import OAuth2Validator
from django.contrib.auth import get_user_model , authenticate
class MyOAuth2Validator(OAuth2Validator):
    """ Primarily extend the functionality of token generation """
    def validate_user(self, username, password, client, request, *args, **kwargs):
        """
        Check username and password correspond to a valid and active User
        """
        u = authenticate(username=username, password=password)
        if u is not None and u.is_active:
            request.user = u
            return True
        return False
`

**Comment by mmohajer9** [comment]
from oauth2_provider.oauth2_validators import OAuth2Validator

    from django.contrib.auth import get_user_model

    USER_MODEL = get_user_model()


    class MyOAuth2Validator(OAuth2Validator):  # pylint: disable=w0223
        """ Primarily extend the functionality of token generation """

        def validate_user(self, username, password, client, request, *args, **kwargs):
            """ Here, you would be able to access the MOBILE/ OTP fields 
                which you will be sending in the request.post body. """
            # otp = request.otp
            # mobile = request.mobile
            # user = AppropriateModel.objects.get(otp=otp, mobile=mobile)
            user = USER_MODEL.objects.get(id=1)
            if user is not None and user.is_active:
                request.user = user
                return True
            return False

**Comment by n2ygk** [comment]
Looks like this is answered. Closing.
