### ISSUE TITLE
CORS-protection middleware

### ISSUE THREAD

**Issue by cheif** [jazzband/django-oauth-toolkit#287]
We're currently facing some issues whet we're about to expose our API to external users, namely CORS-protection together with OAuth2.

The go-to package for cors-headers, [django-cors-headers](https://github.com/ottoyiu/django-cors-headers/) works fine when only having a small number of internal applications, but the white/blacklist approach is somewhat limited when dealing with public API:s.

The solution we're going to go with is to generate CORS-headers based on the OAuth2-application for the request (if it's present, ofc), which gives a more scalable approach.

My question is basically if others would be interested in this and if i should add this middleware to django-oauth-toolkit instead of keeping it in our own repository?

**Comment by jlafon** [comment]
I would like to see this in DOT, as we have also used the approach of generating CORS headers based on the application.

**Comment by MBuffenoir** [comment]
Cheif I would gladly give it a try too ...

**Comment by masci** [comment]
:+1:  for this

**Comment by cheif** [comment]
Started working on this here: https://github.com/cheif/django-oauth-toolkit/tree/cors-header-middleware
It's basically a port of the implementation we have right now, there's some more things need though, e.g. letting headers and methods be configured in settings instead of hardcoded.

**Comment by MattBlack85** [comment]
no interest apparently from latest comment on #300
