### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by gabn88** [jazzband/django-oauth-toolkit#318]
I have an existing API (DRF) that uses, 1. JWT, 2. 'normal' tokens, 3. Sessions to gather the date from the API. I have permissions and filters in place, so that users can see,write, change, delete only the stuff that they should be allowed to do.

Now I have created an app and used Oauth to log the user in. I did not pose any allowances on my API, but still the user is permitted all the actions that he could with a JWT, 'normal' token or Session!! This means that any other app the subscribes himself via de o/applications can BY DEFAULT do all this stuff (of course when the user allows him). 

This sounds like a crazy security issue, since any existing user can create an app and show the login form. I had more imagined it to be like, by default no permissions, only when you allow a certain app permissions the app has permission.

~~Also I have done the tutorial using DRF (using cUrl). The application that the user granted access also had access to ALL api endpoints and ALL actions are permitted by default. I really find this strange security policy and do not think this is a sensible default. Also it seems that the application can defined whatever scopes he likes to grant the user permission, but it can also be that I don't understand this part well enough.~~

Also I would like to know if it is possible to change this setting system wide? So that an application has access to only API endpoints with explicitly defined scopes?

**Comment by poswald** [comment]
Can you please give some more description of your setup and what you did (which grant type you're using, etc..)? Are you saying you expected a user who is authenticated to have different permissions when authenticated through the API, or if you're saying that you expected the application endpoints not to be available to them?

**Comment by cleder** [comment]
Also you should report security issues via an email directly to the author, not in the issue tracker!

**Comment by gabn88** [comment]
## What I wanted it to be
A Facebook like Oauth system, where an application has to be given permissions by some kind of system superuser. A users that use the application for example get a message "Do you want to grant application XYZ to have permission to:  a. write on your wall, b. see your personal information, c. create new subaccounts, etc..." and the application only gets access/permissions to do that via the endpoints that are especially tagged with a certain scope.

## How it worked for me when I installed it
For me it worked like an Oauth system, where people themselves can create applications (without su control, although this should be not to difficult to implement, but I think it would be nice to have in the core). And when an application is given access by a certain user, this application has all the rights the user has. 

It could be that I was doing something wrong, but I found this to be very suspicious behaviour with regards to security. So much that I ended up not implementing it (yet).

**Comment by palazzem** [comment]
Hello everyone!
I just want to inform all participants of this discussion (as stated by @cleder ) that when someone finds an issue with possible security implications, it's better to send us a direct email to ``security@evonove.it``. We prefer that you send us an e-mail even if you're not sure that the issue is a real threat. I've also added a reference in the README[1].

Anyway, thank you guys for your time on reporting these important issues!

[1]: https://github.com/evonove/django-oauth-toolkit#reporting-security-issues

**Comment by JensTimmerman** [comment]
@gabn88 I'm also looking for the behaviour you want, and it seems so do others.
I've created a pull request based on code by @honestbleeps to allow an admin to set specific scopes an application is allowed to request.
see #395 
Of course you would then not have to allow arbitrary users to create an application  (or set the default scopes to be very limited, and then you can manually add more scopes to applications you trust.)
