### ISSUE TITLE
Change Application's user without using settings.AUTH_USER_MODEL

### ISSUE THREAD

**Issue by esseti** [jazzband/django-oauth-toolkit#462]
Hi all,
In my code I've to change the oauth toolkit in such a way that the user (owner) of the app is my class `User`. 
Yet, in the `settings.AUTH_USER_MODEL` I cannot set this class, I rather have `CustomerUser`.

Now, how can I achieve that?

So far I ended up by *copying* the code of the app and made the change hardcoded. The problem *that I just figured out* is that the update of the code breaks my edits and the whole system (in this specific case my app did not have `is_usable`).

I tried to extend Application setting `user` as my class, but django complains about that.

any suggestion or tip?

**Comment by jleclanche** [comment]
This is now possible with the custom application model.
