### ISSUE TITLE
No module named defaults

### ISSUE THREAD

**Issue by Zorig** [jazzband/django-oauth-toolkit#495]
Error on Django 1.11.3 django-oauth-toolkit 1.0
```from django.conf.urls.defaults import patterns, url, include
ImportError: No module named defaults
```
PS:// defaults removed from Django since 1.6

**Comment by jleclanche** [comment]
Do you have a full stacktrace? We don't import "defaults" anywhere

**Comment by Zorig** [comment]
i installed `django-oauth-toolkit==1.0` on `django 1.11.3` and put `oauth2_provider` in settings.py also url config too, then trying to runserver gives me an error above
