### ISSUE TITLE
Specific scopes for different methods (CBV)

### ISSUE THREAD

**Issue by khorolets** [jazzband/django-oauth-toolkit#502]
Hi! Thanks for your great work. I have a question that I couldn't find the answer for, neither in the docs nor in the issues.

If I need to have different scopes for different methods in my CBV is there any builtin way to achieve it.

For example:

```python
class Endpoint(GenericAPIView):
    permission_classes = (TokenHasScope,)
    required_scopes = ['read']

    def get(self, *args, **kwargs):
        # Everything is ok here, I'm fine with `read` scope only
        pass

    def patch(self, *args, **kwargs):
        # But I need `write` scope here
        pass
```

Can I handle it with DOT now? Thanks in advance!

**Comment by sahama** [comment]
Your answer may be at https://stackoverflow.com/a/47308608/6876911
