### ISSUE TITLE
Please update the docs

### ISSUE THREAD

**Issue by musemby** [jazzband/django-oauth-toolkit#506]
The docs especially at https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html are out of date. For instance the the import for `OAuth2Authentication`  is documented as `oauth2_provider.ext.rest_framework.OAuth2Authentication` yet as of v1.0.0 it's `oauth2_provider.contrib.rest_framework`

The docs are already updated in code but the update has not yet been deployed to read the docs. It can be pretty frustrating for first time users to figure this out. The copyright even reads `© Copyright 2013`.

**Comment by fbidu** [comment]
I second that. 

A few days ago I was updating a toolkit's installation in an old project and ran into this problem. I considered fixing the docs but found out that it was already fixed on GitHub. It would be really nice to update the docs ASAP.

**Comment by jieter** [comment]
@jleclanche seems easy to fix, maybe just a build error in readthedocs?

**Comment by jleclanche** [comment]
I don't have access to rtd.

**Comment by jieter** [comment]
OK, who does?

There seems to be a notion of version 1.0.0 at http://django-oauth-toolkit.readthedocs.io/en/1.0.0/, but it only shows an error message stating it doesn't exist.

**Comment by jleclanche** [comment]
@synasius ping

**Comment by musemby** [comment]
I have compiled the latest docs: http://django-oauth-toolkit-latest.readthedocs.io/en/latest/index.html for anyone that might find themselves in this situation. I will try keep it as up to date as possible. @jleclanche I propose we link to it on the README for now

**Comment by alexm** [comment]
@musemby could you please make a pull request with the changes needed for the rtd build to work?

Thus, maybe it'll be easier for @synasius to review and fix this issue.

Thanks both in advance!

**Comment by jleclanche** [comment]
Closing for #553

**Comment by jleclanche** [comment]
Wrong issue, didn't mean to close. I'm working with @synasius to get the repository transferred to an org that can take better care of it, stay tuned :)

**Comment by camilonova** [comment]
@jleclanche there was something not working here at jazzband ? Let me know how I can help.

**Comment by jleclanche** [comment]
I don't know what the state of this is now that it's been transferred. I think it's fixed?

**Comment by camilonova** [comment]
Looks like it was already fixed. I'm closing this.

**Comment by n2ygk** [comment]
@musemby I am trying to get the RTD docs integration/webhook fixed (again) for this project as part of a new release [1.3](#801).  I see that you created https://readthedocs.org/projects/django-oauth-toolkit-latest/. Would you be so kind as to delete it as the official RTD for the project is https://readthedocs.org/projects/django-oauth-toolkit/ -- without the `-latest` on the end.

**Comment by musemby** [comment]
I have deleted the `-latest` RTD @n2ygk

**Comment by n2ygk** [comment]
Thanks!
