### ISSUE TITLE
revoke_token deletes both the access token and the refresh token from the database

### ISSUE THREAD

**Issue by synic** [jazzband/django-oauth-toolkit#507]
Versions:

```
django-oauth-toolkit==0.8.1
oauth2client==1.4.11
oauthlib==0.7.2
```

Posting data to `/oauth/revoke_token` causes both the access token and the refresh token to be deleted from the database.

How do we only revoke the access token?

We are passing the access token as the `token` field, and `access_token` as `token_type_hint`

```
(lldb) po request.parameters
▿ Optional<Dictionary<String, HTTPQueryParameter>>
  ▿ some : 4 elements
    ▿ 0 : 2 elements
      - key : "client_secret"
      ▿ value : HTTPQueryParameter
        - stringParameter : "client secret"
    ▿ 1 : 2 elements
      - key : "token_type_hint"
      ▿ value : HTTPQueryParameter
        - stringParameter : "access_token"
    ▿ 2 : 2 elements
      - key : "token"
      ▿ value : HTTPQueryParameter
        - stringParameter : "token"
    ▿ 3 : 2 elements
      - key : "client_id"
      ▿ value : HTTPQueryParameter
        - stringParameter : "client_id"


(lldb) po request.HTTPHeaderFields
▿ Optional<Dictionary<String, String>>
  ▿ some : 1 element
    ▿ 0 : 2 elements
      - key : "Content-Type"
      - value : "application/x-www-form-urlencoded"

```

**Comment by jleclanche** [comment]
Part of the issue is that the refresh token is a one-to-one to the access token. But I'm not actually sure it's a good idea not to clear both when revoking the one.

**Comment by synic** [comment]
Consider the following: we have a client that requires that each access token is revoked when the application closes (not logs out), and then when they relaunch the app, they want the refresh token to be used to get a new access token.  This way, the access token is only ever usable when the application is active, and cannot be used after for any reason.

I guess I see three options here:

1.  Have a way to only revoke the access token.
2.  Create a new endpoint that will set the access token's `expires` field to the current time.
3.  When the application is closed, use the refresh token to obtain new access token/refresh token.  It's possible that the access token expires before it's ever used, but in this way, a token is never alive longer than it needs to be.

What do you think?

**Comment by menecio** [comment]
You can easily write your own `RefreshToken` model and change:
```python
access_token = models.OneToOneField(
        oauth2_settings.ACCESS_TOKEN_MODEL, on_delete=models.CASCADE,
        related_name="refresh_token"
    )
```

to 

```python
access_token = models.OneToOneField(
        oauth2_settings.ACCESS_TOKEN_MODEL, on_delete=models.SET_NULL,
        related_name="refresh_token"
    )
```

and then set `OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = 'yourapp.RefreshToken'`

**Comment by rooftopcellist** [comment]
@synic FYI: In DOT 1.1.0, this happens by default.  https://github.com/jazzband/django-oauth-toolkit/blob/1.1.0/oauth2_provider/models.py#L350

This issue can probably be closed now.
