### ISSUE TITLE
Add Documentation on how to customize tokens and grant models.

### ISSUE THREAD

**Issue by Agilulfo** [jazzband/django-oauth-toolkit#525]
In the Advanced section of the documentation there are no instructions on how to associate custom informations to tokens.

For what I understood this can be achieved customizing at least grant and token models.
Customizing these models should be simple as customizing the Application model..
However I'm having several issues with generating and applying migrations.

For instance If I subclass AbstractGrant and the I try to generate migrations without this into settings
`OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'`
then I get the following error:
```
AttributeError: 'Settings' object has no attribute 'OAUTH2_PROVIDER_APPLICATION_MODEL'
Makefile:115: recipe for target 'makemigrations' failed
make: *** [makemigrations] Error 1
```

If I define the OAUTH2_PROVIDER_APPLICATION_MODEL a migration will be generated.
Once I apply the new migration and I add 
`OAUTH2_PROVIDER_GRANT_MODEL = 'oauth.MyGrant'`
as soon as I regenerate the migrations I get 
```
django.db.migrations.exceptions.CircularDependencyError: oauth2_provider.0001_initial, oauth.0001_initial
Makefile:115: recipe for target 'makemigrations' failed
make: *** [makemigrations] Error 1
```
Having basic instruction on how to proceed would be really appreciated.

**Comment by MattBlack85** [comment]
After further investigation it seems wrong to me that the initial migration has dependencies to:
 - oauth2_settings.APPLICATION_MODEL
 - oauth2_settings.ACCESS_TOKEN_MODEL
 - oauth2_settings.REFRESH_TOKEN_MODEL
 - oauth2_settings.GRANT_MODEL

This way whatever subclass of one of this models lead to a circular dependency since for example the `Grant` model has a FK to the `Application` model  so `Application` must be created first and the `Grant`, but since `Grant` depends on `Application` and `Application` depends on grant we are not able to use a custom model

**Comment by MattBlack85** [comment]
@jleclanche can we have an input on this please? We need to implement this thing very soon and we don't know if we have to fork the repo and go with the workaround or dig more into what we're doing wrong 🙏

**Comment by jleclanche** [comment]
@MattBlack85 Have you tried adding the dependencies to the migrations? If it works feel free to PR

**Comment by MattBlack85** [comment]
@jleclanche those dependencies are already in the migrations, the only way it works for us is removing them

**Comment by jleclanche** [comment]
Sorry, I read your post the wrong way around. To be honest with you migration dependencies for abstract models are arcane to me, so I can't tell you what the correct way is... but if you can showcase what it is, I'll merge it.

Why they were added later: I believe there is a closed issue about the Application model's migration dependency. The other models were made abstract only recently.

**Comment by MattBlack85** [comment]
yeah those arcane to me too, giving also the swappable machinery is a private undocumented API doesn't help much. Will open soon a PR with all our findings

**Comment by jdelic** [comment]
@MattBlack85 just to make sure... did you try adding a `run_before` stanza to your own initial migration? [Here is an example from my own `authserver` project](https://github.com/jdelic/authserver/blob/c48037a283d7202b830f83559b0bcbc70fd42156/authserver/mailauth/migrations/0001_initial.py#L22-L24)

**Comment by jdelic** [comment]
I just realized the PR was already merged and the issue never closed. Nevermind, sorry for the spam.
