### ISSUE TITLE
there is no any requirements/optional.txt in repo

### ISSUE THREAD

**Issue by sohamnavadiya** [jazzband/django-oauth-toolkit#535]
Not able to execute pip install -r requirements/optional.txt

**Comment by musemby** [comment]
Sorry about that, outdated docs. Run `tox` instead to install requirements.

**Comment by philratcliffe** [comment]
The requirements files, which included requirements/optional.txt, were deleted on 9th March 2017 when test requirements were moved to tox.ini. The [document file](https://github.com/jazzband/django-oauth-toolkit/blob/master/docs/contributing.rst) has now been updated to remove the incorrect reference requirements/optional.txt - please see PR #578.
