### ISSUE TITLE
Mgmt command to clear expired access tokens without refresh tokens

### ISSUE THREAD

**Issue by mhindery** [jazzband/django-oauth-toolkit#540]
We're using oauth with the client-credentials flow. In this flow, access tokens are created but no refresh tokens. Consequentially, there's no mgmt command provided to clean up expired access tokens, as the current command only looks at refresh tokens. Can the command be extended to delete these expired tokens (if deemed useful, I can have a look at it and submit a PR), or in a separate command?

**Comment by MattBlack85** [comment]
@mhindery if you still need such a feature, send a PR over :)
