### ISSUE TITLE
master branch not being updated on rtd.io

### ISSUE THREAD

**Issue by nhuzaa** [jazzband/django-oauth-toolkit#550]
I was using Authentication class as
`oauth2_provider.ext.rest_framework.OAuth2Authentication`
But i seems that its changed to 
`oauth2_provider.contrib.rest_framework.OAuth2Authentication`

Docs has been updated on the master however 
http://django-oauth-toolkit.readthedocs.io/en/stable/rest-framework/getting_started.html
Shows the old Getting Started page
https://github.com/evonove/django-oauth-toolkit/blob/34f3b7b3511c15686039079026165feaadb1b87d/docs/rest-framework/getting_started.rst

**Comment by n2ygk** [comment]
Somehow there's also a http://django-oauth-toolkit-latest.readthedocs.io/ (note the **-latest**) which has github references to one of the [forks](https://github.com/musemby/django-oauth-toolkit) rather than this main repo (see https://github.com/evonove/django-oauth-toolkit/issues/520). This messed me up too!

**Comment by n2ygk** [comment]
@MattBlack85 it appears that you are the only jazzband lead for this project. Can you take a look and/or add more lead(s) like perhaps @jleclanche (and I volunteer if someone can guide me to make sure I don't screw up). I suspect there may be an old [deprecated github services integration](https://developer.github.com/changes/2018-04-25-github-services-deprecation/) for RTD in project settings which needs to be replaced with a webhook: The [last RTD build](https://readthedocs.org/projects/django-oauth-toolkit/builds/8227869/) was Dec. 8, 2018. 4:51 a.m.

**Comment by jleclanche** [comment]
Feel free to add @n2ygk, I'd rather not be a lead right now as I'm too short on time to dedicate to this :)

**Comment by auvipy** [comment]
you can also add me :)

**Comment by n2ygk** [comment]
Adding this back to 1.3 milestone.

I would appreciate your help with getting the RTD stuff back working:

- [ ] @synasius @masci @jazzband-bot you are the [RTD project owners](https://readthedocs.org/projects/django-oauth-toolkit/)

- [ ] @MattBlack85 you are listed as the sole project lead on https://jazzband.co/projects/django-oauth-toolkit.

- [ ] @jleclanche I am unable to tell who has project settings access. Is it only @MattBlack85 and @jezdez?

I've had difficulty getting a response from @jezdez -- I'm guessing he's super busy. (I hope it's just that he's busy or on vacation!)

**Comment by n2ygk** [comment]
> Adding this back to 1.3 milestone.
> 
> I would appreciate your help with getting the RTD stuff back working:
> 
> * [ ]  @synasius @masci @jazzband-bot you are the [RTD project owners](https://readthedocs.org/projects/django-oauth-toolkit/)
> * [ ]  @MattBlack85 you are listed as the sole project lead on https://jazzband.co/projects/django-oauth-toolkit.
> * [ ]  @jleclanche I am unable to tell who has project settings access. Is it only @MattBlack85 and @jezdez?
> 
> I've had difficulty getting a response from @jezdez -- I'm guessing he's super busy. (I hope it's just that he's busy or on vacation!)

Never mind. I've just heard from @jezdez. He was in fact unavailable for a few days.

**Comment by synasius** [comment]
@n2ygk I can add you on RTD? What is your username?

**Comment by jleclanche** [comment]
@n2ygk I don't have settings access indeed.

**Comment by n2ygk** [comment]
> @n2ygk I can add you on RTD? What is your username?

n2ygk

Thanks!

**Comment by synasius** [comment]
@n2ygk Done!

> Thanks @synasius

You're welcome!

Thanks to everyone who has contributed to keep this project alive! :pray: :heart:

**Comment by n2ygk** [comment]
@jleclanche @auvipy opinion on whether we should configure automatic build of readthedocs on every pull request? We already test build in tox.ini so errors will show up there.

See https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html#
