### ISSUE TITLE
apps aren't loaded yet

### ISSUE THREAD

**Issue by amirRamirfatahi** [jazzband/django-oauth-toolkit#559]
I use python3.5 and django2
I'm following your documentation.
After the start your app part of tutorial 1, when I try to python manage.py migrate I get
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
help me please

**Comment by MedvedevSergey** [comment]
I have the same problem

**Comment by camilonova** [comment]
Surely this is a problem on your local project.
