### ISSUE TITLE
django-oauth-toolkit 'invalid client' error after deploy on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by kras55** [jazzband/django-oauth-toolkit#560]
I use django-oauth-toolkit with my django/django-rest-framework application. When I request an access token in dev mode on localhost, it works OK:

`dev@devComp:$ curl -X POST -d "grant_type=password&username=
<user_name>&password=<password>" -u"<client_id>:<client_secret>"  http://localhost:8000/o/token/`
`{"access_token": "fFySxhVjOroIJkD0IuEXr5WIhwdXg6", "expires_in": 
36000, "token_type": "Bearer", "scope": "read write groups", 
"refresh_token": "14vhyaCZbdLtu7sq8gTcFpm3ro9YxH"}`

But if I request an access token from absolutely the same application deployed at AWS Elastic Beanstalk, I get 'invalid client' error:

`dev@devComp:$ curl -X POST -d "grant_type=password&username=
<user_name>&password=<password>" -u"<client_id>:<client_secret>" 
http://my-eb-prefix.us-west-1.elasticbeanstalk.com/o/token/`
`{"error": "invalid_client"}`

Please advise me what to do to get rid of this error and normally request access tokens from django app deployed at AWS.

**Comment by PhilippeTrounev** [comment]
Same issue here. Works on localhost but get invalid client on elastic beanstalk. Works on Heroku thou...

**Comment by jleclanche** [comment]
Closing old unanswered question.
