### ISSUE TITLE
Add PKCE Support

### ISSUE THREAD

**Issue by jfilter** [jazzband/django-oauth-toolkit#566]
PKCE: Proof Key for Code Exchange (https://oauth.net/2/pkce/)

> PKCE is a technique to secure public clients that don't use a client secret.

PKCE is useful for e.g. mobile apps because the client secret cannot be stored on the device.

**Comment by Abhishek8394** [comment]
Is the project open to accepting pull requests on this issue? I will be working on this anyway, might as well have it available for everyone.

**Comment by JonathanHuot** [comment]
This issue can be closed since https://github.com/jazzband/django-oauth-toolkit/pull/678 has been merged. However, no new release has been published since the  merge.

Also https://github.com/jazzband/django-oauth-toolkit/pull/707 is currently open & investigating.

**Comment by Chitrank-Dixit** [comment]
Hi everyone,

Do anyone write any documentation on PKCE implementation flow. I am using the following flow 

```
import os

import requests
from hashlib import sha256
import base64
from urllib.parse import urlencode
from django.test import TestCase

client_id = '*******'
client_secret = '********'
redirect_uri = 'https://6c5b3b6c.ngrok.io/misc/hello/'

def base64URLEncode(random_bytes):
    return base64.urlsafe_b64encode(random_bytes)

def usha256(buffer):
    return sha256(buffer).digest()

secret_data = b'cr7'
random_chars = os.urandom(32)
verifier = base64URLEncode(secret_data).rstrip(b'=')
code_challenge = base64URLEncode(usha256(verifier)).rstrip(b'=')
code_challenge_method = "S256"
scope = 'openid'
params = {
    'client_id': client_id,
    'redirect_uri': redirect_uri,
    'response_type': 'code',
    #'scope': scope,
    'code_challenge': code_challenge,
    'code_challenge_method': code_challenge_method
}
qstr = urlencode(params)
print('https://6c5b3b6c.ngrok.io/o/authorize/?' + qstr)
code = input('enter code obtained: ')

authorization_url = oauth_resp.url
headers = {'Content-type': 'application/x-www-form-urlencoded'}
token_url = 'https://6c5b3b6c.ngrok.io/o/token/'
data = {
    'code': code,
    'client_id': client_id,
    'client_secret': client_secret,
    'redirect_uri': redirect_uri,
    'grant_type': 'authorization_code',
    'code_verifier': verifier
}
token_resp = requests.post(token_url, data=data, headers=headers)
print(token_resp)
```

If I am not sending the code_verifier in the second call it still gets the access_token and other data. I need to restrict it , that if code verifier is not found or found wrong it should give an error. So I read somewhere and added this in my django app's settings.

```
OAUTH2_PROVIDER = {
    "PKCE_REQUIRED": True
}
```
But It has also not done the work correctly, can anyone help me to use PKCE flow with django-oauth-toolkit ?

**Comment by knowmelife** [comment]
@Chitrank-Dixit
You should just add 'PKCE_REQUIRED = True ' to your settings. Do not wrap it in a dictionary for OAUTH2_PROVIDER.

Source - https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html

I know this question is old, but let me know if you got it working!
