### ISSUE TITLE
Error refreshing token with custom RefreshToken model

### ISSUE THREAD

**Issue by szicari-farmobile** [jazzband/django-oauth-toolkit#571]
Attempting to obtain a new access token using a refresh token results in the following error:

```
relation "oauth2_provider_refreshtoken" does not exist
LINE 1: DELETE FROM "oauth2_provider_refreshtoken" WHERE "oauth2_pro...
                    ^
```

I'm not sure what the problem is. My understanding is Django's "swappable" feature is supposed to use the custom model when defined, but that's not happening.

My code base has custom `Application`, `Access Token`, `Refresh Token`, and `Grant` models defined. We did this because we are not able to use Django to manage our database, so we needed to override the default table names. The implementation is at the bottom.

Access tokens are able to be granted and verified correctly. Digging in a bit, I see that the oAuth toolkit code has a reference to its own model (`oauth2_provider.models.RefreshToken`) at the time the above error is generated.

We are configuring the oAuth toolkit as follows (our custom models are located in a Python package called `fm-django-auth`):

```python
OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
    },
    'APPLICATION_MODEL': 'fm_django_auth.Oauth2Application',
    'ACCESS_TOKEN_MODEL': 'fm_django_auth.Oauth2AccessToken',
    'REFRESH_TOKEN_MODEL': 'fm_django_auth.Oauth2RefreshToken',
    'GRANT_MODEL': 'fm_django_auth.Oauth2Grant',
}
```

Finally, our custom models:

```python
from django.db import models
from oauth2_provider.models import (
    AbstractApplication,
    AbstractAccessToken,
    AbstractRefreshToken,
    AbstractGrant
)

class Oauth2Application(AbstractApplication):
    
    class Meta:
        db_table = 'oauth2"."application'
        managed = False


class Oauth2AccessToken(AbstractAccessToken):

    class Meta:
        db_table = 'oauth2"."access_token'
        managed = False


class Oauth2RefreshToken(AbstractRefreshToken):
    access_token = models.ForeignKey(Oauth2AccessToken)
    application = models.ForeignKey(Oauth2Application)

    class Meta:
        db_table = 'oauth2"."refresh_token'
        managed = False


class Oauth2Grant(AbstractGrant):
    
    class Meta:
        db_table = 'oauth2"."grant'
        managed = False
```

**Comment by joeherm** [comment]
Facing similar issues, were you ever able to successfully customize these models?

**Comment by szicari-farmobile** [comment]
@joeherm Yes, I did find a solution. I needed to configure the custom models like this instead:

```python
OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
    }
}
OAUTH2_PROVIDER_APPLICATION_MODEL = 'fm_django_auth.Oauth2Application'
OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = 'fm_django_auth.Oauth2AccessToken'
OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = 'fm_django_auth.Oauth2RefreshToken'
OAUTH2_PROVIDER_GRANT_MODEL = 'fm_django_auth.Oauth2Grant'
```

The difference between my initial configuration and this "new" configuration is that the old one essentially overrides properties on an already-instantiated settings object (hence the Model error, since Django has already instantiated the oAuth lib's own models); the new approach causes the oAuth lib to instantiate my custom models *instead of its own models* during the settings object's instantiation.

**Comment by joeherm** [comment]
Thanks for the quick response, very helpful! Was able to get things working :)

**Comment by szicari-farmobile** [comment]
Closing due to confirmation that the fix seems to work consistently enough.
