### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by MattBlack85** [jazzband/django-oauth-toolkit#582]
Hi people, is it possible to issue a new release to pypi? We're actually using master which carries a couple of needed changes but I'd like to avoid keeping a reference to master in production.
Also, I wanted to post this to the google group but it seems the link is broken, which is the right link?

**Comment by jleclanche** [comment]
The Google Group has been shut down in favour of this issue tracker.

Re release: Yes, very soon. I'd like to land #580 first.

**Comment by MattBlack85** [comment]
@jleclanche ty
