### ISSUE TITLE
Social Login & Client-Secret

### ISSUE THREAD

**Issue by mertgunay** [jazzband/django-oauth-toolkit#587]
### First of all, I check all of your documentation but I cannot find a why to solve my problems, 
Suggest that, I have mobile application for both ios and android.

In this mobile app, we have only social (facebook) login. For this senerio I have 2 questions;

1-) How should I save the application client id and client secret to obtain acces token.
Example: 
`curl -X POST -d "grant_type=password&username=<user_name>&password=<password>" -u"<client_id>:<client_secret>" http://localhost:8000/o/token/`

My app requests to this url. should I put client id and client secret as a variable without encrpyt ? 

2-) For `grant_type=password ` we need both username and password. But I'm trying to register a user with social login. So I do not have any kind of password. How can I do this. What do you suggest to solve these problems effeciantly ?
### Thanks a lot.

**Comment by jleclanche** [comment]
https://github.com/pennersr/django-allauth/

**Comment by mertgunay** [comment]
What do you mean with this link ? @jleclanche

**Comment by jleclanche** [comment]
django oauth toolkit is an oauth provider, not an oauth consumer. you want allauth if you want to log in to facebook

**Comment by mertgunay** [comment]
How should I save the application client id and client secret to obtain acces token ?
What about this question ? There is no information about store cliend id and secret ?

**Comment by jleclanche** [comment]
django oauth toolkit is not the library you're looking for.

**Comment by mertgunay** [comment]
Okey, thank you for giving your time
