### ISSUE TITLE
AuthorizationView throws 502

### ISSUE THREAD

**Issue by jordantomax** [jazzband/django-oauth-toolkit#588]
First, let me say thanks for making such an amazing package!

I am running into an issue whereby users on our production server request a token using the url `https://api.meural.com/oauth/authorize/?client_id=<client_id>&response_type=code&state=<state>&scope=read+write&redirect_uri=<redirect_uri>` and the server throws a 502. If the user then clears cookies, the problem goes away. Our urls are as follows

```
from django.conf.urls import url
import oauth2_provider.views as oauth2_views

urlpatterns = [
    url(r'^authorize/?$', oauth2_views.AuthorizationView.as_view(), name="authorize"),
    url(r'^token/?$', oauth2_views.TokenView.as_view(), name="token"),
    url(r'^revoke-token/?$', oauth2_views.RevokeTokenView.as_view(), name="revoke-token")
]
```

We have regular Token based authentication on the site in addition to oAuth Token based authentication. At first I thought that may be causing some conflict, but I'm having trouble reproducing the issue reliably based on that hypothesis. 

Am digging into the code now. I see `validate_authorization_request` inside the `get` method:

```
        try:
            scopes, credentials = self.validate_authorization_request(request)
        except OAuthToolkitError as error:
            # Application is not available at this time.
            return self.error_response(error, application=None)

```

Could `error_response` actually trigger a `502`? Any other ideas about why this may be happening. Thanks in advance for your help!

**Comment by MattBlack85** [comment]
502 is actually bad gateway, sounds like a proxy issue (nginx?) feel free to re-open in case
