### ISSUE TITLE
Release new version to PyPI to address bad default value for RefreshToken `revoked`

### ISSUE THREAD

**Issue by wli** [jazzband/django-oauth-toolkit#589]
The version on pypi (1.1.0) contains a critical bug that invalidates all refresh tokens when running a migration, and is NOT noted in the changelog. This was corrected in a follow-up pull request, but was not released yet.

https://github.com/jazzband/django-oauth-toolkit/commit/83ec4ac1e774641670d4641483e622f9b60b50ae

I just ran into this bug in my production instance, which logged out all my users. For anyone else who hits this, you can run the following code AFTER you run the migration (0006_auto_20171214_2232).
```
from oauth2_provider.models import RefreshToken
RefreshToken.objects.update(revoked=None)
```

@jleclanche

**Comment by jleclanche** [comment]
Done
