### ISSUE TITLE
Error 500 Value error on invalid base64 basic auth header.

### ISSUE THREAD

**Issue by d1p** [jazzband/django-oauth-toolkit#591]
Thanks for this amazing package.
I just ran into an issue where If someone submits crafted basic auth header with a crafted base64 string like
`Basic ZHVtbXk=:ZHVtbXk=`
it results in an Error 500, ValueError: not enough values to unpack (expected 2, got 1)

**Comment by jleclanche** [comment]
Thanks for the report! Could you write a test for this and PR it? Fix should be pretty simple.

**Comment by d1p** [comment]
Sure.
