### ISSUE TITLE
[Question]: What is music?

### ISSUE THREAD

**Issue by elcolie** [jazzband/django-oauth-toolkit#594]
I have questions
1. What is `scope` in the document context?
     ```python
     OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
    }
    ```
    Because `scopes` contain `verb`, and `plural nouns`. I am confusing the usage and key idea of it

2. ` required_scopes = ['music']` What is music? Is it model
3. What is the relation between `music` and `song`? What is the model relation?

**Comment by prafulbagai** [comment]
1. It is like `permission`. If the token has required permission(scope), then the view is accessible.

2. `music` is a scope. You need to add `music` in `OAUTH2_PROVIDER['SCOPES']`.

3. No relation. `music` is just a scope which is required to access the view.


You need to brush up your OAuth2 Skills.

**Comment by elcolie** [comment]
@prafulbagai  OK. Thank you.
