### ISSUE TITLE
How to have different read/write scope for a View?

### ISSUE THREAD

**Issue by prafulbagai** [jazzband/django-oauth-toolkit#595]
I'm using DRF and OAuthToolkit. Here is my view:-

    class UserDetailView(RetrieveUpdateDestroyAPIView):
        serializer_class = UserUpdateSerializer
        permission_classes = [TokenHasResourceScope]
        required_scopes = ['user_detail']

Now, the above view will support `GET`, `PUT`, `PATCH`, and `DELETE` methods. Now, if I create a token with a scope as `user_detail`, it will give access to all the methods. However, I want different read/write scopes for SAFE and UNSAFE methods.

Upon reading [OAuthToolkit](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/contrib/rest_framework/permissions.py#L99) code for `TokenHasResourceScope`, it create scopes for `SAFE` and `UNSAFE` methods, ie `user_detail:read` and `user_detail:write`.

Now, if the client request for `user_detail:read` scope, the library returns `invalid scope`.

How do I support scopes for read and write of a particular view differently?

**Comment by AraujoBravo** [comment]
I want create an access_token for TokenHasResourceScope permission:  `client:read`
but the TokenView returns 
`{
    "error": "invalid_scope"
}`
how can i get it accepted?

**Comment by AraujoBravo** [comment]
> TokenHasResourceScope



> I'm using DRF and OAuthToolkit. Here is my view:-
> 
> ```
> class UserDetailView(RetrieveUpdateDestroyAPIView):
>     serializer_class = UserUpdateSerializer
>     permission_classes = [TokenHasResourceScope]
>     required_scopes = ['user_detail']
> ```
> 
> Now, the above view will support `GET`, `PUT`, `PATCH`, and `DELETE` methods. Now, if I create a token with a scope as `user_detail`, it will give access to all the methods. However, I want different read/write scopes for SAFE and UNSAFE methods.
> 
> Upon reading [OAuthToolkit](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/contrib/rest_framework/permissions.py#L99) code for `TokenHasResourceScope`, it create scopes for `SAFE` and `UNSAFE` methods, ie `user_detail:read` and `user_detail:write`.
> 
> Now, if the client request for `user_detail:read` scope, the library returns `invalid scope`.
> 
> How do I support scopes for read and write of a particular view differently?
Here it specifies the solution:
https://github.com/jazzband/django-oauth-toolkit/issues/410

**Comment by AraujoBravo** [comment]
> I'm using DRF and OAuthToolkit. Here is my view:-
> 
> ```
> class UserDetailView(RetrieveUpdateDestroyAPIView):
>     serializer_class = UserUpdateSerializer
>     permission_classes = [TokenHasResourceScope]
>     required_scopes = ['user_detail']
> ```
> 
> Now, the above view will support `GET`, `PUT`, `PATCH`, and `DELETE` methods. Now, if I create a token with a scope as `user_detail`, it will give access to all the methods. However, I want different read/write scopes for SAFE and UNSAFE methods.
> 
> Upon reading [OAuthToolkit](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/contrib/rest_framework/permissions.py#L99) code for `TokenHasResourceScope`, it create scopes for `SAFE` and `UNSAFE` methods, ie `user_detail:read` and `user_detail:write`.
> 
> Now, if the client request for `user_detail:read` scope, the library returns `invalid scope`.
> 
> How do I support scopes for read and write of a particular view differently?


Here it specifies the solution:
https://github.com/jazzband/django-oauth-toolkit/issues/410
