### ISSUE TITLE
Oauth2 Custom Login Authentication

### ISSUE THREAD

**Issue by hassanali97** [jazzband/django-oauth-toolkit#596]
Hello!
i wanted to use my own custom login for authentication of Api and also i wanted to change
this url (accounts/login/?next=/o/applications)
i am not able to get the above url kindly help me out thank you ^_^
also i wanted to redirect url to /o/authorized after user logged in

**Comment by jdelic** [comment]
I am not entirely sure what you want to do, you'll need to give more details and/or be more precise:
* How do you want to "change the URL"? Do you just want to display a different HML template or do you want to change the actual URL/URL parameter names or the `next=` target?
* How are you "unable to get the above URL"? Are you unable to `reverse()` it?

I don't recall django-oauth-toolkit providing an endpoint `/o/authorized`, but I might be wrong. In any case, the OAuth2 standard iirc states that after authorization of the caller through the user, the OAuth2 server will redirect the user to the caller, as long as the URL is registered for the OAuth2 client.

If `authorized` is a typo and you meant `/o/authorize` which usually points to an instance of `AuthorizationView` then you wouldn't "redirect the user" there after login _yourself_. Instead, the flow works like this: The OAuth2 client knows the authorization endpoint of the OAuth2 server and sends the user there if the client has no valid refresh token or access token or they have expired. If the user isn't logged in when he gets sent to the authorization endpoint, he must authenticate (i.e. log in). Within django-oauth-toolkit, you have to realize that `oauth2_provider.views.base.BaseAuthorizationView` inherits from `django.contrib.auth.LoginRequiredMixin`, so Django will send the user to a login page and _then_ to the `AuthorizationView` for you. For more information, you can just follow up with the [relevant Django docs for contrib.auth](https://docs.djangoproject.com/en/2.0/topics/auth/).

Anyway, regardless of all of the above, it might help you to look at [my custom AuthorizationView](https://github.com/jdelic/authserver/blob/c48037a283d7202b830f83559b0bcbc70fd42156/authserver/mailauth/views.py#L32)  implementation and how I set up the [Django URL config](https://github.com/jdelic/authserver/blob/c48037a283d7202b830f83559b0bcbc70fd42156/authserver/authserver/urls.py#L28) to go with it. It might point you in the right direction for how to implement an extended login.
