### ISSUE TITLE
Application name shouldn't allow blank?

### ISSUE THREAD

**Issue by BigChief45** [jazzband/django-oauth-toolkit#600]
I accidentally created an application and forgot entering a name for it, which results in the list view looking like this:

![image](https://user-images.githubusercontent.com/6859247/40203565-d6e5e780-59e2-11e8-917a-b31a432b122f.png)

For me this seems like an unwanted behavior. Plus, there is no link available to enter the detail view of the application.

I checked the model and found this:

```python
class AbstractApplication(models.Model):
    name = models.CharField(max_length=255, blank=True)
```

Seems to me that the model field should not allow blank values?

**Comment by jleclanche** [comment]
The application name is there because it's likely being used but nothing forces you to use it, nor should force you to use it.
