### ISSUE TITLE
Docs URL?

### ISSUE THREAD

**Issue by rfleschenberg** [jazzband/django-oauth-toolkit#601]
There seem to be two instances of the docs on RTD:

* https://django-oauth-toolkit-latest.readthedocs.io/en/latest/
* https://django-oauth-toolkit.readthedocs.io/en/latest/

The first one looks more up to date. Which are the canonical docs? Should the link in the README be updated?

**Comment by jleclanche** [comment]
Second one is canonical. But i don't know what the state on it is. @synasius should have transferred it when the project went to Jazzband. @jezdez do you know?

**Comment by jezdez** [comment]
@jleclanche https://django-oauth-toolkit.readthedocs.io/en/latest/ is the correct one. The "latest" one is owned by a user "musemby" on ReadTheDocs, maybe @musemby?

**Comment by jleclanche** [comment]
@jezdez Yes, it was created by someone here who wanted to have up to date docs. But what I meant is I don't know what the state of automatic doc updates is on our rtd account.

**Comment by jezdez** [comment]
@jleclanche Oh I see, the build is broken and I just fixed it. It required using Python 3.x since the version of Django it installs by default requires it.

**Comment by jleclanche** [comment]
Great! Thanks :)

**Comment by jleclanche** [comment]
@jezdez Btw where is that docs build happening?

**Comment by jezdez** [comment]
@jleclanche Hm, you mean how docs are built? ReadTheDocs gets webhook posts from GitHub whenever a commit has happened and automatically builds the latest changes, then updates the https://django-oauth-toolkit.readthedocs.io/ with it.
