### ISSUE TITLE
Grant type client_credentials implementation

### ISSUE THREAD

**Issue by mekza** [jazzband/django-oauth-toolkit#603]
Hello,

We are implementing a OAuth 2.0 provider using `django-oauth-toolkit` and `django-rest-framework` for a ecommerce site using `django-oscar`. We have a SPA and our API, it makes sense to use `client_credentials` grant type as requests between SPA and API are only machine to machine. 

https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L477 

Here `request.user` is set to `None` which breaks `django-oscar-api` as it expects a user object (logged or anonymous). I can't understand why it was changed from `request.client.user` to `None` (https://github.com/jazzband/django-oauth-toolkit/commit/628f9e6ba98007d2940bb1a4c28136c03d81c245). 

Did anyone as ever face the same problem? Why `request.user` is set to `None`? 

Cheers

**Comment by jdelic** [comment]
When you look at the `git blame` for that line, it takes you to [commit 628f9e6](https://github.com/jazzband/django-oauth-toolkit/commit/628f9e6ba98007d2940bb1a4c28136c03d81c245) where this exact question was brought up and then #38 where a solution to your question seems to exist in [this comment](https://github.com/jazzband/django-oauth-toolkit/issues/38#issuecomment-145898061) and possibly less brittle [further down](https://github.com/jazzband/django-oauth-toolkit/issues/38#issuecomment-164777809)... but you're really better off reading the whole discussion.

Keep digging :). Please update the issue if this helps.
