### ISSUE TITLE
error 500 and ORA-00907: missing right parenthesis on request http://localhost:8000/o/token/?grant_type=refresh_token&refresh_token=xxx&client_id=xxx

### ISSUE THREAD

**Issue by e-sft** [jazzband/django-oauth-toolkit#616]
Python 3.6.3
Django==1.11.11
djangorestframework==3.8.2
django-oauth-toolkit==1.1.0
oauthlib==2.1.0
cx-Oracle==6.1

When I try to refresh token, this end up with an error 500.
http://localhost:8000/o/token/?grant_type=refresh_token&refresh_token=xxx&client_id=xxx

  File "/Users/eugene/django/mobapp/.env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/eugene/django/mobapp/.env/lib/python3.6/site-packages/django/db/backends/oracle/base.py", line 497, in execute
    return self.cursor.execute(query, self._param_generator(params))
django.db.utils.DatabaseError: ORA-00907: missing right parenthesis

params | {':arg0': <django.db.backends.oracle.base.OracleParam object at 0x11cfbba58>}
-- | --
query | ('SELECT * FROM (SELECT "_SUB".* FROM (SELECT '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."ID" AS Col1, '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."USER_ID" AS Col2, '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."TOKEN" AS Col3, '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."APPLICATION_ID" AS Col4, '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."ACCESS_TOKEN_ID" AS Col5, '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."CREATED" AS Col6, '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."UPDATED" AS Col7, '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."REVOKED" AS Col8 FROM '  '"OAUTH2_PROVIDER_REFRESHTOKEN" WHERE ("OAUTH2_PROVIDER_REFRESHTOKEN"."ID" = '  ':arg0 AND "OAUTH2_PROVIDER_REFRESHTOKEN"."REVOKED" IS NULL) ORDER BY '  '"OAUTH2_PROVIDER_REFRESHTOKEN"."ID" ASC FOR UPDATE) "_SUB" WHERE ROWNUM <= '  '1)')
self | <django.db.backends.oracle.base.FormatStylePlaceholderCursor object at 0x11cfbbda0>

When I execute SQL in debugger I receive this error too.
 
SELECT * FROM (SELECT "_SUB".* FROM (SELECT 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."ID" AS Col1, 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."USER_ID" AS Col2, 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."TOKEN" AS Col3, 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."APPLICATION_ID" AS Col4, 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."ACCESS_TOKEN_ID" AS Col5, 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."CREATED" AS Col6, 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."UPDATED" AS Col7, 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."REVOKED" AS Col8 FROM 
 API.OAUTH2_PROVIDER_REFRESHTOKEN WHERE ("OAUTH2_PROVIDER_REFRESHTOKEN"."ID" = 
 23 AND "OAUTH2_PROVIDER_REFRESHTOKEN"."REVOKED" IS NULL) ORDER BY 
 "OAUTH2_PROVIDER_REFRESHTOKEN"."ID" ASC FOR UPDATE) "_SUB" WHERE ROWNUM <= 
 1) 

ORA-00907: missing right parenthesis
00907. 00000 -  "missing right parenthesis"
*Cause:    
*Action:
Error at Line: 12 Column: 42
If I'm deleting "FOR UPDATE" from SQL request, request execute without errors.

Help me, please.

**Comment by rooftopcellist** [comment]
:wave:  This is fixed in 1.1.0 with this [commit](https://github.com/jazzband/django-oauth-toolkit/commit/281b46c250ab9d0e565490bbd75728cf4b9dad0c).
