### ISSUE TITLE
Python 3.4 or Python 3.5

### ISSUE THREAD

**Issue by robrap** [jazzband/django-oauth-toolkit#617]
The [README for 1.2.0](https://github.com/jazzband/django-oauth-toolkit/blob/86e8f9b22c9d5957b8ff6097208de69758a3c013/README.rst) states that the requirement is Python 3.5+. 

However, the [Changelog](https://github.com/jazzband/django-oauth-toolkit/blob/master/CHANGELOG.md) states that the minimum is Python 3.4+.

**Comment by jleclanche** [comment]
It's 3.4+, sorry for the confusion.

**Comment by robrap** [comment]
No worries.  Just letting you know so you could update the docs either way.  Thanks!

**Comment by robrap** [comment]
Created a PR if you want one: https://github.com/jazzband/django-oauth-toolkit/pull/618
