### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'abcdefg' (/o/applications/{pk}/)

### ISSUE THREAD

**Issue by ptrojanowski** [jazzband/django-oauth-toolkit#621]
Is there a reason to have this regex in urls.py `[\w-]` instead of  `[0-9^/]` (for `pk`)?

Visit  for example: http://example.com/o/applications/1asdgsdg/, you will get this error:

> ValueError: invalid literal for int() with base 10: '1asdgsdg'

Take a look at this pull request:

**Comment by MattBlack85** [comment]
closing with the same reason of the closed PR
