### ISSUE TITLE
exposing only /token/ endpoint to public

### ISSUE THREAD

**Issue by anuj9196** [jazzband/django-oauth-toolkit#628]
I'm using this plugin which does not require applications creation by any user and any OAuth application can be only added by **superuser**.

I have this included in the `urlpatterns`
```
path('auth/', include('oauth2_provider.urls', namespace='oauth2_provider')),
```
This is exposing all `urls` including enpoints for managing applications to the public
```
auth/ ^authorize/$ [name='authorize']
auth/ ^token/$ [name='token']
auth/ ^revoke_token/$ [name='revoke-token']
auth/ ^introspect/$ [name='introspect']
auth/ ^applications/$ [name='list']
auth/ ^applications/register/$ [name='register']
auth/ ^applications/(?P<pk>[\w-]+)/$ [name='detail']
auth/ ^applications/(?P<pk>[\w-]+)/delete/$ [name='delete']
auth/ ^applications/(?P<pk>[\w-]+)/update/$ [name='update']
auth/ ^authorized_tokens/$ [name='authorized-token-list']
auth/ ^authorized_tokens/(?P<pk>[\w-]+)/delete/$ [name='authorized-token-delete'] 
```

I want only `/token/` endpoint for the public to generate an access token and refresh token.

**How can I prevent other endpoints from the public and allow only from admin panel?**

**Comment by alysivji** [comment]
Writing this up for others looking for a solution: look at the [urls.py module of this package](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/urls.py) and pull out the views you want to keep in your project's urls.py
