### ISSUE TITLE
REFRESH_TOKEN_GRACE_PERIOD_SECONDS is broken

### ISSUE THREAD

**Issue by glassfordm** [jazzband/django-oauth-toolkit#631]
I'm using django-oauth-toolkit 1.1.2, since I need to use it with Django 1.11, but I believe the issue still exists in the latest django-oauth-toolkit.

REFRESH_TOKEN_GRACE_PERIOD_SECONDS is supposed to make it possible to use a refresh token once, then use it a second time within the grace period in case the response to the first refresh request is lost. However, the refresh token returned by the second request is never saved to the database, and so is invalid and unusable.

# Obtain the initial refresh token
`$ curl -X POST -d "client_id=[INSERT ID]&client_secret=[INSERT SECRET]&grant_type=authorization_code&code=XOJQVyWLXSCOE20wgDv7HKyc2sYrVf&redirect_uri=http://127.0.0.1:8000/" http://127.0.0.1:8000/o/token/`

`{"access_token": "eW2Ph0TyGFV139hbf9iKY6YgKX1cO1", "token_type": "Bearer", "expires_in": 36000, "refresh_token": "4oHfArCi0fn9NJEQnWAVo9sRgBgn2h", "scope": "read"}`

# Use the refresh token
`$ curl -X POST -d "client_id=[INSERT ID]&client_secret=[INSERT SECRET]&grant_type=refresh_token&refresh_token=4oHfArCi0fn9NJEQnWAVo9sRgBgn2h" http://127.0.0.1:8000/o/token/`

`{"access_token": "YwUOsNq7HTVJcleIdvbx6tKPdBiO3v", "token_type": "Bearer", "expires_in": 36000, "refresh_token": "1P7zayXdg3FpgZ0fN6mZfuPRw1E4nN", "scope": "read"}`

# Use the same refresh token a 2nd time
`$ curl -X POST -d "client_id=[INSERT ID]&client_secret=[INSERT SECRET]&grant_type=refresh_token&refresh_token=4oHfArCi0fn9NJEQnWAVo9sRgBgn2h" http://127.0.0.1:8000/o/token/`

`{"access_token": "YwUOsNq7HTVJcleIdvbx6tKPdBiO3v", "token_type": "Bearer", "expires_in": 36000, "refresh_token": "GvgyHHkqGuBTOgakNA14rqfMS56E4B", "scope": "read"}`

# The refresh token returned by the 2nd refresh request is invalid
`$ curl -X POST -d "client_id=[INSERT ID]&client_secret=[INSERT SECRET]&grant_type=refresh_token&refresh_token=GvgyHHkqGuBTOgakNA14rqfMS56E4B" http://127.0.0.1:8000/o/token/`

`{"error": "invalid_grant"}`

**Comment by ZuSe** [comment]
I can confirm it !

**Comment by ziXet** [comment]
Yes! I can confirm it as well. The second refresh token is not in the database at all!

**Comment by ziXet** [comment]
I have created a PR for this issue. https://github.com/jazzband/django-oauth-toolkit/pull/660
