### ISSUE TITLE
Refresh token usage not clear

### ISSUE THREAD

**Issue by doc-E-brown** [jazzband/django-oauth-toolkit#635]
Within the documentation it is not clear as to how to use a refresh token to get a new OAUTH token.  I am happy to issue a pull request against this issue.  There is documentation regarding the expiration and clearing of refresh tokens, but not how to use them.

**Comment by doc-E-brown** [comment]
Hi @bartmika I have submitted a patch to update the documentation.  The diff is [here](https://github.com/jazzband/django-oauth-toolkit/pull/641/files?short_path=044b1d4#diff-044b1d4b8c6473e7309ab0673a5acad4
) for the update documentation and demonstrates using curl how to refresh tokens with password resources.

**Comment by bartmika** [comment]
@doc-E-brown Thank you, much appreciated!
