### ISSUE TITLE
Request object missing from Django authentication

### ISSUE THREAD

**Issue by ripal-pm** [jazzband/django-oauth-toolkit#636]
Hi,

First of all, thanks for creating this toolkit and hope this request will expand it's usage.

Many third party AUTHENTICATION_BACKENDS requires request object. This toolkit is not passing request object to django.contrib.auth.authenticate(). If you will update **oauth2_validators.py=>validate_user**'s authenticate call from **authenticate(username=username, password=password)** to **authenticate(request=request, username=username, password=password)** will fix this issue.

Hope you will be able to make this change quickly.

Thanks with best regards,
ripal-pm

**Comment by adamchainz** [comment]
Fixed in #643 I believe.
