### ISSUE TITLE
Custom restrictions and permissions in TokenView

### ISSUE THREAD

**Issue by papayuca** [jazzband/django-oauth-toolkit#646]
Hi,

What would be a preferred approach to add some restrictions based on combination of the application (client_id) and the user, when providing an access token? E.g. users coming from admin application (client) can obtain token only if they meet certain requirements, e.g. they are admin.
My idea is to override the TokenView, and add this in the post handler, but not sure if that would be a good practice. Any suggestions are welcome!

Thanks and cheers!
P

**Comment by jdelic** [comment]
@papayuca sorry, I didn't see your issue before. Out of the box `django-oauth-toolkit` doesn't provide that functionality and I'm going to assume that about a month later you will already have solved this problem.

However, an example of how to achieve what you want to do can be [found in my authserver project](https://github.com/jdelic/authserver/blob/77921f75aeea4e96306cecf76d5533258ee353f3/authserver/mailauth/views.py#L48). My project defines a custom `User` class that has `MNApplicationPermission` objects which are attached to [`MNApplication` (an implementation of django-auth-toolkit's `AbstractApplication`)](https://github.com/jdelic/authserver/blob/77921f75aeea4e96306cecf76d5533258ee353f3/authserver/mailauth/models.py#L371). The View linked above checks if the current user has the permissions required by the application before allowing the OAuth2 Authorize flow to complete.

I think that's what you also wanted to do.

**Comment by leogout** [comment]
Hey,

Thanks for this template @jdelic. As I used it in another project, I figured that authentication errors would yell an InvalidKey error which wouldn't get caught. I added this piece of code right after the `super().get(...)` part to avoid this:
```
if not resp.status_code == 200:
    return resp
```

**Comment by jdelic** [comment]
@leogout 
Thanks for the heads up! I'm looking into it :+1:. Also, it's nice to hear that my answer was useful to someone :)

I'm also closing this ticket as "probably stale and probably fixed".
