### ISSUE TITLE
Custom ACCESS_TOKEN_EXPIRE_SECONDS by application

### ISSUE THREAD

**Issue by tximpa91** [jazzband/django-oauth-toolkit#650]
Hi, 

I think that my question is pretty straight forward. I want to change the access_token_expire_secondsby application_id something custom like scopes classes.

Kind Regards.

**Comment by jleclanche** [comment]
https://github.com/jazzband/django-oauth-toolkit/blob/ee8cb080ff13b3fad8fd68a47ae7d5a671222a2c/oauth2_provider/oauth2_validators.py#L456

I don't think it's possible right now.

**Comment by jywsn** [comment]
I think you could write a custom validator, subclassing `oauth2_provider.oauth2_validators.OAuth2Validator` and overriding the `save_bearer_token()` method.  Within this method, you know the `request.client`.

**Comment by dopry** [comment]
overriding the validator should work. I would be open to a PR that introduces token settings at the application level it should defer the expires value to the Application model like [validate_redirect_uri](https://github.com/jazzband/django-oauth-toolkit/blob/9aa27c7528cdeda0b85bac5a8a00b39d696a43f9/oauth2_provider/oauth2_validators.py#L509) with something like ```python 
expires = request.client.get_access_token_lifetime()
```

and the application model should be update with an access token lifetime. It would be good to do bearer tokens as well.
