### ISSUE TITLE
releases vs. tags

### ISSUE THREAD

**Issue by n2ygk** [jazzband/django-oauth-toolkit#654]
@jleclanche I note that the last and latest ["Release" in github is 1.0.0](https://github.com/jazzband/django-oauth-toolkit/releases/tag/1.0.0) but that there are many newer tags:
```
1.1.3  …
 b31d693   zip   tar.gz
on Jun 3 
1.2.0  …
 86e8f9b   zip   tar.gz
on May 11 
1.1.2  …
 096ed11   zip   tar.gz
on May 8 
1.1.1  …
 0ae7548   zip   tar.gz
on Apr 13 
1.1.0  …
 e7c3558   zip   tar.gz
```
I see you(?) have been pushing these to [pypi.org](https://pypi.org/project/django-oauth-toolkit/#history) just not creating a github Release to match. Should there be github Releases published as well or just drop doing them as tags are sufficient?

How can I help?

**Comment by jleclanche** [comment]
I don't generally do github releases as it's not possible to do them automatically and the data isn't queriable/editable programmatically from git. Feel free to update the tags with the [matching changelog](https://github.com/jazzband/django-oauth-toolkit/blob/master/CHANGELOG.md) though if you think it helps.
