### ISSUE TITLE
Can we track each client usage?

### ISSUE THREAD

**Issue by anuj9196** [jazzband/django-oauth-toolkit#658]
I'm using **Django-OAuth-Toolkit** to allow client based authorization.

I have set different client for different platforms. Like for Android, a different client is used to generate the access token and for the web, a different client is used to generate the access token.

I want to log which the client is making the request.

**Comment by n2ygk** [comment]
I believe this information is in `self.context['request'].auth.application_id` as long as you are using the internal oauth2_provider. When the oauth2 provider is external, this information is currently not made easily available.

**Comment by n2ygk** [comment]
See #664 regarding external AS.
