### ISSUE TITLE
"+" in username for password grant?

### ISSUE THREAD

**Issue by bartmika** [jazzband/django-oauth-toolkit#665]
Hello,

I am using the **resource password grant** option. I successfully manage to get the following console code to run:

``
curl -X POST -d "grant_type=password&username=johnsmith@some_email.com&password=<password>" -u"<client_id>:<client_secret>" http://localhost:8000/o/token/
``

However, when I run the following, I get a *Invalid credentials given* error:

``
curl -X POST -d "grant_type=password&username=johnsmith+1@some_email.com&password=<password>" -u"<client_id>:<client_secret>" http://localhost:8000/o/token/
``

Do you know what is going on? I am simply adding `+1` to the email and this issue happens.

Thanks!

**Comment by jleclanche** [comment]
Urlencode it. It's a reserved character.
