### ISSUE TITLE
Invalid grant_type refresh_token

### ISSUE THREAD

**Issue by tximpa91** [jazzband/django-oauth-toolkit#672]
Hi I am trying to get a refresh token with this endpoint 127.0.0.1:8000/o/token/ and the payload , I already try with json and x-www-form-urlencoded. The response is always 401 invalid grant type
{
	
	"grant_type": "refresh_token",
	"refresh_token":"xxxxxx",
	"client_id":"xxxxx",
	"client_secret":"xxxxxx"

	
}

**Comment by jasonkiim** [comment]
Would love a follow-up regarding this. Experiencing the same issue with my project!

**Comment by JonathanHuot** [comment]
Json is different than x-www-form-urlencoded. Use `grant_type=refresh_token&refresh_token=xxxx&client_id=xxx&client_secret=yyy` as your HTTP body instead.

**Comment by saczuac** [comment]
Facing same issue!, how to fix this ?, i am doing the post through python request lib in python3.

**Comment by VivekDSrivastava** [comment]
Was anyone able to fix this issue ?
