### ISSUE TITLE
How do i implement Passwordless authentication OTP? 

### ISSUE THREAD

**Issue by amir5121** [jazzband/django-oauth-toolkit#673]
is there a way to specify how to validate a user other that username and password? i couldn't find anything in the settings.
similar to #380 but apparently the link referenced in the comments is invalid

**Comment by amir5121** [comment]
well i did a debug and things do happen in the settings apparently my bad.

for anyone else having this confusion `OAUTH2_VALIDATOR_CLASS` in the setting

and then extend OAuth2Validator and override the `validate_user` function

**Comment by HeroSony** [comment]
Hi @amir5121 , can you share me the example? I just used OTP as well.

**Comment by anuj9196** [comment]
Hi @amir5121  and @HeroSony Did you get this solved? I need help integrating the same thing in my application.

**Comment by amir5121** [comment]
I kinda missed the notification on this issue.. but none the less here is how i handled it back then.

`from django.contrib.auth import get_user_model
from oauth2_provider.oauth2_validators import OAuth2Validator


class OauthDachValidator(OAuth2Validator):
	def get_id_token(self, token, token_handler, request):
		pass

	def validate_silent_authorization(self, request):
		pass

	def validate_silent_login(self, request):
		pass

	def validate_user_match(self, id_token_hint, scopes, claims, request):
		pass

	def validate_user(self, username, password, client, request, *args, **kwargs):
		res = super(OauthDachValidator, self).validate_user(username, password, client, request, args, kwargs)
		print(username, password, client, request, args, kwargs)
		if not res:
			user = get_user_model().objects.get(username=username)
			if user.is_active and password.isdigit() and user.short_token == int(password):
				request.user = user
				user.remove_token()
				res = True
		return res
`
