### ISSUE TITLE
source refresh token is always null

### ISSUE THREAD

**Issue by singhravi1** [jazzband/django-oauth-toolkit#674]
Every access token is created with the source_refresh_token as null.

If we have specified this field as one to one, it should be stored in the access token object.

**Comment by n2ygk** [comment]
Access tokens only have a source_refresh_token if they've been obtained via
a Refresh Token -- which is optional for Authorization Code flow and not
even permitted for Implicit flow. So it is "normal" for the
source_refresh_token to be null in many cases.

**Comment by singhravi1** [comment]
Yep i just noticed this.

Few problems caused by this when using with SQL server (I'm bound to use this database :cry: ):
- as it is one to one field, its causing unique constraint failed (**can we change one to one to Foreignkey field in refresh token model as well as access token model?**)
- have to remove migrations folder in oauth2_provider as it causes _cannot update type of an AutoField_ error.

**Comment by n2ygk** [comment]
See #668 here and https://github.com/michiya/django-pyodbc-azure/pull/189 which fixes this. You are not the only one stuck using SQL Server;-)

**Comment by singhravi1** [comment]
Wow. This is interesting.

Both your PRs are on the point and needs to be merged asap.
But the issue causing unique constraint error will still be remaining?

Is the way i'm solving this correct?

**Comment by n2ygk** [comment]
The fix to `django-pyodbc-azure` is the correct fix. The relationship between access_token and source_refresh_token is OneToOne and nullable which is identical to making it ForeignKey unique and nullable. In order for this to work as-is with SQL Server, you have to either relax the uniqueness constraint (and take a risk;-) or fix the SQL DDL to work around SQL Server's failure to properly implement the NULL UNIQUE constraint. This workaround is implemented in https://github.com/michiya/django-pyodbc-azure/pull/189 as further described [here (pyodbc fix)](https://columbia-it-django-jsonapi-training.readthedocs.io/en/latest/database.html#advanced-topic-sql-server-workarounds) or, alternatively, [here (custom migration fix)](https://columbia-it-django-jsonapi-training.readthedocs.io/en/latest/database.html#workaround-mishandling-of-null-unique-indexes).

I strongly suggest the pydobc approach. Maybe upvote it and nag Michiya to merge;-) At least test and write a comment saying it works for you too.

**Comment by singhravi1** [comment]
@n2ygk 
I installed your commit on `django-pyodbc-azure`.
Then i installed `django-oauth-toolkit` and ran `migrate` command.
But, as ususal, got stuck on migration 0005 with `NotImplementedError: the backend doesn't support altering from/to AutoField.`

Am i doing anything wrong? Anything else i have to do?

**Comment by n2ygk** [comment]
I saw a later note from you that this worked. Did you figure it out?

**Comment by singhravi1** [comment]
Yes!

**Comment by n2ygk** [comment]
OK, closing this. Hopefully Michiya will merge it soon.
