### ISSUE TITLE
When the access_token is expired "Authentication credentials were not provided." is returned

### ISSUE THREAD

**Issue by smn-snkl** [jazzband/django-oauth-toolkit#677]
When the token is expired it returns

`{"detail":"Authentication credentials were not provided."}`

even though the credentials are provided in the request headers: 

`'HTTP_AUTHORIZATION': 'Bearer DJoUxCatnmzeh4ZGGUNhBxZP3erbdq'`

A better error message might be helpful, what do you think?

**Comment by jordanorc** [comment]
Same problem here, and I agree with you. It would be better to have a more clear message about expired tokens. There is any way to do that?

**Comment by n2ygk** [comment]
That error is actually coming from [Django-REST-framework](https://github.com/encode/django-rest-framework/blob/86aa549832b9468d14a9f66370cf15d6dbcb4bfa/rest_framework/exceptions.py#L169-L172):
```
class NotAuthenticated(APIException):
    status_code = status.HTTP_401_UNAUTHORIZED
    default_detail = _('Authentication credentials were not provided.')
    default_code = 'not_authenticated'
```
It is a result of the [introspection endpoint](https://tools.ietf.org/html/rfc7662#section-2.2) returning that the token is not active:
```
   The following is a non-normative example response for a token that
   has been revoked or is otherwise invalid:

     HTTP/1.1 200 OK
     Content-Type: application/json

     {
      "active": false
     }
```
So, perhaps suggest in DRF that the error message be more clear although all you can say is the access token is not active. The reason can be any number of:
- it's just an invalid token
- it expired
- etc.

See https://tools.ietf.org/html/rfc7662#section-4
