### ISSUE TITLE
Rest Framework: no such table: main.oauth2_provider_refreshtoken__old

### ISSUE THREAD

**Issue by softwaresale** [jazzband/django-oauth-toolkit#683]
Hello all.

Currently, I am trying to use django oauth toolkit with my REST api, which is built with django-rest-framework. I followed the django rest framework tutorial [here](https://django-oauth-toolkit.readthedocs.io/en/stable/rest-framework/rest-framework.html) to the letter. 

Everything for the most part works fine. I can access the admin site and register new applications. However, my problem comes when I try to request a new token.

Whenever I run
`$ curl -X POST -d "grant_type=password&username=<user_name>&password=<password>" -u"<client_id>:<client_secret>" http://localhost:8000/o/token/
` with the proper data filled in (I actually put my own username, password, client id, and client secret  in), I get a 500 error and get the following exception: 
`
no such table: main.oauth2_provider_refreshtoken__old
`.

Does anyone know how to fix this? I migrated prior to running, and the migration ran fine. I am also using a custom user class, if it makes a difference. It extends 
`django.contrib.auth.models.AbstractUser` and is registered in `settings.py` via the `AUTH_USER_MODEL` setting.

I am using django-oauth-toolkit v1.2.0, django-rest-framework v3.9.0, and django v2.1.4.

Thanks for your help!

**Comment by MattBlack85** [comment]
this problem was related to SQLite if I remember well and version 2.1.5 should have solved it. Can you replicate it on latest django version (2.1.7)?

**Comment by softwaresale** [comment]
Thanks! The upgrade worked perfectly.
