### ISSUE TITLE
If you are using implicit, authorization_codeor all-in-one grant_type, you must define redirect_uris field in your Application model

### ISSUE THREAD

**Issue by idobrodushniy** [jazzband/django-oauth-toolkit#685]
Hi!
I have got an error because of trying to access the AuthorizationView with credentials of application with grant type  'client-credentials'.
What is the right way to allow only "authorization-code" grant type in this view?

**Comment by huazaisix** [comment]
> Hi!
> I have got an error because of trying to access the AuthorizationView with credentials of application with grant type 'client-credentials'.
> What is the right way to allow only "authorization-code" grant type in this view?

Did you define redirect_uris in Application?

**Comment by theharshitgarg** [comment]
@huazaisix : Can you give an example?
