### ISSUE TITLE
How to skip approval promp after token expire

### ISSUE THREAD

**Issue by cloverink** [jazzband/django-oauth-toolkit#691]
Hi guys,

I have a question. 
I was setting OAUTH2_PROVIDER as below
```
ACCESS_TOKEN_EXPIRE_SECONDS: 1800,
REQUEST_APPROVAL_PROMPT: 'auto'
```

It works correctly but after _1800_ second.

I try to login again from popup window.
It still show approval prompt.

(I expect a system will not ask me again when I approved this site)
Any suggesstion ?

**Comment by n2ygk** [comment]
Assuming you are using Authorization Code, you’ll want to use a Refresh
Token to avoid the need to interact with the user. The first time a new
login occurs, the scopes are approved by the user and then access & refresh
tokens are granted. When access expires, use refresh to get a new one.
