### ISSUE TITLE
revoke token on invalid token returns 200 instead of 4xx

### ISSUE THREAD

**Issue by ashishmohite** [jazzband/django-oauth-toolkit#692]
revoke_token endpoint on passing  invalid token returns 200 instead of 4xx
I'm not sure whether it's intended way of working or a bug. To me it looks like a bug

**Comment by maciejb2k** [comment]
@ashishmohite I've done a little research about revoking token, and it's intended way of working.
django-oauth-toolkit is based on oauthlib, and the answers is in source code of oauthlib under this link: https://github.com/oauthlib/oauthlib/blob/7586b0b1f39b19d0779d9d7caa967a3f66c09702/oauthlib/oauth2/rfc6749/endpoints/revocation.py#L41

**Comment by JonathanHuot** [comment]
Yes, the behavior is expected and correct.
