### ISSUE TITLE
Do you plan to release a new version soon? 

### ISSUE THREAD

**Issue by andrroy** [jazzband/django-oauth-toolkit#697]
Hi! Are you planning a new release soon? We have been waiting for https://github.com/jazzband/django-oauth-toolkit/pull/611 for a while, as it is causing a lot of exceptions in production. I know we can install the latest version via Github, but I'm really looking forward to having the last version in pip

**Comment by sindrig** [comment]
Same for us, now that #678 has been merged.

Until then we will test master from github locally, but we probably won't release anything using it.

**Comment by MattBlack85** [comment]
+1 here, version 1.2.0 is almost one year old, can we release a new version 1.X? Or are we waiting to release a version 2?

**Comment by andrroy** [comment]
Any update on this?

**Comment by auvipy** [comment]
Will try to push a newer version on pypi by this week end

**Comment by andrroy** [comment]
@auvipy Any update on when we can expect a new release? Is there anything I can do to help? 🙂

**Comment by KBenas** [comment]
Ping :)

**Comment by auvipy** [comment]
wait

**Comment by auvipy** [comment]
this week end for sure

**Comment by reto-liip** [comment]
@auvipy Any update on when we can expect a new release? Is there anything I can do to help? 🙂 I'd love to have #678 within a release already.

**Comment by PetrDlouhy** [comment]
@auvipy Any progress with this?

**Comment by auvipy** [comment]
no sorry. other priority projects took my time!!

**Comment by adamchainz** [comment]
Bump - would like to have some compatibility fixes available outsid of a tarball, such as #643.

**Comment by adamchainz** [comment]
Btw let me know if there's anything I can do to help, such as becomign a maintainer.

**Comment by raunaqss** [comment]
Any update on this? Is this project open to other maintainers contributing?

**Comment by georgek** [comment]
I can also offer my help in maintaining. Is there anything blocking a 1.3.0 release with PKCE support?

**Comment by jezeniel** [comment]
Also want to contribute if possible for the release, anything that needs to be done so 1.3.0 can be released?

**Comment by reto-liip** [comment]
@MattBlack85 : you are listed as project lead on the [jazzband project's page](https://jazzband.co/projects/django-oauth-toolkit) , does it help if I prepare the PR according to https://jazzband.co/about/releases#continuous-integration ?

**Comment by Maronato** [comment]
Closing this since most of the PRs mentioned here were released on [1.3.0](https://github.com/jazzband/django-oauth-toolkit/releases/tag/1.3.0)
