### ISSUE TITLE
Allow access to only specific endpoints

### ISSUE THREAD

**Issue by hamza-jutt** [jazzband/django-oauth-toolkit#705]
By default all endpoints can be accessed with access token if permissions and scopes_required is not set on view. 
For example if I have 200 endpoints and only 3 should be accessed via access_token(OAuth 2.0). I'll have to add permission classes on all 197 views to not allow via access_token(Also there is not any clear way to make sure some endpoint is not accessed via access_token). 

Is there any way I could allow only specific views via access_token by some setting?
API is created with DRF

**Comment by Maronato** [comment]
What if you remove `oauth2_provider.contrib.rest_framework.OAuth2Authentication` from your rest_framework [DEFAULT_AUTHENTICATION_CLASSES](https://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme) and only set the OAuth2 `authentication_classes` on the 3 views that you wish to allow via oauth?
