### ISSUE TITLE
authorization_code should use pkce to verify public clients

### ISSUE THREAD

**Issue by Abhishek8394** [jazzband/django-oauth-toolkit#711]
According to RFC [https://tools.ietf.org/html/rfc7636#section-4](https://tools.ietf.org/html/rfc7636#section-4)  For public clients with `authorization_code` grant PKCE's `code_verifier` must be used to authenticate client. Currently authentication for public client is dropped altogether. 

**Current behaviour:**
Client's `code_challenge` is not used to authenticate public clients. This leaves public clients vulnerable to token interception attack.

**Expected behaviour:**
Public clients on `authorization_code` grant type must be verified by method described in RFC linked in the issue. 

I am not sure how much it would affect existing deployments by making this mandatory, but there should be some option / setting switch that we can flip to enable this security feature. 

I'll be open to working on this, let me know if I should.

**Comment by poswald** [comment]
The RFC 7636 extension to OAuth is somewhat narrow.. it protects against an attack vector that a lot of people simply don't have enabled.

That being said, I think it would be fine as an option. the way to get it into DOT would be first to make sure it's implemented in OAuthLib and then expose it here. I don't see it in that base library yet.

**Comment by JonathanHuot** [comment]
oauthlib support PKCE since version 3, and DOT implemented it since https://github.com/jazzband/django-oauth-toolkit/pull/678. However the DOT documentation was not build since it was merged, so the visibility is null.

If I'm not wrong, using DOT@master you can already do something like:

```python
def check_client_pkce(client_id):
   return clients_database[client_id].is_public

dot_settings = {
  ..,
  "PKCE_REQUIRED": check_client_pkce
}
```

**Comment by Maronato** [comment]
@JonathanHuot is correct. It's not enforced by default, but you can easily do that with some code.
The implementation of such a feature would look something like this:

```Python
# settings.py
from oauth2_provider.models import get_application_model

def enforce_public(client_id):
    client = get_application_model().objects.get(client_id=client_id)
    return client.client_type == client.CLIENT_PUBLIC

OAUTH2_PROVIDER = {
    # ...
    "PKCE_REQUIRED": enforce_public
}
```

I'll close this issue, but feel free to open again if you feel like this needs to be discussed further.
