### ISSUE TITLE
Revoke/remove all tokens when user gets inactive

### ISSUE THREAD

**Issue by singhravi1** [jazzband/django-oauth-toolkit#717]
When a user is_active becomes false, we should expire (better remove) all the tokens (access and refresh) associated with that user.

Is there any reason we have not done this yet?

**Comment by MattBlack85** [comment]
a signal in this case would be probably enough and not too hard to implement but user could have _a lot_ of tokens and making this synchronously is something personally I wouldn't do and is not something I'd like to see implemented for me automagically.
Given this is something relatively easy to implement, I'd leave things as they are now and leave this choice to the user (including the library to deal with this in an async way).
Also, not everybody is using `is_active`, we in fact have only inactive user on account creation, after activation we only have hard delete)

**Comment by singhravi1** [comment]
@MattBlack85 
We want to manage `is_active` for admin functionality for example to ban a user from platform temporarily.
Yeah, currently i'm doing this using signal but was wondering what could be the reason it is not inbuilt in the library.
Also, i'm using celery beat to run a task every day to delete stale user tokens. Hope it is alright to do?

**Comment by MattBlack85** [comment]
yes, your case is more than valid, I'm not advocating such a thing wouldn't be good, but as you say you are using celery while somebody else could use spinach, dramatiq, RQ or something else and this is the _real problem_. We cannot let's say provide a celery task by default cause not everybody is using that. We could _eventually_ hook into the signal on user .save() and define a function to be executed into the settings, something like:
```Python
OAUTH2_PROVIDER_INACTIVE_USER_ACTION = 'module.my_func'

# and within the signal
def act_to_inactive_user(sender, **kwargs):
    if kwargs['instance'].is_active is False:
        parts = settings.OAUTH2_PROVIDER_INACTIVE_USER_ACTION.split('.')
        module_path, func_name = '.'.join(parts[:-1]), parts[-1]
        module = import_module(module_path)
        getattr(module, func_name)(**kwargs)
```
not still sure this will provide a good point to this idea, I suppose in most of the cases it will be a null handler for it

**Comment by singhravi1** [comment]
Yes, i think we can left this management on the user according to their requirement and use case.
Thanks
