### ISSUE TITLE
Cannot register user in the authorization server

### ISSUE THREAD

**Issue by PinkFLoyd92** [jazzband/django-oauth-toolkit#720]
I setup an authorization server using this library following the instructions of the documentation.
[https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_01.html](tutorial)

I created a simple application using the route /o/applications.
![image](https://user-images.githubusercontent.com/8844096/60555814-1a688c00-9d04-11e9-84e6-594619848c0a.png)

Then I began to test its url using curl

> `curl -X POST -d "grant_type=password&username=ldavid&password=root" -u'MQep09BSYVM5keB8FRUKmhL6GhDAXfCmEAzL3iI9:1TyaQ2hgwcJdqyk55URqQXvUXFemtYOjv48R2NVGYIcFa9GW7H7mMO9y5jFzVjAzYoJwk4MYUHWR6oJhb1Z5JTcPrWsvGodVQ2uIPPxSVS0s4bzovvJDkfeoz0LbkpA6' http://localhost:7000/o/token/
> `

and it keeps sending me the message `{"error": "invalid_grant", "error_description": "Invalid credentials given."}`

The setup seemed fine, I am just trying to create a simple user on this application and retrieve the token but it does not work. Is the documentation outdated? or am I sending something wrong?

**Comment by EvaWMwangi** [comment]
Hello @PinkFLoyd92, how did you fix this?
Having the same problem ...
