### ISSUE TITLE
Limit amount of authentication tokens

### ISSUE THREAD

**Issue by cyril-glolent** [jazzband/django-oauth-toolkit#721]
Hi,

I would like to know if there is a way to limit the amount of token that a user can create?

I am using django-oauth2-toolkit to generate the token.
The user can hit the auth url  (http://localhost:8000/o/token/) as much as he wants and creates a new token everytime he goes to that url. 
This action will fill up my database with new valid token.

How can i limit this token creation?
Should i limit this token creation? (like allowing 10 tokens by users to be able to log in my app from different devices)

Thank you for your help.

Cyril

**Comment by Abhishek8394** [comment]
Putting a limit on amount of tokens a user can create would be something like business logic, it sits on a layer above the library. You can either disallow them from requesting an authorization code at `/authorize` in the first place or stop them at the `/token` endpoint. Subclass the respective views and perform your checks before letting the method proceed.

**Comment by IvanAnishchuk** [comment]
There's also a command for removing old expired tokens. Just saying.

**Comment by MattBlack85** [comment]
as @Abhishek8394 rightly pointed, is up to the upper layer to decide if there will be any limitation, overriding the method to create token and checking there if you are creating too many is the right way to go
