### ISSUE TITLE
Please release new version - Cannot revoke all tokens: AccessToken matching query does not exist

### ISSUE THREAD

**Issue by thenewguy** [jazzband/django-oauth-toolkit#764]
I am getting a DoesNotExist exception trying to clean up when a user logs out.

django-oauth-toolkit==1.2.0

```
from itertools import chain
from oauth2_provider.models import get_access_token_model, get_application_model, get_refresh_token_model

    access_tokens = get_access_token_model().objects.filter(user=user)
    refresh_tokens = get_refresh_token_model().objects.filter(user=user)

    for token in chain(access_tokens, refresh_tokens):
        token.revoke()

```

It appears this is fixed in master: https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/models.py#L397

It looks like the fix is a year old: https://github.com/jazzband/django-oauth-toolkit/commit/5b51da74019046ef4c8c81c9975db029a2113d52#diff-ac3d3b1e30eb6e828386263c3a1256ca

Please release a new version.

**Comment by rooftopcellist** [comment]
This would be useful for our team as well.  @thenewguy FYI, this fix is merged in the 1.1.3 release.

**Comment by thenewguy** [comment]
@rooftopcellist thanks. odd it made it in 1.1 but not 1.2

**Comment by n2ygk** [comment]
This commit was merged so I'm not sure if this is still an open issue. Please reopen if it is.
