### ISSUE TITLE
Revoke token endpoint returns nothing with 200 response.

### ISSUE THREAD

**Issue by anuj9196** [jazzband/django-oauth-toolkit#766]
Revoking token is giving `200` response with blank/empty body.

My payload is
```
client_id: "<client id>"
client_secret: "<client secret>"
token: "hWYM8L7GIyTLDen1ZVRvUx43cBhkJD"
token_type_hint: "refresh_token"
```

### Expected Behaviour
It should return the new access token.

### Using version
```
1.2.0
```

**Comment by JonathanHuot** [comment]
Hi @anuj9196 , the expected behavior is to return HTTP 200 for revocation of tokens. I don't get which new access token you'd want to be returned ? Are you mixing the revoke and the refresh grant maybe ?

**Comment by anuj9196** [comment]
@JonathanHuot Yes, it was refresh grant.
