### ISSUE TITLE
how to make it use my custom application register template

### ISSUE THREAD

**Issue by wingyiu** [jazzband/django-oauth-toolkit#77]
i install django-oauth-toolkit via pip, and i am trying to make a website for user to management their Applications. How to make it use my custom application register template?

```
class ApplicationRegistration(LoginRequiredMixin, CreateView):
    """
    View used to register a new Application for the request.user
    """
    form_class = RegistrationForm
    template_name = "oauth2_provider/application_registration_form.html"
```

as you see template_name is hardcode in the view.

**Comment by NBajanca** [comment]
Just one note on this:

In ``INSTALLED_APPS`` on ``settings.py``, ``'django.contrib.staticfiles',`` must be before ``'oauth2_provider',`` for the override to work.
