### ISSUE TITLE
How To Customize Responses for Invalid Credentials Given

### ISSUE THREAD

**Issue by mmohajer9** [jazzband/django-oauth-toolkit#784]
hi !
i'm implementing **OTP** by over riding **OAuth2_VALIDATOR_CLASS** method called **validate_user**

when the function returns false every time its response is 
`{
  "error": "invalid_grant",
  "error_description": "Invalid credentials given."
}
`
so i wanna change this to my customize response and i'm a little bit confused!

**Comment by DesKevinMendez** [comment]
What I did was create my own login class

`class LoginAPI(APIView):
    authentication_classes = []
    permission_classes     = []

    def post(self, request, *args, **kwargs):
        url, headers, body, status_code = TokenView().create_token_response(request)
        tokenInfo = json.loads(body)


        if tokenInfo.get('error') is None:
            user = User.objects.get(username=request.data.get("username"))
            tokenInfo['user'] =  {
                "username": user.username,
                "email": user.email,
            }
        else:
            errorMessage = {
                "detail": "Invalid credentials given."
            }
            tokenInfo = errorMessage
            
        return Response(tokenInfo, status=status_code)`

And my urls.py

`from .views import LoginAPI

urlpatterns = [
    ....
    path('0auth_login/', LoginAPI.as_view(), name="api_0auth_login"),
    ....
]`

**Comment by iproha94** [comment]
```
from django.utils.translation import gettext_lazy as _
from django.http import JsonResponse
from oauth2_provider.views.base import TokenView


class MyTokenView(TokenView):

    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)
        if response.status_code == 400:
            return JsonResponse(
                {'detail': _("Invalid credentials given.")}, status=400)

        return response

```

**Comment by mmohajer9** [comment]
> ```
> from django.utils.translation import gettext_lazy as _
> from django.http import JsonResponse
> from oauth2_provider.views.base import TokenView
> 
> 
> class MyTokenView(TokenView):
> 
>     def post(self, request, *args, **kwargs):
>         response = super().post(request, *args, **kwargs)
>         if response.status_code == 400:
>             return JsonResponse(
>                 {'detail': _("Invalid credentials given.")}, status=400)
> 
>         return response
> ```

ty ! this is the thing that i was looking for !
