### ISSUE TITLE
Release 1.3

### ISSUE THREAD

**Issue by rhenter** [jazzband/django-oauth-toolkit#785]
Some things we need to do for this release:

- [x] update CHANGELOG. It was last updated with PR #668 yet there have been about 30 PRs merged since then. There must be *something* that rates being listed in the CHANGELOG! See https://keepachangelog.com/en/1.0.0/.
- [x] make ONE CHANGELOG. There are currently two: [CHANGELOG.md](https://github.com/jazzband/django-oauth-toolkit/blob/master/CHANGELOG.md) and [docs/changelog.rst](https://github.com/jazzband/django-oauth-toolkit/blob/master/docs/changelog.rst).
- [x] Update [docs/index.rst](https://github.com/jazzband/django-oauth-toolkit/blob/master/docs/index.rst) to reflect oauthlib versions required.
- [x] update AUTHORS to reflect current contributors -- not updated in 3 years.
- [x] consider updating CONTRIBUTING to more clearly require CHANGELOG, etc. updates with any merged PR. 
- [x] add a pull request template like [this example](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/docs/pull_request_template.md)

**Comment by n2ygk** [comment]
I've just created a Milestone for [1.3](https://github.com/jazzband/django-oauth-toolkit/milestone/14)

We'll need to assign some issues and get to work on this. It's been 2 years since 1.2 was published.

**Comment by n2ygk** [comment]
@auvipy @jleclanche Do you think we can get to a 1.3 release? Let me know how I can help other than creating a milestone, which I've done.

**Comment by jleclanche** [comment]
Sorry folks I'm completely booked up for the next ~10 days. I'm always +1 on releasing more often, and with the recent django releases now's a good time as ever.

**Comment by n2ygk** [comment]
> Sorry folks I'm completely booked up for the next ~10 days. I'm always +1 on releasing more often, and with the recent django releases now's a good time as ever.

I can wait 10 days;-) 

Is master currently in a reasonable state for declaring a release? I can go ahead and do some testing...

**Comment by jleclanche** [comment]
I don't use it in production. I'd say if you tried master on prod data then we're good to go yes.

**Comment by auvipy** [comment]
I have some open PR that needs at least one approval to get merged!

**Comment by n2ygk** [comment]
> I have some open PR that needs at least one approval to get merged!

I'll take a look. Please assign your open PR to the 1.3.0 Milestone.

**Comment by auvipy** [comment]
https://github.com/jazzband/django-oauth-toolkit/pull/789

**Comment by n2ygk** [comment]
See #550 regarding readthedocs updates being broken since December 2018....

**Comment by n2ygk** [comment]
@auvipy Thanks so much for all your reviews and merges. Just a couple more please;-)

@jleclanche Once those are merged, I'll be submitting a (hopefully) final PR to:
- update the version in `setup.cfg`
- set a `1.3.0` tag
- set final release date in `CHANGELOG.md`

Anything I'm forgetting?

Will the jazzband-bot push it to pypi when the tag shows up?

@MattBlack85: We still need to fix the RTD webhook. (@jezdez:) I've applied for lead per the Jazzband documentation so hopefully that happens soon and I can fix the webhook. Meanwhile, it looks like your are the one. (@auvipy: see the jazzband docs on how to apply.)
