### ISSUE TITLE
herokuapp site is down

### ISSUE THREAD

**Issue by daveseff** [jazzband/django-oauth-toolkit#786]
It seems that every bit of official documentation points to using http://django-oauth-toolkit.herokuapp.com in their examples. This site seems to be broken at the moment.

**Comment by HsnVahedi** [comment]
Yes! It's broken. Does anyone know how we can create an "Oauth2 Consumer" ourselves?

**Comment by n2ygk** [comment]
I've never used the referenced herokuapp but I test OAuth 2.0 (the authorization service and REST APIs that uses it via Authorization: Bearer tokens) with [Postman].(https://learning.postman.com/docs/postman/sending-api-requests/authorization/#oauth-20)

You could also try [googling oauth2 consumer](https://www.google.com/search?q=Oauth2+Consumer). There are a bunch of examples out there.

I also have an example with some documentation at https://columbia-it-django-jsonapi-training.readthedocs.io/

**Comment by n2ygk** [comment]
See #815 

Any volunteers to resolve this issue (e.g. a documentation PR and/or update the demo app and provide instructions perhaps to run locally)?

**Comment by bastbnl** [comment]
Hey @HsnVahedi A bit late to the party, but I use the Google OAuth playground at https://developers.google.com/oauthplayground/. You can configure it to connect to your deployment
