### ISSUE TITLE
Getting error: "unsupported_grant_type" with grant_type: 'authorization_code'

### ISSUE THREAD

**Issue by godhar** [jazzband/django-oauth-toolkit#802]
With these POST request params:
     
grant_type: 'authorization_code',
        redirect_uri: 'http://localhost:4200/dashboard',
        client_id: 'CLIENT_ID',
        code,
        state,
        verifier

And header:
  'Content-Type': 'application/x-www-form-urlencoded'

I am getting a 400, with message: {error: 'unsupported_grant_type'}

Surely django supports 'authorization_code' grant type?

**Comment by sergilao** [comment]
I also had the same problem. I think the problem is your library expect `authorization-code` and oauthlib is waiting for `authorization_code`. Could you please fix it?

**Comment by godhar** [comment]
I got it in the end. The PKCE flow was incorrect at some point. It was not a Django problem per se.
