### ISSUE TITLE
push release 1.3.0 to pypi

### ISSUE THREAD

**Issue by n2ygk** [jazzband/django-oauth-toolkit#804]
Push release 1.3.0 to pypi

**Comment by auvipy** [comment]
do you have access? on PyPI?

**Comment by n2ygk** [comment]
@auvipy I'm working on getting it. I'm in touch with jazzband-roadies (@jezdez) who was away for a few days but is back and has been in touch today.

**Comment by auvipy** [comment]
ok great

**Comment by bastbnl** [comment]
Thanks for the work you all did for this release. Please include a pypi source release too, besides the wheel.

**Comment by n2ygk** [comment]
@synasius would you be so kind as to also add me as a pypi maintainer as you did for rtd in #550? pypi user is also n2ygk.

This will take the pressure off of @jezdez's jazzband-roadie backlog as we'll be able to get the release published and then later we can fix the github integrations -> webhooks.

**Comment by synasius** [comment]
@n2ygk Sure! You should be a maintainer now! :smile:

**Comment by n2ygk** [comment]
@auvipy why'd you reopen?

**Comment by n2ygk** [comment]
> @n2ygk Sure! You should be a maintainer now! 😄

@synasius would you also be so kind as to make me a maintainer of this github repo? @jannisleidel is apparently unavailable to do so. It's getting tiring doing manual rtfd and twine updates;-)

**Comment by jezdez** [comment]
Hey folks, just to be clear, following a multiple weeks of health related time-off earlier in the year (I wasn't able to use my computer keyboard comfortably) I've been scrambling to keep my family safe and secure during the pandemic for the past two weeks -- while working as usual and serving on the PSF board where we had to deal with the PyCon US cancellation.

In short, I hope you remember that I'm a person and do Jazzband in my freetime, just like you, and that releasing OSS is not essential enough to override handling larger life issues. I know this bus factor situation is not ideal and I do have plans to fix the situation. In the meantime I'm asking you to hang in there until things have settled a bit for me to work through the outstanding issues.

As always, we're all part of this. So flatten the curve and stay home.

**Comment by synasius** [comment]
@n2ygk I do not have access to repository settings anymore. Sorry but I can't help :man_shrugging:

**Comment by n2ygk** [comment]
> Hey folks, just to be clear, following a multiple weeks of health related time-off earlier in the year (I wasn't able to use my computer keyboard comfortably) I've been scrambling to keep my family safe and secure during the pandemic for the past two weeks -- while working as usual and serving on the PSF board where we had to deal with the PyCon US cancellation.
> 
> In short, I hope you remember that I'm a person and do Jazzband in my freetime, just like you, and that releasing OSS is not essential enough to override handling larger life issues. I know this bus factor situation is not ideal and I do have plans to fix the situation. In the meantime I'm asking you to hang in there until things have settled a bit for me to work through the outstanding issues.
> 
> As always, we're all part of this. So flatten the curve and stay home.

@jezdez Sorry - I wasn't trying to bash you. Just figured I'd ask for others to help where they can as I realize you don't have the bandwidth as the sole roadie, not to mention the concern around having a sole person covering a role. Let me know how I or others can help with your workload.

My employer has had to force a major research university in NYC to transition to 100% remote work and teaching so I do understand the issues you are dealing with.  The extra 3 hours a day of *not* commuting has freed up time for me to contribute to the community here.

Meanwhile, I have pypi and rtfd access so I can continue to manually pull stuff -- it's no big deal. Stay safe.
