### ISSUE TITLE
ModuleNotFoundError: No module named 'oauth2_provider'

### ISSUE THREAD

**Issue by yxm1277** [jazzband/django-oauth-toolkit#811]
Trying to run drf-yasg, but I got 
ModuleNotFoundError: No module named 'oauth2_provider'
My setting.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'oauth2_provider',
    'corsheaders',

    'drf_yasg',
    'snippets',
    'users',
    'articles',
    'todo',
    'people'
]

ST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAYLTA_AUTHENTICATION_CLASSED': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

OAUTH2_CLIENT_ID = '12ee6bgxtpSEgP8TioWcHSXOiDBOUrVav4mRbVEs'
OAUTH2_CLIENT_SECRET = '5FvYALo7W4uNnWE2ySw7Yzpkxh9PSf5GuY37RvOys00ydEyph64dbl1ECOKI9ceQ' \
                       'AKoz0JpiVQtq0DUnsxNhU3ubrJgZ9YbtiXymbLGJq8L7n4fiER7gXbXaNSbze3BN'
OAUTH2_APP_NAME = 'drf-yasg OAuth2 provider'

OAUTH2_REDIRECT_URL = static_lazy('drf-yasg/swagger-ui-dist/oauth2-redirect.html')
OAUTH2_AUTHORIZE_URL = reverse_lazy('oauth2_provider:authorize')
OAUTH2_TOKEN_URL = reverse_lazy('oauth2_provider:token')

**Comment by n2ygk** [comment]
Did you `pip install django-oauth-toolkit`?

**Comment by yxm1277** [comment]
> Did you `pip install django-oauth-toolkit`?

I have solved this problem. Thank you.

**Comment by pm80** [comment]
[](https://github.com/axnsan12/drf-yasg)

**Comment by pm80** [comment]
[drf-yasg](https://github.com/axnsan12/drf-yasg)

**Comment by newfeed123** [comment]
> Did you `pip install django-oauth-toolkit`?

thank you

**Comment by slain4ik** [comment]
> Did you `pip install django-oauth-toolkit`?

thank u!!!!! <3
