### ISSUE TITLE
Source to the OAuth Playground Heroku App?

### ISSUE THREAD

**Issue by winsmith** [jazzband/django-oauth-toolkit#815]
After creating a provider using OAuth Toolkit (really awesome documentation for that, btw), I want to have a separate app instance that uses the provider as auth server, but I don't really know how. 

The documentation for this is a bit unclear to me, either this topic is missing or I just don't get it. Either way, it would help me a lot if I could get a look at the source of the OAuth Playground app that's mentioned in the tutorial. 

Is this app open source, and if yes, does anyone have a link? If not, would the maintainers consider open sourcing the app, or relevant parts of it? Thanks :)

**Comment by n2ygk** [comment]
@masci @synasius I believe you had set up this heroku app something like 7 years ago(!). Can you make the source code available and/or suggest an alternative so we can update the tutorial?

**Comment by masci** [comment]
@n2ygk you might be looking for this https://github.com/evonove/django-oauth-toolkit-example I couldn't find any other piece of code in my archives, maybe @synasius will have more luck :smile:

**Comment by synasius** [comment]
@n2ygk yep @masci pointed you to the right repo :+1:

**Comment by winsmith** [comment]
Thank you so much! This helps a lot
