### ISSUE TITLE
Release 1.3.1 is incorrect on pypi

### ISSUE THREAD

**Issue by n2ygk** [jazzband/django-oauth-toolkit#819]
**Describe the bug**

I inadvertently pushed release 1.3.1 to pypi with a migration that was laying around from a dev branch.

**Version**

1.3.1

**Additional context**

I have maintainer but not owner access in pypi so can't delete the incorrect package.

**Comment by n2ygk** [comment]
@synasius Sorry to bug you: Would you please delete 1.3.1 from pypi? I screwed up when I twined it up. I don't have "Manage" access.

If you're unable, I supposed I can push 1.3.2 but I'd rather not have a bad package sitting there.

**Comment by n2ygk** [comment]
Temporary fix after migrate is remove the 0003 migration:
```
./manage.py migrate oauth2_provider 0002_auto_20190406_1805
```

**Comment by synasius** [comment]
@n2ygk Done! I think you won't be able to upload a `1.3.1` again but you have instead to upload a `1.3.2`
