### ISSUE TITLE
Generate access token using user instance (not username, password and grant_type)

### ISSUE THREAD

**Issue by anuj9196** [jazzband/django-oauth-toolkit#823]
**Describe the bug**
I'm using **Django REST Framework** and using this library to provide token based authentication to the frontend applications.

There is Login with Google implementation using `django-allauth` plugin.

I want to generate access token when user login using social account.

For handling social login and generating social account, I have created this view.

```
class GoogleLoginView(LoginView):
    """
    Enable login using google
    """
    adapter_class = GoogleOAuth2Adapter
    serializer_class = CustomSocialLoginSerializer

    def login(self):
        self.user = self.serializer.validated_data['user']
        self.token = TokenView().create_token_response(self.request)
        return self.token

    def post(self, request, *args, **kwargs):
        self.request = request
        self.serializer = self.get_serializer(
            data=self.request.data,
            context={'request': request}
        )
        self.serializer.is_valid(raise_exception=True)

        url, header, body, status_ = self.login()
        return Response(json.loads(body), status=status_)
```

The request data has `user` instance along with `client_id` and `client_secret` of the application.

But this gives error
```
'{"error": "unsupported_grant_type"}'
```

**To Reproduce**

**Expected behavior**
There should a method that can be used to generate access token using `client_id`, `client_secret` and `user` instance.

**Version**
django-oauth-toolkit==1.3.0

- [ ] I have tested with the latest published release and it's still a problem.
- [ ] I have tested with the master branch and it's still a problem.

**Additional context**

**Comment by anuj9196** [comment]
Got it solved by using custom validator like
```
from oauth2_provider.oauth2_validators import OAuth2Validator

from authentication.models import User


class CustomOAuth2Validator(OAuth2Validator):

    def validate_user(self, username, password, client, request, *args, **kwargs):
        user = request.user

        try:
            social_login = request.social_login
        except AttributeError:
            social_login = False

        if social_login and user:
            u = User.objects.get(email=user)
            if u.is_active:
                request.user = u
                return True
            return False

        return super().validate_user(username, password, client, request, *args, **kwargs)

```

**Comment by anik-s** [comment]
`
from oauth2_provider.models import AccessToken, Application, RefreshToken
from oauthlib import common
from django.utils import timezone

# generate access token and other things
application = Application.objects.get(pk=application_id)
# request.data. = True
user = getUser()
expires = timezone.now() + timezone.timedelta(seconds=oauth2_settings.ACCESS_TOKEN_EXPIRE_SECONDS)
access_token = AccessToken(
    user=user,
    scope='read write groups',
    expires=expires,
    token=common.generate_token(),
    application=application
)
access_token.save()
refresh_token = RefreshToken(
    user=user,
    token=common.generate_token(),
    application=application,
    access_token=access_token
)
refresh_token.save()
resp_data = {
    'token': {
        'access_token': access_token.token,
        'expires_in': oauth2_settings.ACCESS_TOKEN_EXPIRE_SECONDS,
        'token_type': 'Bearer',
        'scope': access_token.scope,
        'refresh_token': refresh_token.token
    },
    'user_id': user.id
}

return Response(resp_data, status=status.HTTP_200_OK, headers={})
`
@futurbotconsolidated
