### ISSUE TITLE
500 Server Error on accessing the token through postman

### ISSUE THREAD

**Issue by sumodhnair19** [jazzband/django-oauth-toolkit#843]
Hi,

I have been trying to access the token URL through postman. However I am getting "500- Server Error".  Below are some of the details for your reference :-

```
client_id: <my id>
client_secret: <my secret>
code:<generated-code>
code_verifier:<verifiercode>
grant_type:authorization_code
```
The content-type used is. "application/x-www-form-urlencoded;charset=UTF-8"

Please let me know what I am doing wrong?

Thanks,
Sumodh

**Comment by FluidSense** [comment]
Do you get anything else in response?
There seems to usually be an JSON-error attached when I get the same status code (500).

**Comment by n2ygk** [comment]
What are the errors in the django app server console?

**Comment by MattBlack85** [comment]
closing due inactivity, feel free to re-open providing more details
