### ISSUE TITLE
Best practice for for creating a user based token for 3rd party apps in Django

### ISSUE THREAD

**Issue by andrijan** [jazzband/django-oauth-toolkit#844]
I have an application that needs users to give access to a 3rd party application.

The requirements are that the 3rd party application has the same permissions as the user (acts on the user's behalf)

The 3rd party application has no frontend, so the oauth2 redirection flow doesn't quite work.

My initial thought was to create a model for 3rd-party applications and the User can add their own apps.

By adding an app, the user would receive a app ID (or client id) and a app Secret (or client secret). The user gives the 3rd party app this information and it can request a Bearer Token once (After that, this combination of ID and Secret won't work). That Bearer Token will live for X seconds, but the application can refresh the Token with a Refresh Token it will get back as well.

I realize this looks almost identical to Oauth2, but I haven't figured out how to achieve it with Django Oauth Toolkit at least.

Any recommendations?

Thanks!

**Comment by rminderhoud** [comment]
Seems over complicated, can you not just manually generate a refresh token and access token and require the user to manually pass that information to the 3rd party application initially?
