### ISSUE TITLE
It seems to be not supported for Django 3.0

### ISSUE THREAD

**Issue by Yebing2018** [jazzband/django-oauth-toolkit#849]
Hello, I use django-oauth-toolkit in Django 3.0, but it seems to be not supported for Django 3.0
![auth2](https://user-images.githubusercontent.com/43950313/85939419-f4da8680-b947-11ea-8a96-69275dbef0f3.jpg)

**Comment by auvipy** [comment]
https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/models.py this from master

**Comment by rminderhoud** [comment]
This is not the case with the latest `django-oauth-toolkit` version. Which version do you have installed?

**Comment by n2ygk** [comment]
DOT 1.3.2 works fine with Django 3.0. Closing.
