### ISSUE TITLE
How do i set cleartokens in cron or celery-beat?

### ISSUE THREAD

**Issue by Kiel-Hyre** [jazzband/django-oauth-toolkit#850]
Hi new here. Just stumble in the docs management in which it has cleartokens command

I manage to run it on shell python3 manage.py cleartokens (Very funny I spend long time how to run this too because I do not know that thing can run in terminal. # sorry newbie django) 

Though I do not have any idea how to do it in cron (said in the docs)
And if possible in celery-beat :)

so if anyone can give just a little example or tips on how to do it is much appreciated.

#ps if there is, maybe its a good idea to update the docs with example

**Comment by rminderhoud** [comment]
You can call this function https://github.com/jazzband/django-oauth-toolkit/blob/d392c608a85a682f6adba111576efe12288e27f6/oauth2_provider/models.py#L438

You can simply add a task to celery like so:
```python
from oauth2_provider.models import clear_expired

@app.task
def test(arg):
    clear_tokens()
```

**Comment by Kiel-Hyre** [comment]
Actually cleartokens uses clear_expired() 

right now we had django-celery-beat installed in our app thus, making tasks configuration much easier because it is in the /admin/

anyway this is just a simple code we had.

apps.__init__.py
```
from . import tasks
```

apps.tasks.py
```
@app.task
def async_cleartokens(*args):
    from django.core.management import call_command
    call_command('cleartokens')
```

settings.py
```
# just config the REFRESH_TOKEN_EXPIRATION_SECONDS here, in the docs.
```

and tasks seconds as said, is config in the /admin/


I still do not know how to do this in cron itself, anyway much appreciated for the help.
