### ISSUE TITLE
how can i change the access token and refresh token length?

### ISSUE THREAD

**Issue by raju010193** [jazzband/django-oauth-toolkit#851]
how can i change the access token and refresh token length?
"token": {
    "access_token": "bLAJ72PTuTZjXfckxtmPs2mYDkWt6T",
    "expires_in": 36000,
    "token_type": "Bearer",
    "scope": "read write groups",
    "refresh_token": "zr4m88eRv0ckjuUekhZRkYFiv6M7dW"
  }

**Comment by Kiel-Hyre** [comment]
https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html

you can change the token generator (ACCESS_TOKEN_GENERATOR) 
in which by default uses oauthlib.oauth2.tokens.random_token_generator
which uses common that with length=30 by default

so for me create your own generator

something in ur app folder
generators.py
```
def random_token_generator(length=50):
     # token in accessmodel had max_length of 255
     return common.generate_token(length)
```
then override the ACCESS_TOKEN_GENERATOR = 'apps.random_token_generator'
# ps this one is not tested XD but I hope  you know the concept.

**Comment by raju010193** [comment]
Thanks its working @Kiel-Hyre
