### ISSUE TITLE
How to implement google and facebook oauth2 in django rest framework ?

### ISSUE THREAD

**Issue by ahmedosama5200** [jazzband/django-oauth-toolkit#853]
I went through the documentation for a way to implement oauth2 using google and facebook providers but can't find anything. I am confused, what is this library really about ?

**Comment by bastbnl** [comment]
Do you want to enable people to login using a Google or a Facebook account on your site? Check django-allauth.

**Comment by ahmedosama5200** [comment]
I am not sure but django-allauth doesn't work with django rest framework.

**Comment by ahmedosama5200** [comment]
I have gone through documentation, they didn't even talk about how to use it with rest. also this [`one](https://github.com/Tivix/django-rest-auth) and this [one](https://github.com/RealmTeam/django-rest-framework-social-oauth2) are not maintained any more. Any solutions ?

**Comment by bastbnl** [comment]
I don't know what you're trying to achieve here, but let me describe what I did on brwnppr.com and maybe it helps. 

I wanted to build an application that allows users to login to the application using a social account, like Google and LinkedIn or an email account. This application is based on a REST API, which is consumed via OAuth2. I was struggling with the same thought and the solution I used was basically simpler. 

To my understanding you're using Bearer tokens to communicatie with the application. The OAuth dance to Google or LinkedIn enables my application to perform requests to Google or LinkedIn using the token that's linked to the users' account, so you're invoking requests on behalf of that user. Those tokens are intended to be used with Google or LinkedIn and are linked to the Google and LinkedIn accounts. 

The idea is **to setup a local account** on your Django application, using the data shared by the OAuth provider, which - for you - is Google or Facebook. `django-allauth` can safely setup and populate the user accounts on your Django application using the data provided by the social provider. Then, when you want to consume the OAuth API of the Django application you're developing, you are connecting to an authorization page hosted by your Django application. This authorization page (see: https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_01.html) enables the user to login using their Google or LinkedIn account **via the authorization page on your Django application** and the OAuth dance to your application gets you the tokens needed for the API provided by your Django application.

Does this make sense?

**Comment by ahmedosama5200** [comment]
Thanks for your reply
I have  decoupled app, django rest framework for backend, and multiple clients on the front end (angular, android, ios)
The flow of authentication should go like this, the client signs in with google or facebook, gets an id_token that will be sent to backend. on the backend, the token is verified and exchanged for user's email, name, etc..., then a jwt token is generated and sent to  the client, which is attached to all future requests.
I checked django allauth and it doesn't have such functionality, I think

I was previously working with nodejs and this process can be automated using [passportjs](http://www.passportjs.org/) library which is very well maintained and supported by nodejs community.

I can do this myself using a couple of different libraries, but I am trying to save myself some time and effort by finding a package that does this for me.

**Comment by professorhaseeb** [comment]
I use this for social oauth2 in DRF, works like a charm
https://github.com/RealmTeam/django-rest-framework-social-oauth2

**Comment by soerendip** [comment]
That seems to be written for django 1. Is it still working?

**Comment by rganowski** [comment]
In an [issue for django-rest-framework-social-oauth2](https://github.com/RealmTeam/django-rest-framework-social-oauth2/issues/241#issuecomment-790473262) I've just read that:

> This lib is not maintained anymore. Use https://github.com/wagnerdelima/drf-social-oauth2 instead
