### ISSUE TITLE
LIMIT/OFFSET is not supported with select_for_update on this database backend.

### ISSUE THREAD

**Issue by dag18e** [jazzband/django-oauth-toolkit#866]
We are using Oracle Database 12c Enterprise Edition Release 12.2.0.1.0, which from what I researched it seems the issue is coming from [this statement](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/models.py#L406-L409) since 12c doesn't allow limits in ```select_for_update``` statements. We were able to fix it with:
```python
            try:
                self = refresh_token_model.select_for_update().get(
                    pk=self.pk, revoked__isnull=True
                )
            except refresh_token_model.DoesNotExist:
                return
```

It would be great if we could stop maintaining the fork and just use the release version.

**Comment by MattBlack85** [comment]
@dag18e care to send a patch?

**Comment by dag18e** [comment]
Sure! We replaced [your code here](https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/models.py#L390-L395) with [this.](https://github.com/SpencerjCarroll/django-oauth-toolkit/blob/stable/1.1/oauth2_provider/models.py#L359-L366)

**Comment by 0ddlyoko** [comment]
Is it important to set `self = None` if you `return` just after ?

**Comment by dag18e** [comment]
@0ddlyoko No, you're right. The ```self = None``` line can be cut. Thanks for pointing that out.
