### ISSUE TITLE
Support for user.pk instead of user.id

### ISSUE THREAD

**Issue by anush0247** [jazzband/django-oauth-toolkit#869]
We have internally implemented a custom user model, where we don't have id as a primary key, instead, we have another key called user_id.

Suggested Fix:

Using `user.pk`

Ref: https://docs.djangoproject.com/en/3.1/ref/models/instances/#django.db.models.Model.pk

https://github.com/jazzband/django-oauth-toolkit/blob/4a83d4c17acae1ad2aee3ca1525ce1b7cdbfd801/oauth2_provider/oauth2_validators.py#L778

**Comment by MattBlack85** [comment]
it seems the issue was in the oicd code that for now is gone as it wasn't fully functional, closing

PS: i grepped the code and I couldn't find any reference to user.id
