### ISSUE TITLE
'OIDC_RSA_PRIVATE_KEY' is mandatory

### ISSUE THREAD

**Issue by n2ygk** [jazzband/django-oauth-toolkit#873]
**Describe the bug**

Existing code using the latest master commit (pr #859) throws an error when not using OIDC features.

**To Reproduce**

Install DOT master commit 295c065a3e5a14b777f1e56c8e36adedae0af461

**Expected behavior**

Code not using OIDC should continue to work.

**Version**

master 295c065a3e5a14b777f1e56c8e36adedae0af461

- [ ] I have tested with the latest published release and it's still a problem.
- [x] I have tested with the master branch and it's still a problem.

**Additional context**

```
  File "/Users/alan/src/django-training/env/lib/python3.7/site-packages/oauth2_provider/settings.py", line 217, in validate_setting
    raise AttributeError("OAuth2Provider setting: %r is mandatory" % (attr))
rest_framework.request.WrappedAttributeError: OAuth2Provider setting: 'OIDC_RSA_PRIVATE_KEY' is mandatory
```

**Comment by FluidSense** [comment]
I'm a bit interested in this, as we are currently using [django-oidc-provider](https://github.com/juanifioren/django-oidc-provider), but it has gone stale. It would be nice to migrate over to django-oauth-toolkit, but we would then need OIDC-support in django-oauth-toolkit. 
Could a solution to this be implementing RSA private key as in django-oidc-provider, e.g., adding a command for generating it, storing it in a model and accessing it through there? Then it could be moved out of settings and removed from `MANDATORY_SETTINGS` which seems to be the source of this error message.

Perhaps @thinkwelltwd can contribute with some insight into the decisions on having it in settings?

**Comment by n2ygk** [comment]
@FluidSense We'v have had to revert #859 until it doesn't break existing non-OIDC usage. Probably just a few configuration tweaks needed here and there. It also needs to be documented and clearly some more test cases are needed. The plan is to make a small 1.3.3 release without the OIDC feature and then hopefully get the contributors to finish up the PR such that it is mergeable into a new major release. It sill needs a fair amount of work to make that happen.

Help making this happen would be appreciated!

**Comment by FluidSense** [comment]
I see, that sounds like a good decision seeing as there has been no recent releases, but some fixes. 

Perhaps a place to start to look into things would be the reverted PR then, to see if I have something to contribute there, and if I can understand enough of it to document on behalf of the original authors

**Comment by n2ygk** [comment]
Reverted in #877
