### ISSUE TITLE
question: How do I get user info from o/callback?

### ISSUE THREAD

**Issue by showell** [jazzband/django-oauth-toolkit#874]
I am just getting starting with this toolkit.  I have been able to call o/code an o/callback to get a response with these fields:

* access_token
* expires_in
* token_type
* scope
* refresh_token

I would like to extend the response to include things from my User model:

* id
* full_name

What is the recommended way to do that?  I tried finding this in the docs, so apologies in advance if this is already documented, and doc links are welcome, of course.

**Comment by showell** [comment]
I am also wondering if there's a better way to get help in general, such as an IRC channel or some forum.  Thanks!

**Comment by aero31aero** [comment]
We can always extend the view to do this, but we need to copy the entire code of the view to be able to use the token.

```python
class TokenView(oauth2_views.TokenView):
    # Like a lot of other things, we have to copy paste the entire view code
    # just to make a small change here.

    def do_something(self, token, request, response):
        req = HttpRequest()
        req.method = 'GET'
        req.META = request.META
		req.META["Authorization"] = f"bearer {access_token}"
		(ok, req) = get_oauthlib_core().verify_request(req, [])
        user_profile = UserProfile.objects.get(id=req.user.id)
        print("PROFILE", user_profile)

    def post(self, request, *args, **kwargs):
        url, headers, body, status = self.create_token_response(request)
        token = None  # custom: Capture the token in this scope
        if status == 200:
            access_token = json.loads(body).get("access_token")
            if access_token is not None:
                token = get_access_token_model().objects.get(token=access_token)
                app_authorized.send(sender=self, request=request, token=token)
        response = HttpResponse(content=body, status=status)
        self.do_something(token, request, response)
        for k, v in headers.items():
            response[k] = v
        return response
```

**Comment by FluidSense** [comment]
I would suggest creating a specific endpoint to retrieve user info and authenticating for that endpoint with the access token. Yes, it requires another round-trip to the API, but Oauth2 is meant for authorization and not authentication.
The OIDC standard is meant for authentication and usually incoporates a /userinfo-endpoint as specified the [specs](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo).
There is ongoing work on extending this package to also support OIDC, but there is no current due date or roadmap for it.

**Comment by showell** [comment]
@FluidSense Thanks for the guidance.  In our app it's not much trouble to make the extra round trip, so we'll just do that.  Closing.
