### ISSUE TITLE
Heroku Service for consumer testing down?

### ISSUE THREAD

**Issue by AlexLangeComputerWang** [jazzband/django-oauth-toolkit#875]
Hello!

I am going through the tutorials on setting up Oauth Toolkit on readthedocs,
there is a section on the tutorial for testing the authorization servers using a heroku consumer service if I am not very familiar with Oauth2 (I am definitely not familiar with oauth2 heheh), but the site for testing that authorization is down due to an application error.
Is there someone I should contact to get that fixed or up and running?

**Comment by n2ygk** [comment]
The Heroku app has been down for a long time. A Pull Request to fix the documentation to remove the heroku reference would be gladly accepted and would be your chance to learn a little more about oauth2.

I suggest:
- remove heroku references from the documentation.
- replace that with documentation on how to test locally with Postman as the consumer. [Here](https://columbia-it-django-jsonapi-training.readthedocs.io/en/latest/using_oauth2.html#get-an-oauth-2-0-token) is an example.

**Comment by AlexanderLange7** [comment]
Interesting, I was not aware of this fact. I can look into researching this, and updating that documentation much later today. It will be a good learning experience, as there is quite a handful (maybe even a bucket-full) of information regarding oauth2. But I digress, I will do some requests and editing probably around 6:00 CST. 

Thanks!

**Comment by n2ygk** [comment]
> Interesting, I was not aware of this fact. I can look into researching this, and updating that documentation much later today. It will be a good learning experience, as there is quite a handful (maybe even a bucket-full) of information regarding oauth2. But I digress, I will do some requests and editing probably around 6:00 CST.
> 
> Thanks!

@AlexanderLange7 any progress on this?

**Comment by AlexanderLange7** [comment]
Ah, I completely forgot about this, hehe. Life has sort of got in the way recently, hah.

I recently started going down the path of using SAML for the project I was originally using the oauth toolkit for, so I more or less archived the stuff on my machine on oauth toolkit. I was able to sort of figure out how the toolkit works prior to the shift I think? I was able to understand the redirecting to an SSO link thru postman, but that's really it. Haven't been able to go through or look at changing the documentation, or figuring out how the token is passed through the api to application, sorry.

I might get around to it? Might not? Might be able to get away with just linking the given example in the docs?

**Comment by Zorig** [comment]
This consumer service is still down

**Comment by marcusl** [comment]
It's still down, no change to docs.

**Comment by n2ygk** [comment]
> It's still down, no change to docs.

Feel free to submit a documentation PR

**Comment by marcusl** [comment]
As soon as I figure out how to test it manually, or some good description
thereof. Link above did not work. :)

Thanks for making this btw.

Den tis 14 feb. 2023 kl 19:37 skrev Alan Crosswell ***@***.***

**Comment by n2ygk** [comment]
@marcusl I test with Postman... This may be helpful: https://columbia-it-django-jsonapi-training.readthedocs.io/en/latest/using_oauth2/#get-an-oauth-20-token

**Comment by marcusl** [comment]
Getting "invalid_client". Am such a n00b at this. Will dig further. Thanks for quick pingbacks. :)

**Comment by n2ygk** [comment]
Check to make sure you are using PKCE (or have disabled it in settings) and the cleartext `client_secret` prior to it being hashed on save.

**Comment by marcusl** [comment]
adding PKCE (from your link) helped to get postman past authorize and onto token/ which returned that. 
Ahh. I copied the post-hash client secret. Stupid mistake. Works now! 🥳🥳
