### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by adamchainz** [jazzband/django-oauth-toolkit#876]
Hi,

Is it possible to get a new release? There hasn't been one since March, and there have been several commits since. I'm particularly interested in getting the Django 3.1 deprecation warning fixes from @smithdc1 's recent work.

Thanks for a great library,

Adam

**Comment by n2ygk** [comment]
Unfortunately a bunch of commits mere merged without proper documentation and my use in a project has discovered some errors (#873).  I'm not sure if I need to revert the commits to get to a clean release or something else. I don't have a lot of free time to look at this. @auvipy can you?

**Comment by n2ygk** [comment]
@adamchainz I'm reverting #859 since it is huge and was merged without following the process, leading to unexpected errors in existing code. Hopefully this will allow us to put together a release with fewer changes and allow the needed time to fully review and re-merge #859.

See #877.

**Comment by adamchainz** [comment]
Great, thanks for the update. No rush, since one can always mute deprecation warnings :)

**Comment by MattBlack85** [comment]
see #878 for any update

**Comment by adamchainz** [comment]
Thanks @MattBlack85 . I'm closing this issue in favour of following #878.
