### ISSUE TITLE
RELEASE 1.3.3

### ISSUE THREAD

**Issue by MattBlack85** [jazzband/django-oauth-toolkit#878]
Checklist:
- [x] Update the changelog

**Comment by smithdc1** [comment]
I have opened a couple of pull requests which I think would be useful to review and merge ahead of a release

#882 adds support for Django 3.1. It works, but it's not on the test matrix
#883 makes the URL() change this fixes the last remaining deprecation warning on Django 3.1

**Comment by MattBlack85** [comment]
@smithdc1 will try to have a look at them

**Comment by brianhelba** [comment]
@MattBlack85 @n2ygk The release of 1.3.3 was never pushed to PyPI: https://pypi.org/project/django-oauth-toolkit/#history

**Comment by n2ygk** [comment]
Working on it....

**Comment by n2ygk** [comment]
1.3.3. pushed to pypi and rtfd. Still need #890 merged and then the release can be fixed @MattBlack85
