### ISSUE TITLE
Contributing: How to make migrations?

### ISSUE THREAD

**Issue by FluidSense** [jazzband/django-oauth-toolkit#879]
Hello!   
I've been trying to set up `django-oauth-toolkit` locally to try to contribute, but I cannot seem to understand how to make migrations without a `manage.py` file.   
Do you write them manually? Or do you make the migrations from a test project?  
I see some projects like django-wiki contains a test project with just the required functionality to make migrations, but I couldn't find anything as such in this package.   
Any help, guides or links are appreciated!

**Comment by n2ygk** [comment]
Migrations are difficult right now. They have to be created with manage.py and then hand-edited due to attempts at swappable models. We need to fix this if we can. There is an open PR #872 that might help.

**Comment by MattBlack85** [comment]
@FluidSense probably the best way would be to install your local version into some micro django project and run makemigrations

**Comment by FluidSense** [comment]
Thanks! I'll close the issue as my question was answered!
