### ISSUE TITLE
Requesting another access_token using an existing access_token

### ISSUE THREAD

**Issue by mo3rfan** [jazzband/django-oauth-toolkit#885]
Is it possible to request another access token (with a different scope) using an existing access token for a particular user?

Something like a password grant, but instead of sending the password in the request, the current bearer token is sent and a new token will be returned in response.

I don't want to revoke the current access token. (ie, don't want a refresh_token grant type)

**Comment by mo3rfan** [comment]
Never mind I just re-read the [RFC on refresh tokens](https://tools.ietf.org/html/rfc6749#section-1.5) and it looks like refresh tokens can be used to obtain additional access tokens without necessarily revoking the current access token.

**Comment by n2ygk** [comment]
The policy about Access Token revocation is usually settable in the OAuth2
AS.  Implementations may vary. I don't know off hand what the DOT AS does
as I don't use it, but a commercial AS I use has it as a settable option.
