### ISSUE TITLE
Can I store the scopes information in the database?

### ISSUE THREAD

**Issue by vava24680** [jazzband/django-oauth-toolkit#914]
Hi, I am wondering if I can store the scopes in the database instead of in the file?

Thank You~

**Comment by tevansuk** [comment]
See https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html#scopes-backend-class

and https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/scopes.py

You would need to define models to store the scopes, write a class implementing `BaseScopes` that retrieves the data from those models, and set `SCOPES_BACKEND_CLASS="path.to.that.Class` in your settings.

**Comment by vava24680** [comment]
Thanks, I got you. I am closing this issue now.
