### ISSUE TITLE
follow-up to #906

### ISSUE THREAD

**Issue by n2ygk** [jazzband/django-oauth-toolkit#923]
@dag18e @n2ygk I think we added some things here that are not really needed:
1) AFAIK .filter() can't raise DoesNotExist
2) L412 casts the Queryset to a list and then slicing, I do no think this is needed and this slows down things a bit

I feel these things should be addressed in a follow up PR

_Originally posted by @MattBlack85 in https://github.com/jazzband/django-oauth-toolkit/pull/906#discussion_r572176021_

**Comment by dag18e** [comment]
1 is fair.
For number 2, the reason I casted it to a list and then did slicing is that applying a slice directly to the Queryset also threw the LIMIT/OFFSET error I was originally trying to solve.

**Comment by MattBlack85** [comment]
oh ok @dag18e , good to know!

**Comment by n2ygk** [comment]
@MattBlack85 so are we good now. No more changes to #906 or are we waiting on a PR for item 1 above?

**Comment by MattBlack85** [comment]
@n2ygk waiting for PR to fix 1)

**Comment by n2ygk** [comment]
@MattBlack85 I don't think we ever got this PR ^

**Comment by n2ygk** [comment]
> @MattBlack85 I don't think we ever got this PR ^

I've fixed this in b5e2cd5ac
