### ISSUE TITLE
Can't open (actually can't find) the django-oauth-toolkit goolge group ?

### ISSUE THREAD

**Issue by azataiot** [jazzband/django-oauth-toolkit#924]
Can't open (actually can't find or can't access) the django-oauth-toolkit goolge group ?

![image](https://user-images.githubusercontent.com/8280770/107464046-9e921f00-6b89-11eb-8b24-1ecf7f664ff0.png)

**Comment by n2ygk** [comment]
@azataiot I expect this group has disappeared along with other things like the herokuapp app that were set up by the original authors. @synasius or  @masci  if you can confirm this group is gone I'll remove it from the documentation.

Meanwhile, the traffic is low enough that you can submit your questions here.

**Comment by azataiot** [comment]
I've seen that the group is now removed from the documentation, and I think that's a nice move so that people won't be confused.

**Comment by n2ygk** [comment]
It's not removed: https://django-oauth-toolkit.readthedocs.io/en/latest/
