### ISSUE TITLE
redirect_uri encoding issue

### ISSUE THREAD

**Issue by indigodomo** [jazzband/django-oauth-toolkit#941]
With v1.3.0, when an OAuth client passes in the redirect_uri to the authorize view, the url encoded thusly works:

    u = "https://myhost.com/grant-catch"
    u_encoded = urllib.parse.quote(u)
    # results in 'https%3A//myhost.com/grant-catch'

However, a url encoded this way fails with **Invalid redirect URI**:

    u = "https://myhost.com/grant-catch"
    u_encoded = urllib.parse.quote_plus(u)
    # results in 'https%3A%2F%2Fmyhost.com%2Fgrant-catch'

Alexa encodes the redirect URL the latter way, so it doesn't work. I've tried digging through the code but I'm not getting anywhere trying to figure out where it's going wrong. Is this a bug or am I missing something?

**Comment by n2ygk** [comment]
I suspect this hasn't changed but can you please test with 1.4.1 or master branch?

Also, please take a look here to make sure you are encoding the URI correctly: https://tools.ietf.org/html/rfc6749#appendix-B

**Comment by indigodomo** [comment]
I will attempt to do the upgrade at some point, but that would be quite involved for other reasons.

Note that I'm not encoding the URL - Amazon is as part of the Alexa Skills Kit's OAuth implementation. Getting them to change their encoding (if that's the issue) is not going to happen.

**Comment by indigodomo** [comment]
Red herring, sorry about that. I have another question but I'm not sure where to ask it - the Google Group doesn't appear to be working and it doesn't look like github discussions haven't been turned on for this repo yet. Suggestions?

**Comment by n2ygk** [comment]
OK by "red herring" I think you mean to close this? Re-open if I misunderstood.

Oh there's supposed to be a google group? Well I guess there isn't any more. The original maintainers of this project and likely that google group have moved on.

It's time for a documentation fix and I'll ask @jazzband/roadies to see if we can enable github discussions.

**Comment by n2ygk** [comment]
@indigodomo BTW, you can always open a question issue here too...
