### ISSUE TITLE
Can you force all /authorize/ calls to the login page without a redirect?

### ISSUE THREAD

**Issue by indigodomo** [jazzband/django-oauth-toolkit#943]
Apparently Amazon's OAuth implementation for Alexa doesn't like the redirect to the login page from the /authorizations/ view call - it interprets the redirect as an error. Is there some flow that would always present the login view (rather than redirect to it) then proceed with the authorization flow? I found the REQUEST_APPROVAL_PROMPT setting but it's set to "force" by default and I suspect it's only controlling the authorization view.

**Comment by MattBlack85** [comment]
We have been successful using dot with Alexa and I don't recall modifying anything login related!
LWA shouldn't have issues with that, not sure where exactly is the problem honestly

**Comment by indigodomo** [comment]
Tracked it down and it had nothing to do with the redirect (which was the last thing in the apache error log) - during the variety of testing I was doing I managed to get the scope wrong in the alexa skill config. Terrible error from the ASK IMO, but it is what it is. Case closed.
