### ISSUE TITLE
Or in required_scopes

### ISSUE THREAD

**Issue by krzysieqq** [jazzband/django-oauth-toolkit#951]
Hi,
I'm using drf and oauth toolkit with IsAuthenticatedOrTokenHasScope permissions as default. I have a view that contains scopes
`required_scopes = ['mod', 'admin']` When users logs into the app he have special groups which define his permission scope. So when the moderator logs into the app he gets `mod` scope. When he calls my view he gets 403 because `allow_scopes` in AccessToken model returns False. That is because the `resource_scopes` is ['mod', 'admin'] and provided_scopes is 'mod'. When method `allow_scopes` checks `resource_scopes.issubset(provided_scopes)` she returns False which is not intentional in my case.

Is there any other option without overwriting allow_scopes in AccessToken model to define that this view needs scope `mod` or scope `admin`. ?

**Comment by n2ygk** [comment]
I suggest looking at [TokenMatchesOASRequirements](https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/permissions.html?highlight=tokenmatchesoasrequirements#tokenmatchesoasrequirements) which lets you have a list of lists of alternately-allowed scopes.

Furthermore, be aware that you can use boolean operators for `permission_classes` as in this somewhat convoluted example:
```python
permission_classes = [
        (TokenMatchesOASRequirements & IsAuthenticated & MyClaimPermission)
        | (TokenMatchesOASRequirements & ~IsAuthenticated & MyClaimPermission)
        | (IsAuthenticated & MyDjangoModelPermissions)
```
