### ISSUE TITLE
OIDC support with external IDP

### ISSUE THREAD

**Issue by bparmentier** [jazzband/django-oauth-toolkit#961]
I would like to use django-oauth-toolkit with OpenID Connect to authenticate users from an external identity provider (Keycloak).

The setup would be the following: Keycloak - JS front-end - Django/DRF back-end (API). The front-end authenticates users with Keycloak and Keycloak returns a set of JWT access token, refresh token and id token. The access token is then used by the front-end to make API calls to the back-end, identifying the user.

My understanding after testing the latest DOT 1.5.0 release is that OIDC is only supported when using DOT as OIDC Provider. If I define `RESOURCE_SERVER_INTROSPECTION_URL` as described in https://django-oauth-toolkit.readthedocs.io/en/1.5.0/resource_server.html, the call the external introspection endpoint will be done only if I authenticate with a "simple" bearer token, not with a JWT access token, as returned by Keycloak.

To overcome this, I re-implemented the [`validate_jwt_bearer_token`](https://github.com/jazzband/django-oauth-toolkit/blob/1.5.0/oauth2_provider/oauth2_validators.py#L788) method with the code of [`validate_bearer_token`](https://github.com/jazzband/django-oauth-toolkit/blob/1.5.0/oauth2_provider/oauth2_validators.py#L374) (in a custom Oauth2Validator class).

This works but then instead of calling Keycloak's introspection endpoint for nearly every request (Keycloak's access token lifespan is something like 5 min), I would like to simply validate the JWT access token "offline", a bit like what is done in DOT's `validate_jwt_bearer_token`, but this doesn't work in my case since it expects an ID token and a client registered in DOT (btw, isn't the ID token not supposed to be used for authentication?).

I'm not deeply familiar with OIDC, so I am wondering what would be the best approach to take in my case.

**Comment by n2ygk** [comment]
Looks like an enhancement is needed.

**Comment by n2ygk** [comment]
stale. closing
