### ISSUE TITLE
Change JSON based HttpResponse to JSONResponse

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [jazzband/django-oauth-toolkit#987]
https://github.com/jazzband/django-oauth-toolkit/blob/d90bb348f00886ae8321f8194f6275be9aa08f80/oauth2_provider/views/introspect.py#L48-L56

Any reason not to use `django.http.JSONResponse`?

**Comment by auvipy** [comment]
valid point to use jsonresponse
