### ISSUE TITLE
Generated Access token using JWT

### ISSUE THREAD

**Issue by KhoaDauTay** [jazzband/django-oauth-toolkit#990]
- Hi everyone, i'm try generate token with function `signed_token_generator`
- This is my settings:
```
OAUTH2_PROVIDER = {
    "SCOPES_BACKEND_CLASS": "OauthToolket_RestFramework.scopes.ScopesBackend",
    "ACCESS_TOKEN_GENERATOR": "oauthlib.oauth2.rfc6749.tokens.signed_token_generator",
    "OIDC_RSA_PRIVATE_KEY": ""PRIAVATE_KEY""""
}
```
- I try create app with this:
![image](https://user-images.githubusercontent.com/54214642/122915882-75c73500-d386-11eb-8b74-ddbe4cfcf24b.png)

- This is my error, some one can help for problem
![image](https://user-images.githubusercontent.com/54214642/122915944-88416e80-d386-11eb-9752-8eb3facc4cd6.png)

**Comment by haakenlid** [comment]
You can't do it this way. The signed_token_generator has a different return type from the default generator (it's a higher order function).  In any case, a valid JWT would be too long to be stored in the default AccessToken model. 

This issue is related to #757

**Comment by haakenlid** [comment]
I wrote a token generator which uses the HS256 algorithm. The client required a valid JWT access token, but they didn't need to use a specific signing key or validate the signature. So this seems to work ok for my use. 

I think the "exp" claim is required. To ensure unique tokens, I also added a uuid to the payload.

    "ACCESS_TOKEN_GENERATOR": "import.path.to.jwt_token_generator"


```python
from uuid import uuid4
from base64 import b85encode
import jwt  # pip install pyjwt
from django.conf import settings
from django.utils.timezone import now


def jwt_token_generator(
    request=None,
    refresh_token=False,
    key=settings.SECRET_KEY,
    algorithm='HS256',
):
    """Generate a JWT access token with jti and exp claims
    jti - The "jti" (JWT ID) claim provides a unique identifier for the JWT.)
    exp - The "exp" (expiration time) claim identifies the expiration time
    Uses HS256 to sign and django SECRET_KEY as key.
    The minimal payload results in a token length of ca 144 bytes with the
    HMAC.SHA-256 algorithm
    """

    seconds = request.expires_in if request else 36000
    exp = int(now().timestamp()) + seconds
    jti = b85encode(uuid4().bytes).decode()

    claims = {"jti": jti, "exp": exp}
    return jwt.encode(claims, key, algorithm)
```
