### ISSUE TITLE
How to retrieve id_token for OIDC

### ISSUE THREAD

**Issue by emrulhaikal** [jazzband/django-oauth-toolkit#992]
Hi,

First of all I would like to say thank you for his great library. I have a question regarding OIDC id_token. I followed the instruction in https://django-oauth-toolkit.readthedocs.io/en/stable/oidc.html#openid-connect-support documentation on how to setup the OIDC. When I tried to do POST request in the Postman, I unable to retrieve the id_token. Please see the attachment as the reference. I am using React as a SPA and Django as the API. Thanks for all the help.

![post_request](https://user-images.githubusercontent.com/38237803/124126542-5c706800-daad-11eb-8e8d-1ccb50e2983b.png)

**Comment by dopry** [comment]
@emrulhaikal if this is still an issue for you, please re-open and share your application setup. If you were able to resolve it, please comment with details about what worked for you. Thanks!
