### ISSUE TITLE
OpenIDC endpoints

### ISSUE THREAD

**Issue by Jenm78** [jazzband/django-oauth-toolkit#999]
I am been using Django Oauth toolkit to implement an autenticacion service with Basic bearer token. No problems so far. 
However, I am now trying to change to the use of JWT tokens. I configure everything in the settings.py as the documentation indicates. I also create a private key using openssl, but when I try to access to the endpoints like http://mydomain/o/.well-known/openid-configuration/, it could not be resolved, answering me a 404 error. 

In the other hand, when I use the token endpoint  http://mydomain/o/token/ the token answered is the same kind of bearer token I had before, not a JWT token. 

Please, I will appreciate any help you can give me.

**Comment by dopry** [comment]
It sounds like you might not be using an OIDC flow that would issue an identity token. IIRC only Identity tokens are JWTs at present.  If you were able to figure this out, please add a comment explaining what you did. If you still need help, please re-open with more detail about how you have setup your site and application.
